using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    /// <summary>
    /// Controller class for AggregatedCounter
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class AggregatedCounterController
    {
        // Preload our schema..
        AggregatedCounter thisSchemaLoad = new AggregatedCounter();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public AggregatedCounterCollection FetchAll()
        {
            AggregatedCounterCollection coll = new AggregatedCounterCollection();
            Query qry = new Query(AggregatedCounter.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public AggregatedCounterCollection FetchByID(object Key)
        {
            AggregatedCounterCollection coll = new AggregatedCounterCollection().Where("Key", Key).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public AggregatedCounterCollection FetchByQuery(Query qry)
        {
            AggregatedCounterCollection coll = new AggregatedCounterCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Key)
        {
            return (AggregatedCounter.Delete(Key) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Key)
        {
            return (AggregatedCounter.Destroy(Key) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Key,long ValueX,DateTime? ExpireAt)
	    {
		    AggregatedCounter item = new AggregatedCounter();
		    
            item.Key = Key;
            
            item.ValueX = ValueX;
            
            item.ExpireAt = ExpireAt;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string Key,long ValueX,DateTime? ExpireAt)
	    {
		    AggregatedCounter item = new AggregatedCounter();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Key = Key;
				
			item.ValueX = ValueX;
				
			item.ExpireAt = ExpireAt;
				
	        item.Save(UserName);
	    }
    }
}
