using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the AggregatedCounter class.
	/// </summary>
    [Serializable]
	public partial class AggregatedCounterCollection : ActiveList<AggregatedCounter, AggregatedCounterCollection>
	{	   
		public AggregatedCounterCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>AggregatedCounterCollection</returns>
		public AggregatedCounterCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                AggregatedCounter o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the AggregatedCounter table.
	/// </summary>
	[Serializable]
	public partial class AggregatedCounter : ActiveRecord<AggregatedCounter>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public AggregatedCounter()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public AggregatedCounter(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public AggregatedCounter(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public AggregatedCounter(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("AggregatedCounter", TableType.Table, DataService.GetInstance("DataAccessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"HangFire";
				//columns
				
				TableSchema.TableColumn colvarKey = new TableSchema.TableColumn(schema);
				colvarKey.ColumnName = "Key";
				colvarKey.DataType = DbType.String;
				colvarKey.MaxLength = 100;
				colvarKey.AutoIncrement = false;
				colvarKey.IsNullable = false;
				colvarKey.IsPrimaryKey = true;
				colvarKey.IsForeignKey = false;
				colvarKey.IsReadOnly = false;
				colvarKey.DefaultSetting = @"";
				colvarKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarKey);
				
				TableSchema.TableColumn colvarValueX = new TableSchema.TableColumn(schema);
				colvarValueX.ColumnName = "Value";
				colvarValueX.DataType = DbType.Int64;
				colvarValueX.MaxLength = 0;
				colvarValueX.AutoIncrement = false;
				colvarValueX.IsNullable = false;
				colvarValueX.IsPrimaryKey = false;
				colvarValueX.IsForeignKey = false;
				colvarValueX.IsReadOnly = false;
				colvarValueX.DefaultSetting = @"";
				colvarValueX.ForeignKeyTableName = "";
				schema.Columns.Add(colvarValueX);
				
				TableSchema.TableColumn colvarExpireAt = new TableSchema.TableColumn(schema);
				colvarExpireAt.ColumnName = "ExpireAt";
				colvarExpireAt.DataType = DbType.DateTime;
				colvarExpireAt.MaxLength = 0;
				colvarExpireAt.AutoIncrement = false;
				colvarExpireAt.IsNullable = true;
				colvarExpireAt.IsPrimaryKey = false;
				colvarExpireAt.IsForeignKey = false;
				colvarExpireAt.IsReadOnly = false;
				colvarExpireAt.DefaultSetting = @"";
				colvarExpireAt.ForeignKeyTableName = "";
				schema.Columns.Add(colvarExpireAt);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAccessProvider"].AddSchema("AggregatedCounter",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Key")]
		[Bindable(true)]
		public string Key 
		{
			get { return GetColumnValue<string>(Columns.Key); }
			set { SetColumnValue(Columns.Key, value); }
		}
		  
		[XmlAttribute("ValueX")]
		[Bindable(true)]
		public long ValueX 
		{
			get { return GetColumnValue<long>(Columns.ValueX); }
			set { SetColumnValue(Columns.ValueX, value); }
		}
		  
		[XmlAttribute("ExpireAt")]
		[Bindable(true)]
		public DateTime? ExpireAt 
		{
			get { return GetColumnValue<DateTime?>(Columns.ExpireAt); }
			set { SetColumnValue(Columns.ExpireAt, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varKey,long varValueX,DateTime? varExpireAt)
		{
			AggregatedCounter item = new AggregatedCounter();
			
			item.Key = varKey;
			
			item.ValueX = varValueX;
			
			item.ExpireAt = varExpireAt;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(string varKey,long varValueX,DateTime? varExpireAt)
		{
			AggregatedCounter item = new AggregatedCounter();
			
				item.Key = varKey;
			
				item.ValueX = varValueX;
			
				item.ExpireAt = varExpireAt;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn KeyColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn ValueXColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn ExpireAtColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Key = @"Key";
			 public static string ValueX = @"Value";
			 public static string ExpireAt = @"ExpireAt";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
