using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    /// <summary>
    /// Controller class for Job
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class JobController
    {
        // Preload our schema..
        Job thisSchemaLoad = new Job();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public JobCollection FetchAll()
        {
            JobCollection coll = new JobCollection();
            Query qry = new Query(Job.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public JobCollection FetchByID(object Id)
        {
            JobCollection coll = new JobCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public JobCollection FetchByQuery(Query qry)
        {
            JobCollection coll = new JobCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (Job.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (Job.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(long? StateId,string StateName,string InvocationData,string Arguments,DateTime CreatedAt,DateTime? ExpireAt)
	    {
		    Job item = new Job();
		    
            item.StateId = StateId;
            
            item.StateName = StateName;
            
            item.InvocationData = InvocationData;
            
            item.Arguments = Arguments;
            
            item.CreatedAt = CreatedAt;
            
            item.ExpireAt = ExpireAt;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(long Id,long? StateId,string StateName,string InvocationData,string Arguments,DateTime CreatedAt,DateTime? ExpireAt)
	    {
		    Job item = new Job();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.StateId = StateId;
				
			item.StateName = StateName;
				
			item.InvocationData = InvocationData;
				
			item.Arguments = Arguments;
				
			item.CreatedAt = CreatedAt;
				
			item.ExpireAt = ExpireAt;
				
	        item.Save(UserName);
	    }
    }
}
