using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    /// <summary>
    /// Controller class for State
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class StateController
    {
        // Preload our schema..
        State thisSchemaLoad = new State();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public StateCollection FetchAll()
        {
            StateCollection coll = new StateCollection();
            Query qry = new Query(State.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public StateCollection FetchByID(object Id)
        {
            StateCollection coll = new StateCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public StateCollection FetchByQuery(Query qry)
        {
            StateCollection coll = new StateCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (State.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (State.Destroy(Id) == 1);
        }
        
        
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(long Id,long JobId)
        {
            Query qry = new Query(State.Schema);
            qry.QueryType = QueryType.Delete;
            qry.AddWhere("Id", Id).AND("JobId", JobId);
            qry.Execute();
            return (true);
        }        
       
    	
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(long JobId,string Name,string Reason,DateTime CreatedAt,string Data)
	    {
		    State item = new State();
		    
            item.JobId = JobId;
            
            item.Name = Name;
            
            item.Reason = Reason;
            
            item.CreatedAt = CreatedAt;
            
            item.Data = Data;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(long Id,long JobId,string Name,string Reason,DateTime CreatedAt,string Data)
	    {
		    State item = new State();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.JobId = JobId;
				
			item.Name = Name;
				
			item.Reason = Reason;
				
			item.CreatedAt = CreatedAt;
				
			item.Data = Data;
				
	        item.Save(UserName);
	    }
    }
}
