using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    /// <summary>
    /// Controller class for TblChucDanh
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblChucDanhController
    {
        // Preload our schema..
        TblChucDanh thisSchemaLoad = new TblChucDanh();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblChucDanhCollection FetchAll()
        {
            TblChucDanhCollection coll = new TblChucDanhCollection();
            Query qry = new Query(TblChucDanh.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblChucDanhCollection FetchByID(object IdChucDanh)
        {
            TblChucDanhCollection coll = new TblChucDanhCollection().Where("IdChucDanh", IdChucDanh).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblChucDanhCollection FetchByQuery(Query qry)
        {
            TblChucDanhCollection coll = new TblChucDanhCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdChucDanh)
        {
            return (TblChucDanh.Delete(IdChucDanh) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdChucDanh)
        {
            return (TblChucDanh.Destroy(IdChucDanh) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid IdChucDanh,Guid? IdPhongBan,string TenChucDanh,string MoTa,int ThuTuHienThi,bool KichHoat,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
	    {
		    TblChucDanh item = new TblChucDanh();
		    
            item.IdChucDanh = IdChucDanh;
            
            item.IdPhongBan = IdPhongBan;
            
            item.TenChucDanh = TenChucDanh;
            
            item.MoTa = MoTa;
            
            item.ThuTuHienThi = ThuTuHienThi;
            
            item.KichHoat = KichHoat;
            
            item.DaXoa = DaXoa;
            
            item.NguoiTao = NguoiTao;
            
            item.NgayTao = NgayTao;
            
            item.NguoiCapNhat = NguoiCapNhat;
            
            item.NgayCapNhat = NgayCapNhat;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid IdChucDanh,Guid? IdPhongBan,string TenChucDanh,string MoTa,int ThuTuHienThi,bool KichHoat,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
	    {
		    TblChucDanh item = new TblChucDanh();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.IdChucDanh = IdChucDanh;
				
			item.IdPhongBan = IdPhongBan;
				
			item.TenChucDanh = TenChucDanh;
				
			item.MoTa = MoTa;
				
			item.ThuTuHienThi = ThuTuHienThi;
				
			item.KichHoat = KichHoat;
				
			item.DaXoa = DaXoa;
				
			item.NguoiTao = NguoiTao;
				
			item.NgayTao = NgayTao;
				
			item.NguoiCapNhat = NguoiCapNhat;
				
			item.NgayCapNhat = NgayCapNhat;
				
	        item.Save(UserName);
	    }
    }
}
