using System;
using System.ComponentModel;
using SubSonic;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    [DataObject]
    public partial class TblCauHinhTuanLamViecController
    {
        private readonly TblCauHinhTuanLamViec schemaLoader = new TblCauHinhTuanLamViec();
        private string UserName
        {
            get
            {
                return System.Web.HttpContext.Current != null
                    ? System.Web.HttpContext.Current.User.Identity.Name
                    : System.Threading.Thread.CurrentPrincipal.Identity.Name;
            }
        }

        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblCauHinhTuanLamViecCollection FetchAll()
        {
            TblCauHinhTuanLamViecCollection collection = new TblCauHinhTuanLamViecCollection();
            Query query = new Query(TblCauHinhTuanLamViec.Schema);
            collection.LoadAndCloseReader(query.ExecuteReader());
            return collection;
        }

        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblCauHinhTuanLamViecCollection FetchByID(object IdCauHinh)
        {
            return new TblCauHinhTuanLamViecCollection().Where("IdCauHinh", IdCauHinh).Load();
        }

        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdCauHinh) { return TblCauHinhTuanLamViec.Delete(IdCauHinh) == 1; }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdCauHinh) { return TblCauHinhTuanLamViec.Destroy(IdCauHinh) == 1; }

        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblCauHinhTuanLamViecCollection FetchByQuery(Query query)
        {
            TblCauHinhTuanLamViecCollection collection = new TblCauHinhTuanLamViecCollection();
            collection.LoadAndCloseReader(query.ExecuteReader());
            return collection;
        }

        [DataObjectMethod(DataObjectMethodType.Insert, true)]
        public void Insert(Guid IdCauHinh,byte NgayTrongTuan,bool LaNgayLamViec,TimeSpan? GioBatDauSang,TimeSpan? GioKetThucSang,TimeSpan? GioBatDauChieu,TimeSpan? GioKetThucChieu,string NguoiTao,DateTime? NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
        {
            TblCauHinhTuanLamViec item = new TblCauHinhTuanLamViec();
            item.IdCauHinh = IdCauHinh;
            item.NgayTrongTuan = NgayTrongTuan;
            item.LaNgayLamViec = LaNgayLamViec;
            item.GioBatDauSang = GioBatDauSang;
            item.GioKetThucSang = GioKetThucSang;
            item.GioBatDauChieu = GioBatDauChieu;
            item.GioKetThucChieu = GioKetThucChieu;
            item.NguoiTao = NguoiTao;
            item.NgayTao = NgayTao;
            item.NguoiCapNhat = NguoiCapNhat;
            item.NgayCapNhat = NgayCapNhat;
            item.Save(UserName);
        }

        [DataObjectMethod(DataObjectMethodType.Update, true)]
        public void Update(Guid IdCauHinh,byte NgayTrongTuan,bool LaNgayLamViec,TimeSpan? GioBatDauSang,TimeSpan? GioKetThucSang,TimeSpan? GioBatDauChieu,TimeSpan? GioKetThucChieu,string NguoiTao,DateTime? NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
        {
            TblCauHinhTuanLamViec item = new TblCauHinhTuanLamViec();
            item.MarkOld();
            item.IsLoaded = true;
            item.IdCauHinh = IdCauHinh;
            item.NgayTrongTuan = NgayTrongTuan;
            item.LaNgayLamViec = LaNgayLamViec;
            item.GioBatDauSang = GioBatDauSang;
            item.GioKetThucSang = GioKetThucSang;
            item.GioBatDauChieu = GioBatDauChieu;
            item.GioKetThucChieu = GioKetThucChieu;
            item.NguoiTao = NguoiTao;
            item.NgayTao = NgayTao;
            item.NguoiCapNhat = NguoiCapNhat;
            item.NgayCapNhat = NgayCapNhat;
            item.Save(UserName);
        }
    }
}
