using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    /// <summary>
    /// Controller class for TblEmailHistory
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblEmailHistoryController
    {
        // Preload our schema..
        TblEmailHistory thisSchemaLoad = new TblEmailHistory();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblEmailHistoryCollection FetchAll()
        {
            TblEmailHistoryCollection coll = new TblEmailHistoryCollection();
            Query qry = new Query(TblEmailHistory.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblEmailHistoryCollection FetchByID(object Id)
        {
            TblEmailHistoryCollection coll = new TblEmailHistoryCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblEmailHistoryCollection FetchByQuery(Query qry)
        {
            TblEmailHistoryCollection coll = new TblEmailHistoryCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblEmailHistory.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblEmailHistory.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid Id,string CreatedUser,DateTime CreatedDate,string UpdatedUser,DateTime UpdatedDate,Guid RefId,string RefType,Guid? SenderId,DateTime? SentDate,string Sender,string Subject,string EmailContent,Guid CustomerId,string ServerMail,string FromEmail,string ToEmail,string CcEmail,string BccEmail,bool IsSent,bool IsRead,DateTime? ReadDate,int NumberOfSent,string ErrorMessage)
	    {
		    TblEmailHistory item = new TblEmailHistory();
		    
            item.Id = Id;
            
            item.CreatedUser = CreatedUser;
            
            item.CreatedDate = CreatedDate;
            
            item.UpdatedUser = UpdatedUser;
            
            item.UpdatedDate = UpdatedDate;
            
            item.RefId = RefId;
            
            item.RefType = RefType;
            
            item.SenderId = SenderId;
            
            item.SentDate = SentDate;
            
            item.Sender = Sender;
            
            item.Subject = Subject;
            
            item.EmailContent = EmailContent;
            
            item.CustomerId = CustomerId;
            
            item.ServerMail = ServerMail;
            
            item.FromEmail = FromEmail;
            
            item.ToEmail = ToEmail;
            
            item.CcEmail = CcEmail;
            
            item.BccEmail = BccEmail;
            
            item.IsSent = IsSent;
            
            item.IsRead = IsRead;
            
            item.ReadDate = ReadDate;
            
            item.NumberOfSent = NumberOfSent;
            
            item.ErrorMessage = ErrorMessage;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid Id,string CreatedUser,DateTime CreatedDate,string UpdatedUser,DateTime UpdatedDate,Guid RefId,string RefType,Guid? SenderId,DateTime? SentDate,string Sender,string Subject,string EmailContent,Guid CustomerId,string ServerMail,string FromEmail,string ToEmail,string CcEmail,string BccEmail,bool IsSent,bool IsRead,DateTime? ReadDate,int NumberOfSent,string ErrorMessage)
	    {
		    TblEmailHistory item = new TblEmailHistory();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.CreatedUser = CreatedUser;
				
			item.CreatedDate = CreatedDate;
				
			item.UpdatedUser = UpdatedUser;
				
			item.UpdatedDate = UpdatedDate;
				
			item.RefId = RefId;
				
			item.RefType = RefType;
				
			item.SenderId = SenderId;
				
			item.SentDate = SentDate;
				
			item.Sender = Sender;
				
			item.Subject = Subject;
				
			item.EmailContent = EmailContent;
				
			item.CustomerId = CustomerId;
				
			item.ServerMail = ServerMail;
				
			item.FromEmail = FromEmail;
				
			item.ToEmail = ToEmail;
				
			item.CcEmail = CcEmail;
				
			item.BccEmail = BccEmail;
				
			item.IsSent = IsSent;
				
			item.IsRead = IsRead;
				
			item.ReadDate = ReadDate;
				
			item.NumberOfSent = NumberOfSent;
				
			item.ErrorMessage = ErrorMessage;
				
	        item.Save(UserName);
	    }
    }
}
