using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblKhachHang class.
	/// </summary>
    [Serializable]
	public partial class TblKhachHangCollection : ActiveList<TblKhachHang, TblKhachHangCollection>
	{	   
		public TblKhachHangCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblKhachHangCollection</returns>
		public TblKhachHangCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblKhachHang o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblKhachHang table.
	/// </summary>
	[Serializable]
	public partial class TblKhachHang : ActiveRecord<TblKhachHang>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblKhachHang()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblKhachHang(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblKhachHang(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblKhachHang(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblKhachHang", TableType.Table, DataService.GetInstance("DataAccessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarIdKhachHang = new TableSchema.TableColumn(schema);
				colvarIdKhachHang.ColumnName = "IdKhachHang";
				colvarIdKhachHang.DataType = DbType.Guid;
				colvarIdKhachHang.MaxLength = 0;
				colvarIdKhachHang.AutoIncrement = false;
				colvarIdKhachHang.IsNullable = false;
				colvarIdKhachHang.IsPrimaryKey = true;
				colvarIdKhachHang.IsForeignKey = false;
				colvarIdKhachHang.IsReadOnly = false;
				
						colvarIdKhachHang.DefaultSetting = @"(newid())";
				colvarIdKhachHang.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIdKhachHang);
				
				TableSchema.TableColumn colvarTenKhachHang = new TableSchema.TableColumn(schema);
				colvarTenKhachHang.ColumnName = "TenKhachHang";
				colvarTenKhachHang.DataType = DbType.String;
				colvarTenKhachHang.MaxLength = 250;
				colvarTenKhachHang.AutoIncrement = false;
				colvarTenKhachHang.IsNullable = false;
				colvarTenKhachHang.IsPrimaryKey = false;
				colvarTenKhachHang.IsForeignKey = false;
				colvarTenKhachHang.IsReadOnly = false;
				colvarTenKhachHang.DefaultSetting = @"";
				colvarTenKhachHang.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTenKhachHang);
				
				TableSchema.TableColumn colvarIdLoaiKhachHang = new TableSchema.TableColumn(schema);
				colvarIdLoaiKhachHang.ColumnName = "IdLoaiKhachHang";
				colvarIdLoaiKhachHang.DataType = DbType.Guid;
				colvarIdLoaiKhachHang.MaxLength = 0;
				colvarIdLoaiKhachHang.AutoIncrement = false;
				colvarIdLoaiKhachHang.IsNullable = false;
				colvarIdLoaiKhachHang.IsPrimaryKey = false;
				colvarIdLoaiKhachHang.IsForeignKey = true;
				colvarIdLoaiKhachHang.IsReadOnly = false;
				colvarIdLoaiKhachHang.DefaultSetting = @"";
				
					colvarIdLoaiKhachHang.ForeignKeyTableName = "TblLoaiKhachHang";
				schema.Columns.Add(colvarIdLoaiKhachHang);
				
				TableSchema.TableColumn colvarIdSoThue = new TableSchema.TableColumn(schema);
				colvarIdSoThue.ColumnName = "IdSoThue";
				colvarIdSoThue.DataType = DbType.AnsiString;
				colvarIdSoThue.MaxLength = 50;
				colvarIdSoThue.AutoIncrement = false;
				colvarIdSoThue.IsNullable = true;
				colvarIdSoThue.IsPrimaryKey = false;
				colvarIdSoThue.IsForeignKey = false;
				colvarIdSoThue.IsReadOnly = false;
				colvarIdSoThue.DefaultSetting = @"";
				colvarIdSoThue.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIdSoThue);
				
				TableSchema.TableColumn colvarSoDienThoai = new TableSchema.TableColumn(schema);
				colvarSoDienThoai.ColumnName = "SoDienThoai";
				colvarSoDienThoai.DataType = DbType.AnsiString;
				colvarSoDienThoai.MaxLength = 30;
				colvarSoDienThoai.AutoIncrement = false;
				colvarSoDienThoai.IsNullable = true;
				colvarSoDienThoai.IsPrimaryKey = false;
				colvarSoDienThoai.IsForeignKey = false;
				colvarSoDienThoai.IsReadOnly = false;
				colvarSoDienThoai.DefaultSetting = @"";
				colvarSoDienThoai.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSoDienThoai);
				
				TableSchema.TableColumn colvarThuDienTu = new TableSchema.TableColumn(schema);
				colvarThuDienTu.ColumnName = "ThuDienTu";
				colvarThuDienTu.DataType = DbType.String;
				colvarThuDienTu.MaxLength = 256;
				colvarThuDienTu.AutoIncrement = false;
				colvarThuDienTu.IsNullable = true;
				colvarThuDienTu.IsPrimaryKey = false;
				colvarThuDienTu.IsForeignKey = false;
				colvarThuDienTu.IsReadOnly = false;
				colvarThuDienTu.DefaultSetting = @"";
				colvarThuDienTu.ForeignKeyTableName = "";
				schema.Columns.Add(colvarThuDienTu);
				
				TableSchema.TableColumn colvarDiaChi = new TableSchema.TableColumn(schema);
				colvarDiaChi.ColumnName = "DiaChi";
				colvarDiaChi.DataType = DbType.String;
				colvarDiaChi.MaxLength = 500;
				colvarDiaChi.AutoIncrement = false;
				colvarDiaChi.IsNullable = true;
				colvarDiaChi.IsPrimaryKey = false;
				colvarDiaChi.IsForeignKey = false;
				colvarDiaChi.IsReadOnly = false;
				colvarDiaChi.DefaultSetting = @"";
				colvarDiaChi.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDiaChi);
				
				TableSchema.TableColumn colvarTenNguoiDaiDien = new TableSchema.TableColumn(schema);
				colvarTenNguoiDaiDien.ColumnName = "TenNguoiDaiDien";
				colvarTenNguoiDaiDien.DataType = DbType.String;
				colvarTenNguoiDaiDien.MaxLength = 250;
				colvarTenNguoiDaiDien.AutoIncrement = false;
				colvarTenNguoiDaiDien.IsNullable = true;
				colvarTenNguoiDaiDien.IsPrimaryKey = false;
				colvarTenNguoiDaiDien.IsForeignKey = false;
				colvarTenNguoiDaiDien.IsReadOnly = false;
				colvarTenNguoiDaiDien.DefaultSetting = @"";
				colvarTenNguoiDaiDien.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTenNguoiDaiDien);
				
				TableSchema.TableColumn colvarTenNguoiLienHe = new TableSchema.TableColumn(schema);
				colvarTenNguoiLienHe.ColumnName = "TenNguoiLienHe";
				colvarTenNguoiLienHe.DataType = DbType.String;
				colvarTenNguoiLienHe.MaxLength = 250;
				colvarTenNguoiLienHe.AutoIncrement = false;
				colvarTenNguoiLienHe.IsNullable = true;
				colvarTenNguoiLienHe.IsPrimaryKey = false;
				colvarTenNguoiLienHe.IsForeignKey = false;
				colvarTenNguoiLienHe.IsReadOnly = false;
				colvarTenNguoiLienHe.DefaultSetting = @"";
				colvarTenNguoiLienHe.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTenNguoiLienHe);
				
				TableSchema.TableColumn colvarDienThoaiLienHe = new TableSchema.TableColumn(schema);
				colvarDienThoaiLienHe.ColumnName = "DienThoaiLienHe";
				colvarDienThoaiLienHe.DataType = DbType.AnsiString;
				colvarDienThoaiLienHe.MaxLength = 30;
				colvarDienThoaiLienHe.AutoIncrement = false;
				colvarDienThoaiLienHe.IsNullable = true;
				colvarDienThoaiLienHe.IsPrimaryKey = false;
				colvarDienThoaiLienHe.IsForeignKey = false;
				colvarDienThoaiLienHe.IsReadOnly = false;
				colvarDienThoaiLienHe.DefaultSetting = @"";
				colvarDienThoaiLienHe.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDienThoaiLienHe);
				
				TableSchema.TableColumn colvarEmail = new TableSchema.TableColumn(schema);
				colvarEmail.ColumnName = "Email";
				colvarEmail.DataType = DbType.String;
				colvarEmail.MaxLength = 256;
				colvarEmail.AutoIncrement = false;
				colvarEmail.IsNullable = true;
				colvarEmail.IsPrimaryKey = false;
				colvarEmail.IsForeignKey = false;
				colvarEmail.IsReadOnly = false;
				colvarEmail.DefaultSetting = @"";
				colvarEmail.ForeignKeyTableName = "";
				schema.Columns.Add(colvarEmail);
				
				TableSchema.TableColumn colvarGhiChu = new TableSchema.TableColumn(schema);
				colvarGhiChu.ColumnName = "GhiChu";
				colvarGhiChu.DataType = DbType.String;
				colvarGhiChu.MaxLength = 1000;
				colvarGhiChu.AutoIncrement = false;
				colvarGhiChu.IsNullable = true;
				colvarGhiChu.IsPrimaryKey = false;
				colvarGhiChu.IsForeignKey = false;
				colvarGhiChu.IsReadOnly = false;
				colvarGhiChu.DefaultSetting = @"";
				colvarGhiChu.ForeignKeyTableName = "";
				schema.Columns.Add(colvarGhiChu);
				
				TableSchema.TableColumn colvarKichHoat = new TableSchema.TableColumn(schema);
				colvarKichHoat.ColumnName = "KichHoat";
				colvarKichHoat.DataType = DbType.Boolean;
				colvarKichHoat.MaxLength = 0;
				colvarKichHoat.AutoIncrement = false;
				colvarKichHoat.IsNullable = false;
				colvarKichHoat.IsPrimaryKey = false;
				colvarKichHoat.IsForeignKey = false;
				colvarKichHoat.IsReadOnly = false;
				
						colvarKichHoat.DefaultSetting = @"((1))";
				colvarKichHoat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarKichHoat);
				
				TableSchema.TableColumn colvarDaXoa = new TableSchema.TableColumn(schema);
				colvarDaXoa.ColumnName = "DaXoa";
				colvarDaXoa.DataType = DbType.Boolean;
				colvarDaXoa.MaxLength = 0;
				colvarDaXoa.AutoIncrement = false;
				colvarDaXoa.IsNullable = false;
				colvarDaXoa.IsPrimaryKey = false;
				colvarDaXoa.IsForeignKey = false;
				colvarDaXoa.IsReadOnly = false;
				
						colvarDaXoa.DefaultSetting = @"((0))";
				colvarDaXoa.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDaXoa);
				
				TableSchema.TableColumn colvarNguoiTao = new TableSchema.TableColumn(schema);
				colvarNguoiTao.ColumnName = "NguoiTao";
				colvarNguoiTao.DataType = DbType.String;
				colvarNguoiTao.MaxLength = 150;
				colvarNguoiTao.AutoIncrement = false;
				colvarNguoiTao.IsNullable = false;
				colvarNguoiTao.IsPrimaryKey = false;
				colvarNguoiTao.IsForeignKey = false;
				colvarNguoiTao.IsReadOnly = false;
				colvarNguoiTao.DefaultSetting = @"";
				colvarNguoiTao.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNguoiTao);
				
				TableSchema.TableColumn colvarNgayTao = new TableSchema.TableColumn(schema);
				colvarNgayTao.ColumnName = "NgayTao";
				colvarNgayTao.DataType = DbType.DateTime;
				colvarNgayTao.MaxLength = 0;
				colvarNgayTao.AutoIncrement = false;
				colvarNgayTao.IsNullable = false;
				colvarNgayTao.IsPrimaryKey = false;
				colvarNgayTao.IsForeignKey = false;
				colvarNgayTao.IsReadOnly = false;
				
						colvarNgayTao.DefaultSetting = @"(getdate())";
				colvarNgayTao.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayTao);
				
				TableSchema.TableColumn colvarNguoiCapNhat = new TableSchema.TableColumn(schema);
				colvarNguoiCapNhat.ColumnName = "NguoiCapNhat";
				colvarNguoiCapNhat.DataType = DbType.String;
				colvarNguoiCapNhat.MaxLength = 150;
				colvarNguoiCapNhat.AutoIncrement = false;
				colvarNguoiCapNhat.IsNullable = true;
				colvarNguoiCapNhat.IsPrimaryKey = false;
				colvarNguoiCapNhat.IsForeignKey = false;
				colvarNguoiCapNhat.IsReadOnly = false;
				colvarNguoiCapNhat.DefaultSetting = @"";
				colvarNguoiCapNhat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNguoiCapNhat);
				
				TableSchema.TableColumn colvarNgayCapNhat = new TableSchema.TableColumn(schema);
				colvarNgayCapNhat.ColumnName = "NgayCapNhat";
				colvarNgayCapNhat.DataType = DbType.DateTime;
				colvarNgayCapNhat.MaxLength = 0;
				colvarNgayCapNhat.AutoIncrement = false;
				colvarNgayCapNhat.IsNullable = true;
				colvarNgayCapNhat.IsPrimaryKey = false;
				colvarNgayCapNhat.IsForeignKey = false;
				colvarNgayCapNhat.IsReadOnly = false;
				colvarNgayCapNhat.DefaultSetting = @"";
				colvarNgayCapNhat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayCapNhat);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAccessProvider"].AddSchema("TblKhachHang",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("IdKhachHang")]
		[Bindable(true)]
		public Guid IdKhachHang 
		{
			get { return GetColumnValue<Guid>(Columns.IdKhachHang); }
			set { SetColumnValue(Columns.IdKhachHang, value); }
		}
		  
		[XmlAttribute("TenKhachHang")]
		[Bindable(true)]
		public string TenKhachHang 
		{
			get { return GetColumnValue<string>(Columns.TenKhachHang); }
			set { SetColumnValue(Columns.TenKhachHang, value); }
		}
		  
		[XmlAttribute("IdLoaiKhachHang")]
		[Bindable(true)]
		public Guid IdLoaiKhachHang 
		{
			get { return GetColumnValue<Guid>(Columns.IdLoaiKhachHang); }
			set { SetColumnValue(Columns.IdLoaiKhachHang, value); }
		}
		  
		[XmlAttribute("IdSoThue")]
		[Bindable(true)]
		public string IdSoThue 
		{
			get { return GetColumnValue<string>(Columns.IdSoThue); }
			set { SetColumnValue(Columns.IdSoThue, value); }
		}
		  
		[XmlAttribute("SoDienThoai")]
		[Bindable(true)]
		public string SoDienThoai 
		{
			get { return GetColumnValue<string>(Columns.SoDienThoai); }
			set { SetColumnValue(Columns.SoDienThoai, value); }
		}
		  
		[XmlAttribute("ThuDienTu")]
		[Bindable(true)]
		public string ThuDienTu 
		{
			get { return GetColumnValue<string>(Columns.ThuDienTu); }
			set { SetColumnValue(Columns.ThuDienTu, value); }
		}
		  
		[XmlAttribute("DiaChi")]
		[Bindable(true)]
		public string DiaChi 
		{
			get { return GetColumnValue<string>(Columns.DiaChi); }
			set { SetColumnValue(Columns.DiaChi, value); }
		}
		  
		[XmlAttribute("TenNguoiDaiDien")]
		[Bindable(true)]
		public string TenNguoiDaiDien 
		{
			get { return GetColumnValue<string>(Columns.TenNguoiDaiDien); }
			set { SetColumnValue(Columns.TenNguoiDaiDien, value); }
		}
		  
		[XmlAttribute("TenNguoiLienHe")]
		[Bindable(true)]
		public string TenNguoiLienHe 
		{
			get { return GetColumnValue<string>(Columns.TenNguoiLienHe); }
			set { SetColumnValue(Columns.TenNguoiLienHe, value); }
		}
		  
		[XmlAttribute("DienThoaiLienHe")]
		[Bindable(true)]
		public string DienThoaiLienHe 
		{
			get { return GetColumnValue<string>(Columns.DienThoaiLienHe); }
			set { SetColumnValue(Columns.DienThoaiLienHe, value); }
		}
		  
		[XmlAttribute("Email")]
		[Bindable(true)]
		public string Email 
		{
			get { return GetColumnValue<string>(Columns.Email); }
			set { SetColumnValue(Columns.Email, value); }
		}
		  
		[XmlAttribute("GhiChu")]
		[Bindable(true)]
		public string GhiChu 
		{
			get { return GetColumnValue<string>(Columns.GhiChu); }
			set { SetColumnValue(Columns.GhiChu, value); }
		}
		  
		[XmlAttribute("KichHoat")]
		[Bindable(true)]
		public bool KichHoat 
		{
			get { return GetColumnValue<bool>(Columns.KichHoat); }
			set { SetColumnValue(Columns.KichHoat, value); }
		}
		  
		[XmlAttribute("DaXoa")]
		[Bindable(true)]
		public bool DaXoa 
		{
			get { return GetColumnValue<bool>(Columns.DaXoa); }
			set { SetColumnValue(Columns.DaXoa, value); }
		}
		  
		[XmlAttribute("NguoiTao")]
		[Bindable(true)]
		public string NguoiTao 
		{
			get { return GetColumnValue<string>(Columns.NguoiTao); }
			set { SetColumnValue(Columns.NguoiTao, value); }
		}
		  
		[XmlAttribute("NgayTao")]
		[Bindable(true)]
		public DateTime NgayTao 
		{
			get { return GetColumnValue<DateTime>(Columns.NgayTao); }
			set { SetColumnValue(Columns.NgayTao, value); }
		}
		  
		[XmlAttribute("NguoiCapNhat")]
		[Bindable(true)]
		public string NguoiCapNhat 
		{
			get { return GetColumnValue<string>(Columns.NguoiCapNhat); }
			set { SetColumnValue(Columns.NguoiCapNhat, value); }
		}
		  
		[XmlAttribute("NgayCapNhat")]
		[Bindable(true)]
		public DateTime? NgayCapNhat 
		{
			get { return GetColumnValue<DateTime?>(Columns.NgayCapNhat); }
			set { SetColumnValue(Columns.NgayCapNhat, value); }
		}
		
		#endregion
		
		
		#region PrimaryKey Methods		
		
        protected override void SetPrimaryKey(object oValue)
        {
            base.SetPrimaryKey(oValue);
            
            SetPKValues();
        }
        
		
		private SweetSoft.QLDA.DataAccess.TblDuAnCollection colTblDuAnRecords;
		public SweetSoft.QLDA.DataAccess.TblDuAnCollection TblDuAnRecords()
		{
			if(colTblDuAnRecords == null)
			{
				colTblDuAnRecords = new SweetSoft.QLDA.DataAccess.TblDuAnCollection().Where(TblDuAn.Columns.IdKhachHang, IdKhachHang).Load();
				colTblDuAnRecords.ListChanged += new ListChangedEventHandler(colTblDuAnRecords_ListChanged);
			}
			return colTblDuAnRecords;
		}
				
		void colTblDuAnRecords_ListChanged(object sender, ListChangedEventArgs e)
		{
            if (e.ListChangedType == ListChangedType.ItemAdded)
            {
		        // Set foreign key value
		        colTblDuAnRecords[e.NewIndex].IdKhachHang = IdKhachHang;
            }
		}
		private SweetSoft.QLDA.DataAccess.TblGuiNhanKhachHangCollection colTblGuiNhanKhachHangRecords;
		public SweetSoft.QLDA.DataAccess.TblGuiNhanKhachHangCollection TblGuiNhanKhachHangRecords()
		{
			if(colTblGuiNhanKhachHangRecords == null)
			{
				colTblGuiNhanKhachHangRecords = new SweetSoft.QLDA.DataAccess.TblGuiNhanKhachHangCollection().Where(TblGuiNhanKhachHang.Columns.IdKhachHang, IdKhachHang).Load();
				colTblGuiNhanKhachHangRecords.ListChanged += new ListChangedEventHandler(colTblGuiNhanKhachHangRecords_ListChanged);
			}
			return colTblGuiNhanKhachHangRecords;
		}
				
		void colTblGuiNhanKhachHangRecords_ListChanged(object sender, ListChangedEventArgs e)
		{
            if (e.ListChangedType == ListChangedType.ItemAdded)
            {
		        // Set foreign key value
		        colTblGuiNhanKhachHangRecords[e.NewIndex].IdKhachHang = IdKhachHang;
            }
		}
		private SweetSoft.QLDA.DataAccess.TblHopDongThucHienCollection colTblHopDongThucHienRecords;
		public SweetSoft.QLDA.DataAccess.TblHopDongThucHienCollection TblHopDongThucHienRecords()
		{
			if(colTblHopDongThucHienRecords == null)
			{
				colTblHopDongThucHienRecords = new SweetSoft.QLDA.DataAccess.TblHopDongThucHienCollection().Where(TblHopDongThucHien.Columns.IdKhachHang, IdKhachHang).Load();
				colTblHopDongThucHienRecords.ListChanged += new ListChangedEventHandler(colTblHopDongThucHienRecords_ListChanged);
			}
			return colTblHopDongThucHienRecords;
		}
				
		void colTblHopDongThucHienRecords_ListChanged(object sender, ListChangedEventArgs e)
		{
            if (e.ListChangedType == ListChangedType.ItemAdded)
            {
		        // Set foreign key value
		        colTblHopDongThucHienRecords[e.NewIndex].IdKhachHang = IdKhachHang;
            }
		}
		#endregion
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a TblLoaiKhachHang ActiveRecord object related to this TblKhachHang
		/// 
		/// </summary>
		public SweetSoft.QLDA.DataAccess.TblLoaiKhachHang TblLoaiKhachHang
		{
			get { return SweetSoft.QLDA.DataAccess.TblLoaiKhachHang.FetchByID(this.IdLoaiKhachHang); }
			set { SetColumnValue("IdLoaiKhachHang", value.IdLoaiKhachHang); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varIdKhachHang,string varTenKhachHang,Guid varIdLoaiKhachHang,string varIdSoThue,string varSoDienThoai,string varThuDienTu,string varDiaChi,string varTenNguoiDaiDien,string varTenNguoiLienHe,string varDienThoaiLienHe,string varEmail,string varGhiChu,bool varKichHoat,bool varDaXoa,string varNguoiTao,DateTime varNgayTao,string varNguoiCapNhat,DateTime? varNgayCapNhat)
		{
			TblKhachHang item = new TblKhachHang();
			
			item.IdKhachHang = varIdKhachHang;
			
			item.TenKhachHang = varTenKhachHang;
			
			item.IdLoaiKhachHang = varIdLoaiKhachHang;
			
			item.IdSoThue = varIdSoThue;
			
			item.SoDienThoai = varSoDienThoai;
			
			item.ThuDienTu = varThuDienTu;
			
			item.DiaChi = varDiaChi;
			
			item.TenNguoiDaiDien = varTenNguoiDaiDien;
			
			item.TenNguoiLienHe = varTenNguoiLienHe;
			
			item.DienThoaiLienHe = varDienThoaiLienHe;
			
			item.Email = varEmail;
			
			item.GhiChu = varGhiChu;
			
			item.KichHoat = varKichHoat;
			
			item.DaXoa = varDaXoa;
			
			item.NguoiTao = varNguoiTao;
			
			item.NgayTao = varNgayTao;
			
			item.NguoiCapNhat = varNguoiCapNhat;
			
			item.NgayCapNhat = varNgayCapNhat;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varIdKhachHang,string varTenKhachHang,Guid varIdLoaiKhachHang,string varIdSoThue,string varSoDienThoai,string varThuDienTu,string varDiaChi,string varTenNguoiDaiDien,string varTenNguoiLienHe,string varDienThoaiLienHe,string varEmail,string varGhiChu,bool varKichHoat,bool varDaXoa,string varNguoiTao,DateTime varNgayTao,string varNguoiCapNhat,DateTime? varNgayCapNhat)
		{
			TblKhachHang item = new TblKhachHang();
			
				item.IdKhachHang = varIdKhachHang;
			
				item.TenKhachHang = varTenKhachHang;
			
				item.IdLoaiKhachHang = varIdLoaiKhachHang;
			
				item.IdSoThue = varIdSoThue;
			
				item.SoDienThoai = varSoDienThoai;
			
				item.ThuDienTu = varThuDienTu;
			
				item.DiaChi = varDiaChi;
			
				item.TenNguoiDaiDien = varTenNguoiDaiDien;
			
				item.TenNguoiLienHe = varTenNguoiLienHe;
			
				item.DienThoaiLienHe = varDienThoaiLienHe;
			
				item.Email = varEmail;
			
				item.GhiChu = varGhiChu;
			
				item.KichHoat = varKichHoat;
			
				item.DaXoa = varDaXoa;
			
				item.NguoiTao = varNguoiTao;
			
				item.NgayTao = varNgayTao;
			
				item.NguoiCapNhat = varNguoiCapNhat;
			
				item.NgayCapNhat = varNgayCapNhat;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdKhachHangColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn TenKhachHangColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn IdLoaiKhachHangColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn IdSoThueColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn SoDienThoaiColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn ThuDienTuColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn DiaChiColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn TenNguoiDaiDienColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn TenNguoiLienHeColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn DienThoaiLienHeColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn EmailColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        public static TableSchema.TableColumn GhiChuColumn
        {
            get { return Schema.Columns[11]; }
        }
        
        
        
        public static TableSchema.TableColumn KichHoatColumn
        {
            get { return Schema.Columns[12]; }
        }
        
        
        
        public static TableSchema.TableColumn DaXoaColumn
        {
            get { return Schema.Columns[13]; }
        }
        
        
        
        public static TableSchema.TableColumn NguoiTaoColumn
        {
            get { return Schema.Columns[14]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayTaoColumn
        {
            get { return Schema.Columns[15]; }
        }
        
        
        
        public static TableSchema.TableColumn NguoiCapNhatColumn
        {
            get { return Schema.Columns[16]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayCapNhatColumn
        {
            get { return Schema.Columns[17]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string IdKhachHang = @"IdKhachHang";
			 public static string TenKhachHang = @"TenKhachHang";
			 public static string IdLoaiKhachHang = @"IdLoaiKhachHang";
			 public static string IdSoThue = @"IdSoThue";
			 public static string SoDienThoai = @"SoDienThoai";
			 public static string ThuDienTu = @"ThuDienTu";
			 public static string DiaChi = @"DiaChi";
			 public static string TenNguoiDaiDien = @"TenNguoiDaiDien";
			 public static string TenNguoiLienHe = @"TenNguoiLienHe";
			 public static string DienThoaiLienHe = @"DienThoaiLienHe";
			 public static string Email = @"Email";
			 public static string GhiChu = @"GhiChu";
			 public static string KichHoat = @"KichHoat";
			 public static string DaXoa = @"DaXoa";
			 public static string NguoiTao = @"NguoiTao";
			 public static string NgayTao = @"NgayTao";
			 public static string NguoiCapNhat = @"NguoiCapNhat";
			 public static string NgayCapNhat = @"NgayCapNhat";
						
		}
		#endregion
		
		#region Update PK Collections
		
        public void SetPKValues()
        {
                if (colTblDuAnRecords != null)
                {
                    foreach (SweetSoft.QLDA.DataAccess.TblDuAn item in colTblDuAnRecords)
                    {
                        if (item.IdKhachHang == null ||item.IdKhachHang != IdKhachHang)
                        {
                            item.IdKhachHang = IdKhachHang;
                        }
                    }
               }
		
                if (colTblGuiNhanKhachHangRecords != null)
                {
                    foreach (SweetSoft.QLDA.DataAccess.TblGuiNhanKhachHang item in colTblGuiNhanKhachHangRecords)
                    {
                        if (item.IdKhachHang != IdKhachHang)
                        {
                            item.IdKhachHang = IdKhachHang;
                        }
                    }
               }
		
                if (colTblHopDongThucHienRecords != null)
                {
                    foreach (SweetSoft.QLDA.DataAccess.TblHopDongThucHien item in colTblHopDongThucHienRecords)
                    {
                        if (item.IdKhachHang != IdKhachHang)
                        {
                            item.IdKhachHang = IdKhachHang;
                        }
                    }
               }
		}
        #endregion
    
        #region Deep Save
		
        public void DeepSave()
        {
            Save();
            
                if (colTblDuAnRecords != null)
                {
                    colTblDuAnRecords.SaveAll();
               }
		
                if (colTblGuiNhanKhachHangRecords != null)
                {
                    colTblGuiNhanKhachHangRecords.SaveAll();
               }
		
                if (colTblHopDongThucHienRecords != null)
                {
                    colTblHopDongThucHienRecords.SaveAll();
               }
		}
        #endregion
	}
}
