using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    /// <summary>
    /// Controller class for TblKhachHang
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblKhachHangController
    {
        // Preload our schema..
        TblKhachHang thisSchemaLoad = new TblKhachHang();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblKhachHangCollection FetchAll()
        {
            TblKhachHangCollection coll = new TblKhachHangCollection();
            Query qry = new Query(TblKhachHang.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblKhachHangCollection FetchByID(object IdKhachHang)
        {
            TblKhachHangCollection coll = new TblKhachHangCollection().Where("IdKhachHang", IdKhachHang).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblKhachHangCollection FetchByQuery(Query qry)
        {
            TblKhachHangCollection coll = new TblKhachHangCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdKhachHang)
        {
            return (TblKhachHang.Delete(IdKhachHang) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdKhachHang)
        {
            return (TblKhachHang.Destroy(IdKhachHang) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid IdKhachHang,string TenKhachHang,Guid IdLoaiKhachHang,string IdSoThue,string SoDienThoai,string ThuDienTu,string DiaChi,string TenNguoiDaiDien,string TenNguoiLienHe,string DienThoaiLienHe,string ThuDienTuLienHe,string GhiChu,bool KichHoat,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
	    {
		    TblKhachHang item = new TblKhachHang();
		    
            item.IdKhachHang = IdKhachHang;
            
            item.TenKhachHang = TenKhachHang;
            
            item.IdLoaiKhachHang = IdLoaiKhachHang;
            
            item.IdSoThue = IdSoThue;
            
            item.SoDienThoai = SoDienThoai;
            
            item.ThuDienTu = ThuDienTu;
            
            item.DiaChi = DiaChi;
            
            item.TenNguoiDaiDien = TenNguoiDaiDien;
            
            item.TenNguoiLienHe = TenNguoiLienHe;
            
            item.DienThoaiLienHe = DienThoaiLienHe;
            
            item.ThuDienTuLienHe = ThuDienTuLienHe;
            
            item.GhiChu = GhiChu;
            
            item.KichHoat = KichHoat;
            
            item.DaXoa = DaXoa;
            
            item.NguoiTao = NguoiTao;
            
            item.NgayTao = NgayTao;
            
            item.NguoiCapNhat = NguoiCapNhat;
            
            item.NgayCapNhat = NgayCapNhat;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid IdKhachHang,string TenKhachHang,Guid IdLoaiKhachHang,string IdSoThue,string SoDienThoai,string ThuDienTu,string DiaChi,string TenNguoiDaiDien,string TenNguoiLienHe,string DienThoaiLienHe,string ThuDienTuLienHe,string GhiChu,bool KichHoat,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
	    {
		    TblKhachHang item = new TblKhachHang();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.IdKhachHang = IdKhachHang;
				
			item.TenKhachHang = TenKhachHang;
				
			item.IdLoaiKhachHang = IdLoaiKhachHang;
				
			item.IdSoThue = IdSoThue;
				
			item.SoDienThoai = SoDienThoai;
				
			item.ThuDienTu = ThuDienTu;
				
			item.DiaChi = DiaChi;
				
			item.TenNguoiDaiDien = TenNguoiDaiDien;
				
			item.TenNguoiLienHe = TenNguoiLienHe;
				
			item.DienThoaiLienHe = DienThoaiLienHe;
				
			item.ThuDienTuLienHe = ThuDienTuLienHe;
				
			item.GhiChu = GhiChu;
				
			item.KichHoat = KichHoat;
				
			item.DaXoa = DaXoa;
				
			item.NguoiTao = NguoiTao;
				
			item.NgayTao = NgayTao;
				
			item.NguoiCapNhat = NguoiCapNhat;
				
			item.NgayCapNhat = NgayCapNhat;
				
	        item.Save(UserName);
	    }
    }
}
