using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    /// <summary>
    /// Controller class for TblLoaiDuAn
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblLoaiDuAnController
    {
        // Preload our schema..
        TblLoaiDuAn thisSchemaLoad = new TblLoaiDuAn();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblLoaiDuAnCollection FetchAll()
        {
            TblLoaiDuAnCollection coll = new TblLoaiDuAnCollection();
            Query qry = new Query(TblLoaiDuAn.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblLoaiDuAnCollection FetchByID(object IdLoaiDuAn)
        {
            TblLoaiDuAnCollection coll = new TblLoaiDuAnCollection().Where("IdLoaiDuAn", IdLoaiDuAn).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblLoaiDuAnCollection FetchByQuery(Query qry)
        {
            TblLoaiDuAnCollection coll = new TblLoaiDuAnCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdLoaiDuAn)
        {
            return (TblLoaiDuAn.Delete(IdLoaiDuAn) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdLoaiDuAn)
        {
            return (TblLoaiDuAn.Destroy(IdLoaiDuAn) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid IdLoaiDuAn,string TenLoaiDuAn,string MoTa,int ThuTuHienThi,bool KichHoat,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
	    {
		    TblLoaiDuAn item = new TblLoaiDuAn();
		    
            item.IdLoaiDuAn = IdLoaiDuAn;
            
            item.TenLoaiDuAn = TenLoaiDuAn;
            
            item.MoTa = MoTa;
            
            item.ThuTuHienThi = ThuTuHienThi;
            
            item.KichHoat = KichHoat;
            
            item.DaXoa = DaXoa;
            
            item.NguoiTao = NguoiTao;
            
            item.NgayTao = NgayTao;
            
            item.NguoiCapNhat = NguoiCapNhat;
            
            item.NgayCapNhat = NgayCapNhat;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid IdLoaiDuAn,string TenLoaiDuAn,string MoTa,int ThuTuHienThi,bool KichHoat,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
	    {
		    TblLoaiDuAn item = new TblLoaiDuAn();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.IdLoaiDuAn = IdLoaiDuAn;
				
			item.TenLoaiDuAn = TenLoaiDuAn;
				
			item.MoTa = MoTa;
				
			item.ThuTuHienThi = ThuTuHienThi;
				
			item.KichHoat = KichHoat;
				
			item.DaXoa = DaXoa;
				
			item.NguoiTao = NguoiTao;
				
			item.NgayTao = NgayTao;
				
			item.NguoiCapNhat = NguoiCapNhat;
				
			item.NgayCapNhat = NgayCapNhat;
				
	        item.Save(UserName);
	    }
    }
}
