using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblLichHop class.
	/// </summary>
    [Serializable]
	public partial class TblLichHopCollection : ActiveList<TblLichHop, TblLichHopCollection>
	{	   
		public TblLichHopCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblLichHopCollection</returns>
		public TblLichHopCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblLichHop o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblLichHop table.
	/// </summary>
	[Serializable]
	public partial class TblLichHop : ActiveRecord<TblLichHop>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblLichHop()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblLichHop(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblLichHop(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblLichHop(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblLichHop", TableType.Table, DataService.GetInstance("DataAccessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarIdLichHop = new TableSchema.TableColumn(schema);
				colvarIdLichHop.ColumnName = "IdLichHop";
				colvarIdLichHop.DataType = DbType.Guid;
				colvarIdLichHop.MaxLength = 0;
				colvarIdLichHop.AutoIncrement = false;
				colvarIdLichHop.IsNullable = false;
				colvarIdLichHop.IsPrimaryKey = true;
				colvarIdLichHop.IsForeignKey = false;
				colvarIdLichHop.IsReadOnly = false;
				
						colvarIdLichHop.DefaultSetting = @"(newid())";
				colvarIdLichHop.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIdLichHop);
				
				TableSchema.TableColumn colvarIdDuAn = new TableSchema.TableColumn(schema);
				colvarIdDuAn.ColumnName = "IdDuAn";
				colvarIdDuAn.DataType = DbType.Guid;
				colvarIdDuAn.MaxLength = 0;
				colvarIdDuAn.AutoIncrement = false;
				colvarIdDuAn.IsNullable = false;
				colvarIdDuAn.IsPrimaryKey = false;
				colvarIdDuAn.IsForeignKey = true;
				colvarIdDuAn.IsReadOnly = false;
				colvarIdDuAn.DefaultSetting = @"";
				
					colvarIdDuAn.ForeignKeyTableName = "TblDuAn";
				schema.Columns.Add(colvarIdDuAn);
				
				TableSchema.TableColumn colvarIdNhanVienChuTri = new TableSchema.TableColumn(schema);
				colvarIdNhanVienChuTri.ColumnName = "IdNhanVienChuTri";
				colvarIdNhanVienChuTri.DataType = DbType.Guid;
				colvarIdNhanVienChuTri.MaxLength = 0;
				colvarIdNhanVienChuTri.AutoIncrement = false;
				colvarIdNhanVienChuTri.IsNullable = true;
				colvarIdNhanVienChuTri.IsPrimaryKey = false;
				colvarIdNhanVienChuTri.IsForeignKey = true;
				colvarIdNhanVienChuTri.IsReadOnly = false;
				colvarIdNhanVienChuTri.DefaultSetting = @"";
				
					colvarIdNhanVienChuTri.ForeignKeyTableName = "TblNhanVien";
				schema.Columns.Add(colvarIdNhanVienChuTri);
				
				TableSchema.TableColumn colvarMaLichHop = new TableSchema.TableColumn(schema);
				colvarMaLichHop.ColumnName = "MaLichHop";
				colvarMaLichHop.DataType = DbType.AnsiString;
				colvarMaLichHop.MaxLength = 50;
				colvarMaLichHop.AutoIncrement = false;
				colvarMaLichHop.IsNullable = true;
				colvarMaLichHop.IsPrimaryKey = false;
				colvarMaLichHop.IsForeignKey = false;
				colvarMaLichHop.IsReadOnly = false;
				colvarMaLichHop.DefaultSetting = @"";
				colvarMaLichHop.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMaLichHop);
				
				TableSchema.TableColumn colvarTenCuocHop = new TableSchema.TableColumn(schema);
				colvarTenCuocHop.ColumnName = "TenCuocHop";
				colvarTenCuocHop.DataType = DbType.String;
				colvarTenCuocHop.MaxLength = 255;
				colvarTenCuocHop.AutoIncrement = false;
				colvarTenCuocHop.IsNullable = false;
				colvarTenCuocHop.IsPrimaryKey = false;
				colvarTenCuocHop.IsForeignKey = false;
				colvarTenCuocHop.IsReadOnly = false;
				colvarTenCuocHop.DefaultSetting = @"";
				colvarTenCuocHop.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTenCuocHop);
				
				TableSchema.TableColumn colvarNoiDungCuocHop = new TableSchema.TableColumn(schema);
				colvarNoiDungCuocHop.ColumnName = "NoiDungCuocHop";
				colvarNoiDungCuocHop.DataType = DbType.String;
				colvarNoiDungCuocHop.MaxLength = -1;
				colvarNoiDungCuocHop.AutoIncrement = false;
				colvarNoiDungCuocHop.IsNullable = true;
				colvarNoiDungCuocHop.IsPrimaryKey = false;
				colvarNoiDungCuocHop.IsForeignKey = false;
				colvarNoiDungCuocHop.IsReadOnly = false;
				colvarNoiDungCuocHop.DefaultSetting = @"";
				colvarNoiDungCuocHop.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNoiDungCuocHop);
				
				TableSchema.TableColumn colvarThoiGianBatDau = new TableSchema.TableColumn(schema);
				colvarThoiGianBatDau.ColumnName = "ThoiGianBatDau";
				colvarThoiGianBatDau.DataType = DbType.DateTime;
				colvarThoiGianBatDau.MaxLength = 0;
				colvarThoiGianBatDau.AutoIncrement = false;
				colvarThoiGianBatDau.IsNullable = false;
				colvarThoiGianBatDau.IsPrimaryKey = false;
				colvarThoiGianBatDau.IsForeignKey = false;
				colvarThoiGianBatDau.IsReadOnly = false;
				colvarThoiGianBatDau.DefaultSetting = @"";
				colvarThoiGianBatDau.ForeignKeyTableName = "";
				schema.Columns.Add(colvarThoiGianBatDau);
				
				TableSchema.TableColumn colvarThoiGianKetThuc = new TableSchema.TableColumn(schema);
				colvarThoiGianKetThuc.ColumnName = "ThoiGianKetThuc";
				colvarThoiGianKetThuc.DataType = DbType.DateTime;
				colvarThoiGianKetThuc.MaxLength = 0;
				colvarThoiGianKetThuc.AutoIncrement = false;
				colvarThoiGianKetThuc.IsNullable = true;
				colvarThoiGianKetThuc.IsPrimaryKey = false;
				colvarThoiGianKetThuc.IsForeignKey = false;
				colvarThoiGianKetThuc.IsReadOnly = false;
				colvarThoiGianKetThuc.DefaultSetting = @"";
				colvarThoiGianKetThuc.ForeignKeyTableName = "";
				schema.Columns.Add(colvarThoiGianKetThuc);
				
				TableSchema.TableColumn colvarDiaDiemHop = new TableSchema.TableColumn(schema);
				colvarDiaDiemHop.ColumnName = "DiaDiemHop";
				colvarDiaDiemHop.DataType = DbType.String;
				colvarDiaDiemHop.MaxLength = 255;
				colvarDiaDiemHop.AutoIncrement = false;
				colvarDiaDiemHop.IsNullable = true;
				colvarDiaDiemHop.IsPrimaryKey = false;
				colvarDiaDiemHop.IsForeignKey = false;
				colvarDiaDiemHop.IsReadOnly = false;
				colvarDiaDiemHop.DefaultSetting = @"";
				colvarDiaDiemHop.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDiaDiemHop);
				
				TableSchema.TableColumn colvarDuongDanOnline = new TableSchema.TableColumn(schema);
				colvarDuongDanOnline.ColumnName = "DuongDanOnline";
				colvarDuongDanOnline.DataType = DbType.String;
				colvarDuongDanOnline.MaxLength = 500;
				colvarDuongDanOnline.AutoIncrement = false;
				colvarDuongDanOnline.IsNullable = true;
				colvarDuongDanOnline.IsPrimaryKey = false;
				colvarDuongDanOnline.IsForeignKey = false;
				colvarDuongDanOnline.IsReadOnly = false;
				colvarDuongDanOnline.DefaultSetting = @"";
				colvarDuongDanOnline.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDuongDanOnline);
				
				TableSchema.TableColumn colvarTrangThai = new TableSchema.TableColumn(schema);
				colvarTrangThai.ColumnName = "TrangThai";
				colvarTrangThai.DataType = DbType.Byte;
				colvarTrangThai.MaxLength = 0;
				colvarTrangThai.AutoIncrement = false;
				colvarTrangThai.IsNullable = false;
				colvarTrangThai.IsPrimaryKey = false;
				colvarTrangThai.IsForeignKey = false;
				colvarTrangThai.IsReadOnly = false;
				
						colvarTrangThai.DefaultSetting = @"((1))";
				colvarTrangThai.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTrangThai);
				
				TableSchema.TableColumn colvarDaXoa = new TableSchema.TableColumn(schema);
				colvarDaXoa.ColumnName = "DaXoa";
				colvarDaXoa.DataType = DbType.Boolean;
				colvarDaXoa.MaxLength = 0;
				colvarDaXoa.AutoIncrement = false;
				colvarDaXoa.IsNullable = false;
				colvarDaXoa.IsPrimaryKey = false;
				colvarDaXoa.IsForeignKey = false;
				colvarDaXoa.IsReadOnly = false;
				
						colvarDaXoa.DefaultSetting = @"((0))";
				colvarDaXoa.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDaXoa);
				
				TableSchema.TableColumn colvarNguoiTao = new TableSchema.TableColumn(schema);
				colvarNguoiTao.ColumnName = "NguoiTao";
				colvarNguoiTao.DataType = DbType.String;
				colvarNguoiTao.MaxLength = 150;
				colvarNguoiTao.AutoIncrement = false;
				colvarNguoiTao.IsNullable = false;
				colvarNguoiTao.IsPrimaryKey = false;
				colvarNguoiTao.IsForeignKey = false;
				colvarNguoiTao.IsReadOnly = false;
				colvarNguoiTao.DefaultSetting = @"";
				colvarNguoiTao.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNguoiTao);
				
				TableSchema.TableColumn colvarNgayTao = new TableSchema.TableColumn(schema);
				colvarNgayTao.ColumnName = "NgayTao";
				colvarNgayTao.DataType = DbType.DateTime;
				colvarNgayTao.MaxLength = 0;
				colvarNgayTao.AutoIncrement = false;
				colvarNgayTao.IsNullable = false;
				colvarNgayTao.IsPrimaryKey = false;
				colvarNgayTao.IsForeignKey = false;
				colvarNgayTao.IsReadOnly = false;
				
						colvarNgayTao.DefaultSetting = @"(getdate())";
				colvarNgayTao.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayTao);
				
				TableSchema.TableColumn colvarNguoiCapNhat = new TableSchema.TableColumn(schema);
				colvarNguoiCapNhat.ColumnName = "NguoiCapNhat";
				colvarNguoiCapNhat.DataType = DbType.String;
				colvarNguoiCapNhat.MaxLength = 150;
				colvarNguoiCapNhat.AutoIncrement = false;
				colvarNguoiCapNhat.IsNullable = true;
				colvarNguoiCapNhat.IsPrimaryKey = false;
				colvarNguoiCapNhat.IsForeignKey = false;
				colvarNguoiCapNhat.IsReadOnly = false;
				colvarNguoiCapNhat.DefaultSetting = @"";
				colvarNguoiCapNhat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNguoiCapNhat);
				
				TableSchema.TableColumn colvarNgayCapNhat = new TableSchema.TableColumn(schema);
				colvarNgayCapNhat.ColumnName = "NgayCapNhat";
				colvarNgayCapNhat.DataType = DbType.DateTime;
				colvarNgayCapNhat.MaxLength = 0;
				colvarNgayCapNhat.AutoIncrement = false;
				colvarNgayCapNhat.IsNullable = true;
				colvarNgayCapNhat.IsPrimaryKey = false;
				colvarNgayCapNhat.IsForeignKey = false;
				colvarNgayCapNhat.IsReadOnly = false;
				colvarNgayCapNhat.DefaultSetting = @"";
				colvarNgayCapNhat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayCapNhat);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAccessProvider"].AddSchema("TblLichHop",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("IdLichHop")]
		[Bindable(true)]
		public Guid IdLichHop 
		{
			get { return GetColumnValue<Guid>(Columns.IdLichHop); }
			set { SetColumnValue(Columns.IdLichHop, value); }
		}
		  
		[XmlAttribute("IdDuAn")]
		[Bindable(true)]
		public Guid IdDuAn 
		{
			get { return GetColumnValue<Guid>(Columns.IdDuAn); }
			set { SetColumnValue(Columns.IdDuAn, value); }
		}
		  
		[XmlAttribute("IdNhanVienChuTri")]
		[Bindable(true)]
		public Guid? IdNhanVienChuTri 
		{
			get { return GetColumnValue<Guid?>(Columns.IdNhanVienChuTri); }
			set { SetColumnValue(Columns.IdNhanVienChuTri, value); }
		}
		  
		[XmlAttribute("MaLichHop")]
		[Bindable(true)]
		public string MaLichHop 
		{
			get { return GetColumnValue<string>(Columns.MaLichHop); }
			set { SetColumnValue(Columns.MaLichHop, value); }
		}
		  
		[XmlAttribute("TenCuocHop")]
		[Bindable(true)]
		public string TenCuocHop 
		{
			get { return GetColumnValue<string>(Columns.TenCuocHop); }
			set { SetColumnValue(Columns.TenCuocHop, value); }
		}
		  
		[XmlAttribute("NoiDungCuocHop")]
		[Bindable(true)]
		public string NoiDungCuocHop 
		{
			get { return GetColumnValue<string>(Columns.NoiDungCuocHop); }
			set { SetColumnValue(Columns.NoiDungCuocHop, value); }
		}
		  
		[XmlAttribute("ThoiGianBatDau")]
		[Bindable(true)]
		public DateTime ThoiGianBatDau 
		{
			get { return GetColumnValue<DateTime>(Columns.ThoiGianBatDau); }
			set { SetColumnValue(Columns.ThoiGianBatDau, value); }
		}
		  
		[XmlAttribute("ThoiGianKetThuc")]
		[Bindable(true)]
		public DateTime? ThoiGianKetThuc 
		{
			get { return GetColumnValue<DateTime?>(Columns.ThoiGianKetThuc); }
			set { SetColumnValue(Columns.ThoiGianKetThuc, value); }
		}
		  
		[XmlAttribute("DiaDiemHop")]
		[Bindable(true)]
		public string DiaDiemHop 
		{
			get { return GetColumnValue<string>(Columns.DiaDiemHop); }
			set { SetColumnValue(Columns.DiaDiemHop, value); }
		}
		  
		[XmlAttribute("DuongDanOnline")]
		[Bindable(true)]
		public string DuongDanOnline 
		{
			get { return GetColumnValue<string>(Columns.DuongDanOnline); }
			set { SetColumnValue(Columns.DuongDanOnline, value); }
		}
		  
		[XmlAttribute("TrangThai")]
		[Bindable(true)]
		public byte TrangThai 
		{
			get { return GetColumnValue<byte>(Columns.TrangThai); }
			set { SetColumnValue(Columns.TrangThai, value); }
		}
		  
		[XmlAttribute("DaXoa")]
		[Bindable(true)]
		public bool DaXoa 
		{
			get { return GetColumnValue<bool>(Columns.DaXoa); }
			set { SetColumnValue(Columns.DaXoa, value); }
		}
		  
		[XmlAttribute("NguoiTao")]
		[Bindable(true)]
		public string NguoiTao 
		{
			get { return GetColumnValue<string>(Columns.NguoiTao); }
			set { SetColumnValue(Columns.NguoiTao, value); }
		}
		  
		[XmlAttribute("NgayTao")]
		[Bindable(true)]
		public DateTime NgayTao 
		{
			get { return GetColumnValue<DateTime>(Columns.NgayTao); }
			set { SetColumnValue(Columns.NgayTao, value); }
		}
		  
		[XmlAttribute("NguoiCapNhat")]
		[Bindable(true)]
		public string NguoiCapNhat 
		{
			get { return GetColumnValue<string>(Columns.NguoiCapNhat); }
			set { SetColumnValue(Columns.NguoiCapNhat, value); }
		}
		  
		[XmlAttribute("NgayCapNhat")]
		[Bindable(true)]
		public DateTime? NgayCapNhat 
		{
			get { return GetColumnValue<DateTime?>(Columns.NgayCapNhat); }
			set { SetColumnValue(Columns.NgayCapNhat, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a TblDuAn ActiveRecord object related to this TblLichHop
		/// 
		/// </summary>
		public SweetSoft.QLDA.DataAccess.TblDuAn TblDuAn
		{
			get { return SweetSoft.QLDA.DataAccess.TblDuAn.FetchByID(this.IdDuAn); }
			set { SetColumnValue("IdDuAn", value.IdDuAn); }
		}
		
		
		/// <summary>
		/// Returns a TblNhanVien ActiveRecord object related to this TblLichHop
		/// 
		/// </summary>
		public SweetSoft.QLDA.DataAccess.TblNhanVien TblNhanVien
		{
			get { return SweetSoft.QLDA.DataAccess.TblNhanVien.FetchByID(this.IdNhanVienChuTri); }
			set { SetColumnValue("IdNhanVienChuTri", value.IdNhanVien); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varIdLichHop,Guid varIdDuAn,Guid? varIdNhanVienChuTri,string varMaLichHop,string varTenCuocHop,string varNoiDungCuocHop,DateTime varThoiGianBatDau,DateTime? varThoiGianKetThuc,string varDiaDiemHop,string varDuongDanOnline,byte varTrangThai,bool varDaXoa,string varNguoiTao,DateTime varNgayTao,string varNguoiCapNhat,DateTime? varNgayCapNhat)
		{
			TblLichHop item = new TblLichHop();
			
			item.IdLichHop = varIdLichHop;
			
			item.IdDuAn = varIdDuAn;
			
			item.IdNhanVienChuTri = varIdNhanVienChuTri;
			
			item.MaLichHop = varMaLichHop;
			
			item.TenCuocHop = varTenCuocHop;
			
			item.NoiDungCuocHop = varNoiDungCuocHop;
			
			item.ThoiGianBatDau = varThoiGianBatDau;
			
			item.ThoiGianKetThuc = varThoiGianKetThuc;
			
			item.DiaDiemHop = varDiaDiemHop;
			
			item.DuongDanOnline = varDuongDanOnline;
			
			item.TrangThai = varTrangThai;
			
			item.DaXoa = varDaXoa;
			
			item.NguoiTao = varNguoiTao;
			
			item.NgayTao = varNgayTao;
			
			item.NguoiCapNhat = varNguoiCapNhat;
			
			item.NgayCapNhat = varNgayCapNhat;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varIdLichHop,Guid varIdDuAn,Guid? varIdNhanVienChuTri,string varMaLichHop,string varTenCuocHop,string varNoiDungCuocHop,DateTime varThoiGianBatDau,DateTime? varThoiGianKetThuc,string varDiaDiemHop,string varDuongDanOnline,byte varTrangThai,bool varDaXoa,string varNguoiTao,DateTime varNgayTao,string varNguoiCapNhat,DateTime? varNgayCapNhat)
		{
			TblLichHop item = new TblLichHop();
			
				item.IdLichHop = varIdLichHop;
			
				item.IdDuAn = varIdDuAn;
			
				item.IdNhanVienChuTri = varIdNhanVienChuTri;
			
				item.MaLichHop = varMaLichHop;
			
				item.TenCuocHop = varTenCuocHop;
			
				item.NoiDungCuocHop = varNoiDungCuocHop;
			
				item.ThoiGianBatDau = varThoiGianBatDau;
			
				item.ThoiGianKetThuc = varThoiGianKetThuc;
			
				item.DiaDiemHop = varDiaDiemHop;
			
				item.DuongDanOnline = varDuongDanOnline;
			
				item.TrangThai = varTrangThai;
			
				item.DaXoa = varDaXoa;
			
				item.NguoiTao = varNguoiTao;
			
				item.NgayTao = varNgayTao;
			
				item.NguoiCapNhat = varNguoiCapNhat;
			
				item.NgayCapNhat = varNgayCapNhat;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdLichHopColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn IdDuAnColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn IdNhanVienChuTriColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn MaLichHopColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn TenCuocHopColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn NoiDungCuocHopColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn ThoiGianBatDauColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn ThoiGianKetThucColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn DiaDiemHopColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn DuongDanOnlineColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn TrangThaiColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        public static TableSchema.TableColumn DaXoaColumn
        {
            get { return Schema.Columns[11]; }
        }
        
        
        
        public static TableSchema.TableColumn NguoiTaoColumn
        {
            get { return Schema.Columns[12]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayTaoColumn
        {
            get { return Schema.Columns[13]; }
        }
        
        
        
        public static TableSchema.TableColumn NguoiCapNhatColumn
        {
            get { return Schema.Columns[14]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayCapNhatColumn
        {
            get { return Schema.Columns[15]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string IdLichHop = @"IdLichHop";
			 public static string IdDuAn = @"IdDuAn";
			 public static string IdNhanVienChuTri = @"IdNhanVienChuTri";
			 public static string MaLichHop = @"MaLichHop";
			 public static string TenCuocHop = @"TenCuocHop";
			 public static string NoiDungCuocHop = @"NoiDungCuocHop";
			 public static string ThoiGianBatDau = @"ThoiGianBatDau";
			 public static string ThoiGianKetThuc = @"ThoiGianKetThuc";
			 public static string DiaDiemHop = @"DiaDiemHop";
			 public static string DuongDanOnline = @"DuongDanOnline";
			 public static string TrangThai = @"TrangThai";
			 public static string DaXoa = @"DaXoa";
			 public static string NguoiTao = @"NguoiTao";
			 public static string NgayTao = @"NgayTao";
			 public static string NguoiCapNhat = @"NguoiCapNhat";
			 public static string NgayCapNhat = @"NgayCapNhat";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
