using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    /// <summary>
    /// Controller class for TblLichHop_NhanVien
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblLichHopNhanVienController
    {
        // Preload our schema..
        TblLichHopNhanVien thisSchemaLoad = new TblLichHopNhanVien();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblLichHopNhanVienCollection FetchAll()
        {
            TblLichHopNhanVienCollection coll = new TblLichHopNhanVienCollection();
            Query qry = new Query(TblLichHopNhanVien.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblLichHopNhanVienCollection FetchByID(object IdLichHop)
        {
            TblLichHopNhanVienCollection coll = new TblLichHopNhanVienCollection().Where("IdLichHop", IdLichHop).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblLichHopNhanVienCollection FetchByQuery(Query qry)
        {
            TblLichHopNhanVienCollection coll = new TblLichHopNhanVienCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdLichHop)
        {
            return (TblLichHopNhanVien.Delete(IdLichHop) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdLichHop)
        {
            return (TblLichHopNhanVien.Destroy(IdLichHop) == 1);
        }
        
        
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(Guid IdLichHop,Guid IdNhanVien)
        {
            Query qry = new Query(TblLichHopNhanVien.Schema);
            qry.QueryType = QueryType.Delete;
            qry.AddWhere("IdLichHop", IdLichHop).AND("IdNhanVien", IdNhanVien);
            qry.Execute();
            return (true);
        }        
       
    	
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid IdLichHop,Guid IdNhanVien)
	    {
		    TblLichHopNhanVien item = new TblLichHopNhanVien();
		    
            item.IdLichHop = IdLichHop;
            
            item.IdNhanVien = IdNhanVien;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid IdLichHop,Guid IdNhanVien)
	    {
		    TblLichHopNhanVien item = new TblLichHopNhanVien();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.IdLichHop = IdLichHop;
				
			item.IdNhanVien = IdNhanVien;
				
	        item.Save(UserName);
	    }
    }
}
