using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    /// <summary>
    /// Controller class for TblNoiLuuTru
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblNoiLuuTruController
    {
        // Preload our schema..
        TblNoiLuuTru thisSchemaLoad = new TblNoiLuuTru();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblNoiLuuTruCollection FetchAll()
        {
            TblNoiLuuTruCollection coll = new TblNoiLuuTruCollection();
            Query qry = new Query(TblNoiLuuTru.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblNoiLuuTruCollection FetchByID(object IdNoiLuuTru)
        {
            TblNoiLuuTruCollection coll = new TblNoiLuuTruCollection().Where("IdNoiLuuTru", IdNoiLuuTru).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblNoiLuuTruCollection FetchByQuery(Query qry)
        {
            TblNoiLuuTruCollection coll = new TblNoiLuuTruCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdNoiLuuTru)
        {
            return (TblNoiLuuTru.Delete(IdNoiLuuTru) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdNoiLuuTru)
        {
            return (TblNoiLuuTru.Destroy(IdNoiLuuTru) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid IdNoiLuuTru,Guid? IdNoiLuuTruCha,string MaNoiLuuTru,string TenNoiLuuTru,string CapLuuTru,Guid? IdNhanVienPhuTrach,string MoTa,int ThuTuHienThi,bool KichHoat,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
	    {
		    TblNoiLuuTru item = new TblNoiLuuTru();
		    
            item.IdNoiLuuTru = IdNoiLuuTru;
            
            item.IdNoiLuuTruCha = IdNoiLuuTruCha;
            
            item.MaNoiLuuTru = MaNoiLuuTru;
            
            item.TenNoiLuuTru = TenNoiLuuTru;
            
            item.CapLuuTru = CapLuuTru;
            
            item.IdNhanVienPhuTrach = IdNhanVienPhuTrach;
            
            item.MoTa = MoTa;
            
            item.ThuTuHienThi = ThuTuHienThi;
            
            item.KichHoat = KichHoat;
            
            item.DaXoa = DaXoa;
            
            item.NguoiTao = NguoiTao;
            
            item.NgayTao = NgayTao;
            
            item.NguoiCapNhat = NguoiCapNhat;
            
            item.NgayCapNhat = NgayCapNhat;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid IdNoiLuuTru,Guid? IdNoiLuuTruCha,string MaNoiLuuTru,string TenNoiLuuTru,string CapLuuTru,Guid? IdNhanVienPhuTrach,string MoTa,int ThuTuHienThi,bool KichHoat,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
	    {
		    TblNoiLuuTru item = new TblNoiLuuTru();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.IdNoiLuuTru = IdNoiLuuTru;
				
			item.IdNoiLuuTruCha = IdNoiLuuTruCha;
				
			item.MaNoiLuuTru = MaNoiLuuTru;
				
			item.TenNoiLuuTru = TenNoiLuuTru;
				
			item.CapLuuTru = CapLuuTru;
				
			item.IdNhanVienPhuTrach = IdNhanVienPhuTrach;
				
			item.MoTa = MoTa;
				
			item.ThuTuHienThi = ThuTuHienThi;
				
			item.KichHoat = KichHoat;
				
			item.DaXoa = DaXoa;
				
			item.NguoiTao = NguoiTao;
				
			item.NgayTao = NgayTao;
				
			item.NguoiCapNhat = NguoiCapNhat;
				
			item.NgayCapNhat = NgayCapNhat;
				
	        item.Save(UserName);
	    }
    }
}
