using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblRuiRo class.
	/// </summary>
    [Serializable]
	public partial class TblRuiRoCollection : ActiveList<TblRuiRo, TblRuiRoCollection>
	{	   
		public TblRuiRoCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblRuiRoCollection</returns>
		public TblRuiRoCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblRuiRo o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblRuiRo table.
	/// </summary>
	[Serializable]
	public partial class TblRuiRo : ActiveRecord<TblRuiRo>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblRuiRo()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblRuiRo(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblRuiRo(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblRuiRo(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblRuiRo", TableType.Table, DataService.GetInstance("DataAccessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarIdRuiRo = new TableSchema.TableColumn(schema);
				colvarIdRuiRo.ColumnName = "IdRuiRo";
				colvarIdRuiRo.DataType = DbType.Guid;
				colvarIdRuiRo.MaxLength = 0;
				colvarIdRuiRo.AutoIncrement = false;
				colvarIdRuiRo.IsNullable = false;
				colvarIdRuiRo.IsPrimaryKey = true;
				colvarIdRuiRo.IsForeignKey = false;
				colvarIdRuiRo.IsReadOnly = false;
				colvarIdRuiRo.DefaultSetting = @"";
				colvarIdRuiRo.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIdRuiRo);
				
				TableSchema.TableColumn colvarTenRuiRo = new TableSchema.TableColumn(schema);
				colvarTenRuiRo.ColumnName = "TenRuiRo";
				colvarTenRuiRo.DataType = DbType.String;
				colvarTenRuiRo.MaxLength = 255;
				colvarTenRuiRo.AutoIncrement = false;
				colvarTenRuiRo.IsNullable = false;
				colvarTenRuiRo.IsPrimaryKey = false;
				colvarTenRuiRo.IsForeignKey = false;
				colvarTenRuiRo.IsReadOnly = false;
				colvarTenRuiRo.DefaultSetting = @"";
				colvarTenRuiRo.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTenRuiRo);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAccessProvider"].AddSchema("TblRuiRo",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("IdRuiRo")]
		[Bindable(true)]
		public Guid IdRuiRo 
		{
			get { return GetColumnValue<Guid>(Columns.IdRuiRo); }
			set { SetColumnValue(Columns.IdRuiRo, value); }
		}
		  
		[XmlAttribute("TenRuiRo")]
		[Bindable(true)]
		public string TenRuiRo 
		{
			get { return GetColumnValue<string>(Columns.TenRuiRo); }
			set { SetColumnValue(Columns.TenRuiRo, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varIdRuiRo,string varTenRuiRo)
		{
			TblRuiRo item = new TblRuiRo();
			
			item.IdRuiRo = varIdRuiRo;
			
			item.TenRuiRo = varTenRuiRo;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varIdRuiRo,string varTenRuiRo)
		{
			TblRuiRo item = new TblRuiRo();
			
				item.IdRuiRo = varIdRuiRo;
			
				item.TenRuiRo = varTenRuiRo;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdRuiRoColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn TenRuiRoColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string IdRuiRo = @"IdRuiRo";
			 public static string TenRuiRo = @"TenRuiRo";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
