using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblThanhVienDuAn class.
	/// </summary>
    [Serializable]
	public partial class TblThanhVienDuAnCollection : ActiveList<TblThanhVienDuAn, TblThanhVienDuAnCollection>
	{	   
		public TblThanhVienDuAnCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblThanhVienDuAnCollection</returns>
		public TblThanhVienDuAnCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblThanhVienDuAn o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblThanhVienDuAn table.
	/// </summary>
	[Serializable]
	public partial class TblThanhVienDuAn : ActiveRecord<TblThanhVienDuAn>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblThanhVienDuAn()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblThanhVienDuAn(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblThanhVienDuAn(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblThanhVienDuAn(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblThanhVienDuAn", TableType.Table, DataService.GetInstance("DataAccessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarIdThanhVienDuAn = new TableSchema.TableColumn(schema);
				colvarIdThanhVienDuAn.ColumnName = "IdThanhVienDuAn";
				colvarIdThanhVienDuAn.DataType = DbType.Guid;
				colvarIdThanhVienDuAn.MaxLength = 0;
				colvarIdThanhVienDuAn.AutoIncrement = false;
				colvarIdThanhVienDuAn.IsNullable = false;
				colvarIdThanhVienDuAn.IsPrimaryKey = true;
				colvarIdThanhVienDuAn.IsForeignKey = false;
				colvarIdThanhVienDuAn.IsReadOnly = false;
				
						colvarIdThanhVienDuAn.DefaultSetting = @"(newid())";
				colvarIdThanhVienDuAn.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIdThanhVienDuAn);
				
				TableSchema.TableColumn colvarIdDuAn = new TableSchema.TableColumn(schema);
				colvarIdDuAn.ColumnName = "IdDuAn";
				colvarIdDuAn.DataType = DbType.Guid;
				colvarIdDuAn.MaxLength = 0;
				colvarIdDuAn.AutoIncrement = false;
				colvarIdDuAn.IsNullable = false;
				colvarIdDuAn.IsPrimaryKey = false;
				colvarIdDuAn.IsForeignKey = true;
				colvarIdDuAn.IsReadOnly = false;
				colvarIdDuAn.DefaultSetting = @"";
				
					colvarIdDuAn.ForeignKeyTableName = "TblDuAn";
				schema.Columns.Add(colvarIdDuAn);
				
				TableSchema.TableColumn colvarIdNhanVien = new TableSchema.TableColumn(schema);
				colvarIdNhanVien.ColumnName = "IdNhanVien";
				colvarIdNhanVien.DataType = DbType.Guid;
				colvarIdNhanVien.MaxLength = 0;
				colvarIdNhanVien.AutoIncrement = false;
				colvarIdNhanVien.IsNullable = true;
				colvarIdNhanVien.IsPrimaryKey = false;
				colvarIdNhanVien.IsForeignKey = true;
				colvarIdNhanVien.IsReadOnly = false;
				colvarIdNhanVien.DefaultSetting = @"";
				
					colvarIdNhanVien.ForeignKeyTableName = "aspnet_Users";
				schema.Columns.Add(colvarIdNhanVien);
				
				TableSchema.TableColumn colvarIdVaiTroDuAn = new TableSchema.TableColumn(schema);
				colvarIdVaiTroDuAn.ColumnName = "IdVaiTroDuAn";
				colvarIdVaiTroDuAn.DataType = DbType.Guid;
				colvarIdVaiTroDuAn.MaxLength = 0;
				colvarIdVaiTroDuAn.AutoIncrement = false;
				colvarIdVaiTroDuAn.IsNullable = true;
				colvarIdVaiTroDuAn.IsPrimaryKey = false;
				colvarIdVaiTroDuAn.IsForeignKey = true;
				colvarIdVaiTroDuAn.IsReadOnly = false;
				colvarIdVaiTroDuAn.DefaultSetting = @"";
				
					colvarIdVaiTroDuAn.ForeignKeyTableName = "TblVaiTroDuAn";
				schema.Columns.Add(colvarIdVaiTroDuAn);
				
				TableSchema.TableColumn colvarNgayThamGia = new TableSchema.TableColumn(schema);
				colvarNgayThamGia.ColumnName = "NgayThamGia";
				colvarNgayThamGia.DataType = DbType.DateTime;
				colvarNgayThamGia.MaxLength = 0;
				colvarNgayThamGia.AutoIncrement = false;
				colvarNgayThamGia.IsNullable = false;
				colvarNgayThamGia.IsPrimaryKey = false;
				colvarNgayThamGia.IsForeignKey = false;
				colvarNgayThamGia.IsReadOnly = false;
				
						colvarNgayThamGia.DefaultSetting = @"(getdate())";
				colvarNgayThamGia.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayThamGia);
				
				TableSchema.TableColumn colvarGhiChu = new TableSchema.TableColumn(schema);
				colvarGhiChu.ColumnName = "GhiChu";
				colvarGhiChu.DataType = DbType.String;
				colvarGhiChu.MaxLength = 1000;
				colvarGhiChu.AutoIncrement = false;
				colvarGhiChu.IsNullable = true;
				colvarGhiChu.IsPrimaryKey = false;
				colvarGhiChu.IsForeignKey = false;
				colvarGhiChu.IsReadOnly = false;
				colvarGhiChu.DefaultSetting = @"";
				colvarGhiChu.ForeignKeyTableName = "";
				schema.Columns.Add(colvarGhiChu);
				
				TableSchema.TableColumn colvarDaXoa = new TableSchema.TableColumn(schema);
				colvarDaXoa.ColumnName = "DaXoa";
				colvarDaXoa.DataType = DbType.Boolean;
				colvarDaXoa.MaxLength = 0;
				colvarDaXoa.AutoIncrement = false;
				colvarDaXoa.IsNullable = false;
				colvarDaXoa.IsPrimaryKey = false;
				colvarDaXoa.IsForeignKey = false;
				colvarDaXoa.IsReadOnly = false;
				
						colvarDaXoa.DefaultSetting = @"((0))";
				colvarDaXoa.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDaXoa);
				
				TableSchema.TableColumn colvarNguoiTao = new TableSchema.TableColumn(schema);
				colvarNguoiTao.ColumnName = "NguoiTao";
				colvarNguoiTao.DataType = DbType.String;
				colvarNguoiTao.MaxLength = 150;
				colvarNguoiTao.AutoIncrement = false;
				colvarNguoiTao.IsNullable = false;
				colvarNguoiTao.IsPrimaryKey = false;
				colvarNguoiTao.IsForeignKey = false;
				colvarNguoiTao.IsReadOnly = false;
				colvarNguoiTao.DefaultSetting = @"";
				colvarNguoiTao.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNguoiTao);
				
				TableSchema.TableColumn colvarNgayTao = new TableSchema.TableColumn(schema);
				colvarNgayTao.ColumnName = "NgayTao";
				colvarNgayTao.DataType = DbType.DateTime;
				colvarNgayTao.MaxLength = 0;
				colvarNgayTao.AutoIncrement = false;
				colvarNgayTao.IsNullable = false;
				colvarNgayTao.IsPrimaryKey = false;
				colvarNgayTao.IsForeignKey = false;
				colvarNgayTao.IsReadOnly = false;
				
						colvarNgayTao.DefaultSetting = @"(getdate())";
				colvarNgayTao.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayTao);
				
				TableSchema.TableColumn colvarNguoiCapNhat = new TableSchema.TableColumn(schema);
				colvarNguoiCapNhat.ColumnName = "NguoiCapNhat";
				colvarNguoiCapNhat.DataType = DbType.String;
				colvarNguoiCapNhat.MaxLength = 150;
				colvarNguoiCapNhat.AutoIncrement = false;
				colvarNguoiCapNhat.IsNullable = true;
				colvarNguoiCapNhat.IsPrimaryKey = false;
				colvarNguoiCapNhat.IsForeignKey = false;
				colvarNguoiCapNhat.IsReadOnly = false;
				colvarNguoiCapNhat.DefaultSetting = @"";
				colvarNguoiCapNhat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNguoiCapNhat);
				
				TableSchema.TableColumn colvarNgayCapNhat = new TableSchema.TableColumn(schema);
				colvarNgayCapNhat.ColumnName = "NgayCapNhat";
				colvarNgayCapNhat.DataType = DbType.DateTime;
				colvarNgayCapNhat.MaxLength = 0;
				colvarNgayCapNhat.AutoIncrement = false;
				colvarNgayCapNhat.IsNullable = true;
				colvarNgayCapNhat.IsPrimaryKey = false;
				colvarNgayCapNhat.IsForeignKey = false;
				colvarNgayCapNhat.IsReadOnly = false;
				colvarNgayCapNhat.DefaultSetting = @"";
				colvarNgayCapNhat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayCapNhat);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAccessProvider"].AddSchema("TblThanhVienDuAn",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("IdThanhVienDuAn")]
		[Bindable(true)]
		public Guid IdThanhVienDuAn 
		{
			get { return GetColumnValue<Guid>(Columns.IdThanhVienDuAn); }
			set { SetColumnValue(Columns.IdThanhVienDuAn, value); }
		}
		  
		[XmlAttribute("IdDuAn")]
		[Bindable(true)]
		public Guid IdDuAn 
		{
			get { return GetColumnValue<Guid>(Columns.IdDuAn); }
			set { SetColumnValue(Columns.IdDuAn, value); }
		}
		  
		[XmlAttribute("IdNhanVien")]
		[Bindable(true)]
		public Guid? IdNhanVien 
		{
			get { return GetColumnValue<Guid?>(Columns.IdNhanVien); }
			set { SetColumnValue(Columns.IdNhanVien, value); }
		}
		  
		[XmlAttribute("IdVaiTroDuAn")]
		[Bindable(true)]
		public Guid? IdVaiTroDuAn 
		{
			get { return GetColumnValue<Guid?>(Columns.IdVaiTroDuAn); }
			set { SetColumnValue(Columns.IdVaiTroDuAn, value); }
		}
		  
		[XmlAttribute("NgayThamGia")]
		[Bindable(true)]
		public DateTime NgayThamGia 
		{
			get { return GetColumnValue<DateTime>(Columns.NgayThamGia); }
			set { SetColumnValue(Columns.NgayThamGia, value); }
		}
		  
		[XmlAttribute("GhiChu")]
		[Bindable(true)]
		public string GhiChu 
		{
			get { return GetColumnValue<string>(Columns.GhiChu); }
			set { SetColumnValue(Columns.GhiChu, value); }
		}
		  
		[XmlAttribute("DaXoa")]
		[Bindable(true)]
		public bool DaXoa 
		{
			get { return GetColumnValue<bool>(Columns.DaXoa); }
			set { SetColumnValue(Columns.DaXoa, value); }
		}
		  
		[XmlAttribute("NguoiTao")]
		[Bindable(true)]
		public string NguoiTao 
		{
			get { return GetColumnValue<string>(Columns.NguoiTao); }
			set { SetColumnValue(Columns.NguoiTao, value); }
		}
		  
		[XmlAttribute("NgayTao")]
		[Bindable(true)]
		public DateTime NgayTao 
		{
			get { return GetColumnValue<DateTime>(Columns.NgayTao); }
			set { SetColumnValue(Columns.NgayTao, value); }
		}
		  
		[XmlAttribute("NguoiCapNhat")]
		[Bindable(true)]
		public string NguoiCapNhat 
		{
			get { return GetColumnValue<string>(Columns.NguoiCapNhat); }
			set { SetColumnValue(Columns.NguoiCapNhat, value); }
		}
		  
		[XmlAttribute("NgayCapNhat")]
		[Bindable(true)]
		public DateTime? NgayCapNhat 
		{
			get { return GetColumnValue<DateTime?>(Columns.NgayCapNhat); }
			set { SetColumnValue(Columns.NgayCapNhat, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a AspnetUser ActiveRecord object related to this TblThanhVienDuAn
		/// 
		/// </summary>
		public SweetSoft.QLDA.DataAccess.AspnetUser AspnetUser
		{
			get { return SweetSoft.QLDA.DataAccess.AspnetUser.FetchByID(this.IdNhanVien); }
			set { SetColumnValue("IdNhanVien", value.UserId); }
		}
		
		
		/// <summary>
		/// Returns a TblDuAn ActiveRecord object related to this TblThanhVienDuAn
		/// 
		/// </summary>
		public SweetSoft.QLDA.DataAccess.TblDuAn TblDuAn
		{
			get { return SweetSoft.QLDA.DataAccess.TblDuAn.FetchByID(this.IdDuAn); }
			set { SetColumnValue("IdDuAn", value.IdDuAn); }
		}
		
		
		/// <summary>
		/// Returns a TblVaiTroDuAn ActiveRecord object related to this TblThanhVienDuAn
		/// 
		/// </summary>
		public SweetSoft.QLDA.DataAccess.TblVaiTroDuAn TblVaiTroDuAn
		{
			get { return SweetSoft.QLDA.DataAccess.TblVaiTroDuAn.FetchByID(this.IdVaiTroDuAn); }
			set { SetColumnValue("IdVaiTroDuAn", value.IdVaiTroDuAn); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varIdThanhVienDuAn,Guid varIdDuAn,Guid? varIdNhanVien,Guid? varIdVaiTroDuAn,DateTime varNgayThamGia,string varGhiChu,bool varDaXoa,string varNguoiTao,DateTime varNgayTao,string varNguoiCapNhat,DateTime? varNgayCapNhat)
		{
			TblThanhVienDuAn item = new TblThanhVienDuAn();
			
			item.IdThanhVienDuAn = varIdThanhVienDuAn;
			
			item.IdDuAn = varIdDuAn;
			
			item.IdNhanVien = varIdNhanVien;
			
			item.IdVaiTroDuAn = varIdVaiTroDuAn;
			
			item.NgayThamGia = varNgayThamGia;
			
			item.GhiChu = varGhiChu;
			
			item.DaXoa = varDaXoa;
			
			item.NguoiTao = varNguoiTao;
			
			item.NgayTao = varNgayTao;
			
			item.NguoiCapNhat = varNguoiCapNhat;
			
			item.NgayCapNhat = varNgayCapNhat;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varIdThanhVienDuAn,Guid varIdDuAn,Guid? varIdNhanVien,Guid? varIdVaiTroDuAn,DateTime varNgayThamGia,string varGhiChu,bool varDaXoa,string varNguoiTao,DateTime varNgayTao,string varNguoiCapNhat,DateTime? varNgayCapNhat)
		{
			TblThanhVienDuAn item = new TblThanhVienDuAn();
			
				item.IdThanhVienDuAn = varIdThanhVienDuAn;
			
				item.IdDuAn = varIdDuAn;
			
				item.IdNhanVien = varIdNhanVien;
			
				item.IdVaiTroDuAn = varIdVaiTroDuAn;
			
				item.NgayThamGia = varNgayThamGia;
			
				item.GhiChu = varGhiChu;
			
				item.DaXoa = varDaXoa;
			
				item.NguoiTao = varNguoiTao;
			
				item.NgayTao = varNgayTao;
			
				item.NguoiCapNhat = varNguoiCapNhat;
			
				item.NgayCapNhat = varNgayCapNhat;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdThanhVienDuAnColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn IdDuAnColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn IdNhanVienColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn IdVaiTroDuAnColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayThamGiaColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn GhiChuColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn DaXoaColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn NguoiTaoColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayTaoColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn NguoiCapNhatColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayCapNhatColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string IdThanhVienDuAn = @"IdThanhVienDuAn";
			 public static string IdDuAn = @"IdDuAn";
			 public static string IdNhanVien = @"IdNhanVien";
			 public static string IdVaiTroDuAn = @"IdVaiTroDuAn";
			 public static string NgayThamGia = @"NgayThamGia";
			 public static string GhiChu = @"GhiChu";
			 public static string DaXoa = @"DaXoa";
			 public static string NguoiTao = @"NguoiTao";
			 public static string NgayTao = @"NgayTao";
			 public static string NguoiCapNhat = @"NguoiCapNhat";
			 public static string NgayCapNhat = @"NgayCapNhat";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
