using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    /// <summary>
    /// Controller class for TblThanhToan
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblThanhToanController
    {
        // Preload our schema..
        TblThanhToan thisSchemaLoad = new TblThanhToan();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblThanhToanCollection FetchAll()
        {
            TblThanhToanCollection coll = new TblThanhToanCollection();
            Query qry = new Query(TblThanhToan.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblThanhToanCollection FetchByID(object IdThanhToan)
        {
            TblThanhToanCollection coll = new TblThanhToanCollection().Where("IdThanhToan", IdThanhToan).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblThanhToanCollection FetchByQuery(Query qry)
        {
            TblThanhToanCollection coll = new TblThanhToanCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdThanhToan)
        {
            return (TblThanhToan.Delete(IdThanhToan) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdThanhToan)
        {
            return (TblThanhToan.Destroy(IdThanhToan) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid IdThanhToan,Guid IdDuAn,string MaDotThanhToan,string TenDotThanhToan,decimal SoTien,DateTime? HanThanhToan,DateTime? NgayThanhToanThucTe,byte TrangThai,string GhiChu,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
	    {
		    TblThanhToan item = new TblThanhToan();
		    
            item.IdThanhToan = IdThanhToan;
            
            item.IdDuAn = IdDuAn;
            
            item.MaDotThanhToan = MaDotThanhToan;
            
            item.TenDotThanhToan = TenDotThanhToan;
            
            item.SoTien = SoTien;
            
            item.HanThanhToan = HanThanhToan;
            
            item.NgayThanhToanThucTe = NgayThanhToanThucTe;
            
            item.TrangThai = TrangThai;
            
            item.GhiChu = GhiChu;
            
            item.DaXoa = DaXoa;
            
            item.NguoiTao = NguoiTao;
            
            item.NgayTao = NgayTao;
            
            item.NguoiCapNhat = NguoiCapNhat;
            
            item.NgayCapNhat = NgayCapNhat;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid IdThanhToan,Guid IdDuAn,string MaDotThanhToan,string TenDotThanhToan,decimal SoTien,DateTime? HanThanhToan,DateTime? NgayThanhToanThucTe,byte TrangThai,string GhiChu,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
	    {
		    TblThanhToan item = new TblThanhToan();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.IdThanhToan = IdThanhToan;
				
			item.IdDuAn = IdDuAn;
				
			item.MaDotThanhToan = MaDotThanhToan;
				
			item.TenDotThanhToan = TenDotThanhToan;
				
			item.SoTien = SoTien;
				
			item.HanThanhToan = HanThanhToan;
				
			item.NgayThanhToanThucTe = NgayThanhToanThucTe;
				
			item.TrangThai = TrangThai;
				
			item.GhiChu = GhiChu;
				
			item.DaXoa = DaXoa;
				
			item.NguoiTao = NguoiTao;
				
			item.NgayTao = NgayTao;
				
			item.NguoiCapNhat = NguoiCapNhat;
				
			item.NgayCapNhat = NgayCapNhat;
				
	        item.Save(UserName);
	    }
    }
}
