using System;
using System.ComponentModel;
using System.Data;
using System.Xml.Serialization;
using SubSonic;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    [Serializable]
    public partial class TblVanDeCollection : ActiveList<TblVanDe, TblVanDeCollection>
    {
        public TblVanDeCollection() { }
    }

    [Serializable]
    public partial class TblVanDe : ActiveRecord<TblVanDe>, IActiveRecord
    {
        public TblVanDe()
        {
            SetSQLProps();
            SetDefaults();
            MarkNew();
        }

        public TblVanDe(bool useDatabaseDefaults)
        {
            SetSQLProps();
            if (useDatabaseDefaults) ForceDefaults();
            MarkNew();
        }

        public TblVanDe(object keyID)
        {
            SetSQLProps();
            SetDefaults();
            LoadByKey(keyID);
        }

        public TblVanDe(string columnName, object columnValue)
        {
            SetSQLProps();
            SetDefaults();
            LoadByParam(columnName, columnValue);
        }

        protected static void SetSQLProps() { GetTableSchema(); }
        public static Query CreateQuery() { return new Query(Schema); }
        public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null) SetSQLProps();
                return BaseSchema;
            }
        }

        private static void GetTableSchema()
        {
            if (IsSchemaInitialized) return;
            TableSchema.Table schema = new TableSchema.Table("TblVanDe", TableType.Table, DataService.GetInstance("DataAccessProvider"));
            schema.Columns = new TableSchema.TableColumnCollection();
            schema.SchemaName = @"dbo";
            TableSchema.TableColumn columnIdVanDe = new TableSchema.TableColumn(schema);
            columnIdVanDe.ColumnName = "IdVanDe";
            columnIdVanDe.DataType = DbType.Guid;
            columnIdVanDe.MaxLength = 0;
            columnIdVanDe.AutoIncrement = false;
            columnIdVanDe.IsNullable = false;
            columnIdVanDe.IsPrimaryKey = true;
            columnIdVanDe.IsForeignKey = false;
            columnIdVanDe.IsReadOnly = false;
            columnIdVanDe.DefaultSetting = @"(newid())";
            columnIdVanDe.ForeignKeyTableName = "";
            schema.Columns.Add(columnIdVanDe);
            TableSchema.TableColumn columnIdDuAn = new TableSchema.TableColumn(schema);
            columnIdDuAn.ColumnName = "IdDuAn";
            columnIdDuAn.DataType = DbType.Guid;
            columnIdDuAn.MaxLength = 0;
            columnIdDuAn.AutoIncrement = false;
            columnIdDuAn.IsNullable = false;
            columnIdDuAn.IsPrimaryKey = false;
            columnIdDuAn.IsForeignKey = true;
            columnIdDuAn.IsReadOnly = false;
            columnIdDuAn.DefaultSetting = @"";
            columnIdDuAn.ForeignKeyTableName = "TblDuAn";
            schema.Columns.Add(columnIdDuAn);
            TableSchema.TableColumn columnIdCongViecBiAnhHuong = new TableSchema.TableColumn(schema);
            columnIdCongViecBiAnhHuong.ColumnName = "IdCongViecBiAnhHuong";
            columnIdCongViecBiAnhHuong.DataType = DbType.Guid;
            columnIdCongViecBiAnhHuong.MaxLength = 0;
            columnIdCongViecBiAnhHuong.AutoIncrement = false;
            columnIdCongViecBiAnhHuong.IsNullable = true;
            columnIdCongViecBiAnhHuong.IsPrimaryKey = false;
            columnIdCongViecBiAnhHuong.IsForeignKey = true;
            columnIdCongViecBiAnhHuong.IsReadOnly = false;
            columnIdCongViecBiAnhHuong.DefaultSetting = @"";
            columnIdCongViecBiAnhHuong.ForeignKeyTableName = "TblCongViec";
            schema.Columns.Add(columnIdCongViecBiAnhHuong);
            TableSchema.TableColumn columnTenVanDe = new TableSchema.TableColumn(schema);
            columnTenVanDe.ColumnName = "TenVanDe";
            columnTenVanDe.DataType = DbType.String;
            columnTenVanDe.MaxLength = 255;
            columnTenVanDe.AutoIncrement = false;
            columnTenVanDe.IsNullable = false;
            columnTenVanDe.IsPrimaryKey = false;
            columnTenVanDe.IsForeignKey = false;
            columnTenVanDe.IsReadOnly = false;
            columnTenVanDe.DefaultSetting = @"";
            columnTenVanDe.ForeignKeyTableName = "";
            schema.Columns.Add(columnTenVanDe);
            TableSchema.TableColumn columnMoTaChiTiet = new TableSchema.TableColumn(schema);
            columnMoTaChiTiet.ColumnName = "MoTaChiTiet";
            columnMoTaChiTiet.DataType = DbType.String;
            columnMoTaChiTiet.MaxLength = -1;
            columnMoTaChiTiet.AutoIncrement = false;
            columnMoTaChiTiet.IsNullable = true;
            columnMoTaChiTiet.IsPrimaryKey = false;
            columnMoTaChiTiet.IsForeignKey = false;
            columnMoTaChiTiet.IsReadOnly = false;
            columnMoTaChiTiet.DefaultSetting = @"";
            columnMoTaChiTiet.ForeignKeyTableName = "";
            schema.Columns.Add(columnMoTaChiTiet);
            TableSchema.TableColumn columnMucDoAnhHuong = new TableSchema.TableColumn(schema);
            columnMucDoAnhHuong.ColumnName = "MucDoAnhHuong";
            columnMucDoAnhHuong.DataType = DbType.Int32;
            columnMucDoAnhHuong.MaxLength = 0;
            columnMucDoAnhHuong.AutoIncrement = false;
            columnMucDoAnhHuong.IsNullable = true;
            columnMucDoAnhHuong.IsPrimaryKey = false;
            columnMucDoAnhHuong.IsForeignKey = false;
            columnMucDoAnhHuong.IsReadOnly = false;
            columnMucDoAnhHuong.DefaultSetting = @"";
            columnMucDoAnhHuong.ForeignKeyTableName = "";
            schema.Columns.Add(columnMucDoAnhHuong);
            TableSchema.TableColumn columnKeHoachXuLy = new TableSchema.TableColumn(schema);
            columnKeHoachXuLy.ColumnName = "KeHoachXuLy";
            columnKeHoachXuLy.DataType = DbType.String;
            columnKeHoachXuLy.MaxLength = -1;
            columnKeHoachXuLy.AutoIncrement = false;
            columnKeHoachXuLy.IsNullable = true;
            columnKeHoachXuLy.IsPrimaryKey = false;
            columnKeHoachXuLy.IsForeignKey = false;
            columnKeHoachXuLy.IsReadOnly = false;
            columnKeHoachXuLy.DefaultSetting = @"";
            columnKeHoachXuLy.ForeignKeyTableName = "";
            schema.Columns.Add(columnKeHoachXuLy);
            TableSchema.TableColumn columnTrangThai = new TableSchema.TableColumn(schema);
            columnTrangThai.ColumnName = "TrangThai";
            columnTrangThai.DataType = DbType.Byte;
            columnTrangThai.MaxLength = 0;
            columnTrangThai.AutoIncrement = false;
            columnTrangThai.IsNullable = false;
            columnTrangThai.IsPrimaryKey = false;
            columnTrangThai.IsForeignKey = false;
            columnTrangThai.IsReadOnly = false;
            columnTrangThai.DefaultSetting = @"((0))";
            columnTrangThai.ForeignKeyTableName = "";
            schema.Columns.Add(columnTrangThai);
            TableSchema.TableColumn columnDaXoa = new TableSchema.TableColumn(schema);
            columnDaXoa.ColumnName = "DaXoa";
            columnDaXoa.DataType = DbType.Boolean;
            columnDaXoa.MaxLength = 0;
            columnDaXoa.AutoIncrement = false;
            columnDaXoa.IsNullable = false;
            columnDaXoa.IsPrimaryKey = false;
            columnDaXoa.IsForeignKey = false;
            columnDaXoa.IsReadOnly = false;
            columnDaXoa.DefaultSetting = @"((0))";
            columnDaXoa.ForeignKeyTableName = "";
            schema.Columns.Add(columnDaXoa);
            TableSchema.TableColumn columnNguoiTao = new TableSchema.TableColumn(schema);
            columnNguoiTao.ColumnName = "NguoiTao";
            columnNguoiTao.DataType = DbType.String;
            columnNguoiTao.MaxLength = 150;
            columnNguoiTao.AutoIncrement = false;
            columnNguoiTao.IsNullable = false;
            columnNguoiTao.IsPrimaryKey = false;
            columnNguoiTao.IsForeignKey = false;
            columnNguoiTao.IsReadOnly = false;
            columnNguoiTao.DefaultSetting = @"";
            columnNguoiTao.ForeignKeyTableName = "";
            schema.Columns.Add(columnNguoiTao);
            TableSchema.TableColumn columnNgayTao = new TableSchema.TableColumn(schema);
            columnNgayTao.ColumnName = "NgayTao";
            columnNgayTao.DataType = DbType.DateTime;
            columnNgayTao.MaxLength = 0;
            columnNgayTao.AutoIncrement = false;
            columnNgayTao.IsNullable = false;
            columnNgayTao.IsPrimaryKey = false;
            columnNgayTao.IsForeignKey = false;
            columnNgayTao.IsReadOnly = false;
            columnNgayTao.DefaultSetting = @"(getdate())";
            columnNgayTao.ForeignKeyTableName = "";
            schema.Columns.Add(columnNgayTao);
            TableSchema.TableColumn columnNguoiCapNhat = new TableSchema.TableColumn(schema);
            columnNguoiCapNhat.ColumnName = "NguoiCapNhat";
            columnNguoiCapNhat.DataType = DbType.String;
            columnNguoiCapNhat.MaxLength = 150;
            columnNguoiCapNhat.AutoIncrement = false;
            columnNguoiCapNhat.IsNullable = true;
            columnNguoiCapNhat.IsPrimaryKey = false;
            columnNguoiCapNhat.IsForeignKey = false;
            columnNguoiCapNhat.IsReadOnly = false;
            columnNguoiCapNhat.DefaultSetting = @"";
            columnNguoiCapNhat.ForeignKeyTableName = "";
            schema.Columns.Add(columnNguoiCapNhat);
            TableSchema.TableColumn columnNgayCapNhat = new TableSchema.TableColumn(schema);
            columnNgayCapNhat.ColumnName = "NgayCapNhat";
            columnNgayCapNhat.DataType = DbType.DateTime;
            columnNgayCapNhat.MaxLength = 0;
            columnNgayCapNhat.AutoIncrement = false;
            columnNgayCapNhat.IsNullable = true;
            columnNgayCapNhat.IsPrimaryKey = false;
            columnNgayCapNhat.IsForeignKey = false;
            columnNgayCapNhat.IsReadOnly = false;
            columnNgayCapNhat.DefaultSetting = @"";
            columnNgayCapNhat.ForeignKeyTableName = "";
            schema.Columns.Add(columnNgayCapNhat);
            TableSchema.TableColumn columnMaVanDe = new TableSchema.TableColumn(schema);
            columnMaVanDe.ColumnName = "MaVanDe";
            columnMaVanDe.DataType = DbType.AnsiString;
            columnMaVanDe.MaxLength = 50;
            columnMaVanDe.AutoIncrement = false;
            columnMaVanDe.IsNullable = true;
            columnMaVanDe.IsPrimaryKey = false;
            columnMaVanDe.IsForeignKey = false;
            columnMaVanDe.IsReadOnly = false;
            columnMaVanDe.DefaultSetting = @"";
            columnMaVanDe.ForeignKeyTableName = "";
            schema.Columns.Add(columnMaVanDe);
            TableSchema.TableColumn columnIdCongViecPhatSinh = new TableSchema.TableColumn(schema);
            columnIdCongViecPhatSinh.ColumnName = "IdCongViecPhatSinh";
            columnIdCongViecPhatSinh.DataType = DbType.Guid;
            columnIdCongViecPhatSinh.MaxLength = 0;
            columnIdCongViecPhatSinh.AutoIncrement = false;
            columnIdCongViecPhatSinh.IsNullable = true;
            columnIdCongViecPhatSinh.IsPrimaryKey = false;
            columnIdCongViecPhatSinh.IsForeignKey = true;
            columnIdCongViecPhatSinh.IsReadOnly = false;
            columnIdCongViecPhatSinh.DefaultSetting = @"";
            columnIdCongViecPhatSinh.ForeignKeyTableName = "TblCongViec";
            schema.Columns.Add(columnIdCongViecPhatSinh);
            TableSchema.TableColumn columnNguonGocVanDe = new TableSchema.TableColumn(schema);
            columnNguonGocVanDe.ColumnName = "NguonGocVanDe";
            columnNguonGocVanDe.DataType = DbType.Int32;
            columnNguonGocVanDe.MaxLength = 0;
            columnNguonGocVanDe.AutoIncrement = false;
            columnNguonGocVanDe.IsNullable = true;
            columnNguonGocVanDe.IsPrimaryKey = false;
            columnNguonGocVanDe.IsForeignKey = false;
            columnNguonGocVanDe.IsReadOnly = false;
            columnNguonGocVanDe.DefaultSetting = @"";
            columnNguonGocVanDe.ForeignKeyTableName = "";
            schema.Columns.Add(columnNguonGocVanDe);
            BaseSchema = schema;
            DataService.Providers["DataAccessProvider"].AddSchema("TblVanDe", schema);
        }

        [XmlAttribute("IdVanDe")]
        [Bindable(true)]
        public Guid IdVanDe
        {
            get { return GetColumnValue<Guid>(Columns.IdVanDe); }
            set { SetColumnValue(Columns.IdVanDe, value); }
        }

        [XmlAttribute("IdDuAn")]
        [Bindable(true)]
        public Guid IdDuAn
        {
            get { return GetColumnValue<Guid>(Columns.IdDuAn); }
            set { SetColumnValue(Columns.IdDuAn, value); }
        }

        [XmlAttribute("IdCongViecBiAnhHuong")]
        [Bindable(true)]
        public Guid? IdCongViecBiAnhHuong
        {
            get { return GetColumnValue<Guid?>(Columns.IdCongViecBiAnhHuong); }
            set { SetColumnValue(Columns.IdCongViecBiAnhHuong, value); }
        }

        [XmlAttribute("TenVanDe")]
        [Bindable(true)]
        public string TenVanDe
        {
            get { return GetColumnValue<string>(Columns.TenVanDe); }
            set { SetColumnValue(Columns.TenVanDe, value); }
        }

        [XmlAttribute("MoTaChiTiet")]
        [Bindable(true)]
        public string MoTaChiTiet
        {
            get { return GetColumnValue<string>(Columns.MoTaChiTiet); }
            set { SetColumnValue(Columns.MoTaChiTiet, value); }
        }

        [XmlAttribute("MucDoAnhHuong")]
        [Bindable(true)]
        public int? MucDoAnhHuong
        {
            get { return GetColumnValue<int?>(Columns.MucDoAnhHuong); }
            set { SetColumnValue(Columns.MucDoAnhHuong, value); }
        }

        [XmlAttribute("KeHoachXuLy")]
        [Bindable(true)]
        public string KeHoachXuLy
        {
            get { return GetColumnValue<string>(Columns.KeHoachXuLy); }
            set { SetColumnValue(Columns.KeHoachXuLy, value); }
        }

        [XmlAttribute("TrangThai")]
        [Bindable(true)]
        public byte TrangThai
        {
            get { return GetColumnValue<byte>(Columns.TrangThai); }
            set { SetColumnValue(Columns.TrangThai, value); }
        }

        [XmlAttribute("DaXoa")]
        [Bindable(true)]
        public bool DaXoa
        {
            get { return GetColumnValue<bool>(Columns.DaXoa); }
            set { SetColumnValue(Columns.DaXoa, value); }
        }

        [XmlAttribute("NguoiTao")]
        [Bindable(true)]
        public string NguoiTao
        {
            get { return GetColumnValue<string>(Columns.NguoiTao); }
            set { SetColumnValue(Columns.NguoiTao, value); }
        }

        [XmlAttribute("NgayTao")]
        [Bindable(true)]
        public DateTime NgayTao
        {
            get { return GetColumnValue<DateTime>(Columns.NgayTao); }
            set { SetColumnValue(Columns.NgayTao, value); }
        }

        [XmlAttribute("NguoiCapNhat")]
        [Bindable(true)]
        public string NguoiCapNhat
        {
            get { return GetColumnValue<string>(Columns.NguoiCapNhat); }
            set { SetColumnValue(Columns.NguoiCapNhat, value); }
        }

        [XmlAttribute("NgayCapNhat")]
        [Bindable(true)]
        public DateTime? NgayCapNhat
        {
            get { return GetColumnValue<DateTime?>(Columns.NgayCapNhat); }
            set { SetColumnValue(Columns.NgayCapNhat, value); }
        }

        [XmlAttribute("MaVanDe")]
        [Bindable(true)]
        public string MaVanDe
        {
            get { return GetColumnValue<string>(Columns.MaVanDe); }
            set { SetColumnValue(Columns.MaVanDe, value); }
        }

        [XmlAttribute("IdCongViecPhatSinh")]
        [Bindable(true)]
        public Guid? IdCongViecPhatSinh
        {
            get { return GetColumnValue<Guid?>(Columns.IdCongViecPhatSinh); }
            set { SetColumnValue(Columns.IdCongViecPhatSinh, value); }
        }

        [XmlAttribute("NguonGocVanDe")]
        [Bindable(true)]
        public int? NguonGocVanDe
        {
            get { return GetColumnValue<int?>(Columns.NguonGocVanDe); }
            set { SetColumnValue(Columns.NguonGocVanDe, value); }
        }

        public static void Insert(Guid varIdVanDe,Guid varIdDuAn,Guid? varIdCongViecBiAnhHuong,string varTenVanDe,string varMoTaChiTiet,int? varMucDoAnhHuong,string varKeHoachXuLy,byte varTrangThai,bool varDaXoa,string varNguoiTao,DateTime varNgayTao,string varNguoiCapNhat,DateTime? varNgayCapNhat,string varMaVanDe,Guid? varIdCongViecPhatSinh,int? varNguonGocVanDe)
        {
            TblVanDe item = new TblVanDe();
            item.IdVanDe = varIdVanDe;
            item.IdDuAn = varIdDuAn;
            item.IdCongViecBiAnhHuong = varIdCongViecBiAnhHuong;
            item.TenVanDe = varTenVanDe;
            item.MoTaChiTiet = varMoTaChiTiet;
            item.MucDoAnhHuong = varMucDoAnhHuong;
            item.KeHoachXuLy = varKeHoachXuLy;
            item.TrangThai = varTrangThai;
            item.DaXoa = varDaXoa;
            item.NguoiTao = varNguoiTao;
            item.NgayTao = varNgayTao;
            item.NguoiCapNhat = varNguoiCapNhat;
            item.NgayCapNhat = varNgayCapNhat;
            item.MaVanDe = varMaVanDe;
            item.IdCongViecPhatSinh = varIdCongViecPhatSinh;
            item.NguonGocVanDe = varNguonGocVanDe;
            if (System.Web.HttpContext.Current != null)
                item.Save(System.Web.HttpContext.Current.User.Identity.Name);
            else
                item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
        }

        public static void Update(Guid varIdVanDe,Guid varIdDuAn,Guid? varIdCongViecBiAnhHuong,string varTenVanDe,string varMoTaChiTiet,int? varMucDoAnhHuong,string varKeHoachXuLy,byte varTrangThai,bool varDaXoa,string varNguoiTao,DateTime varNgayTao,string varNguoiCapNhat,DateTime? varNgayCapNhat,string varMaVanDe,Guid? varIdCongViecPhatSinh,int? varNguonGocVanDe)
        {
            TblVanDe item = new TblVanDe();
            item.IdVanDe = varIdVanDe;
            item.IdDuAn = varIdDuAn;
            item.IdCongViecBiAnhHuong = varIdCongViecBiAnhHuong;
            item.TenVanDe = varTenVanDe;
            item.MoTaChiTiet = varMoTaChiTiet;
            item.MucDoAnhHuong = varMucDoAnhHuong;
            item.KeHoachXuLy = varKeHoachXuLy;
            item.TrangThai = varTrangThai;
            item.DaXoa = varDaXoa;
            item.NguoiTao = varNguoiTao;
            item.NgayTao = varNgayTao;
            item.NguoiCapNhat = varNguoiCapNhat;
            item.NgayCapNhat = varNgayCapNhat;
            item.MaVanDe = varMaVanDe;
            item.IdCongViecPhatSinh = varIdCongViecPhatSinh;
            item.NguonGocVanDe = varNguonGocVanDe;
            item.IsNew = false;
            if (System.Web.HttpContext.Current != null)
                item.Save(System.Web.HttpContext.Current.User.Identity.Name);
            else
                item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
        }

        public static TableSchema.TableColumn IdVanDeColumn
        {
            get { return Schema.Columns[0]; }
        }

        public static TableSchema.TableColumn IdDuAnColumn
        {
            get { return Schema.Columns[1]; }
        }

        public static TableSchema.TableColumn IdCongViecBiAnhHuongColumn
        {
            get { return Schema.Columns[2]; }
        }

        public static TableSchema.TableColumn TenVanDeColumn
        {
            get { return Schema.Columns[3]; }
        }

        public static TableSchema.TableColumn MoTaChiTietColumn
        {
            get { return Schema.Columns[4]; }
        }

        public static TableSchema.TableColumn MucDoAnhHuongColumn
        {
            get { return Schema.Columns[5]; }
        }

        public static TableSchema.TableColumn KeHoachXuLyColumn
        {
            get { return Schema.Columns[6]; }
        }

        public static TableSchema.TableColumn TrangThaiColumn
        {
            get { return Schema.Columns[7]; }
        }

        public static TableSchema.TableColumn DaXoaColumn
        {
            get { return Schema.Columns[8]; }
        }

        public static TableSchema.TableColumn NguoiTaoColumn
        {
            get { return Schema.Columns[9]; }
        }

        public static TableSchema.TableColumn NgayTaoColumn
        {
            get { return Schema.Columns[10]; }
        }

        public static TableSchema.TableColumn NguoiCapNhatColumn
        {
            get { return Schema.Columns[11]; }
        }

        public static TableSchema.TableColumn NgayCapNhatColumn
        {
            get { return Schema.Columns[12]; }
        }

        public static TableSchema.TableColumn MaVanDeColumn
        {
            get { return Schema.Columns[13]; }
        }

        public static TableSchema.TableColumn IdCongViecPhatSinhColumn
        {
            get { return Schema.Columns[14]; }
        }

        public static TableSchema.TableColumn NguonGocVanDeColumn
        {
            get { return Schema.Columns[15]; }
        }

        public struct Columns
        {
            public static string IdVanDe = @"IdVanDe";
            public static string IdDuAn = @"IdDuAn";
            public static string IdCongViecBiAnhHuong = @"IdCongViecBiAnhHuong";
            public static string TenVanDe = @"TenVanDe";
            public static string MoTaChiTiet = @"MoTaChiTiet";
            public static string MucDoAnhHuong = @"MucDoAnhHuong";
            public static string KeHoachXuLy = @"KeHoachXuLy";
            public static string TrangThai = @"TrangThai";
            public static string DaXoa = @"DaXoa";
            public static string NguoiTao = @"NguoiTao";
            public static string NgayTao = @"NgayTao";
            public static string NguoiCapNhat = @"NguoiCapNhat";
            public static string NgayCapNhat = @"NgayCapNhat";
            public static string MaVanDe = @"MaVanDe";
            public static string IdCongViecPhatSinh = @"IdCongViecPhatSinh";
            public static string NguonGocVanDe = @"NguonGocVanDe";
        }
    }
}
