using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    /// <summary>
    /// Controller class for TblVanDe
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblVanDeController
    {
        // Preload our schema..
        TblVanDe thisSchemaLoad = new TblVanDe();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblVanDeCollection FetchAll()
        {
            TblVanDeCollection coll = new TblVanDeCollection();
            Query qry = new Query(TblVanDe.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblVanDeCollection FetchByID(object IdVanDe)
        {
            TblVanDeCollection coll = new TblVanDeCollection().Where("IdVanDe", IdVanDe).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblVanDeCollection FetchByQuery(Query qry)
        {
            TblVanDeCollection coll = new TblVanDeCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdVanDe)
        {
            return (TblVanDe.Delete(IdVanDe) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdVanDe)
        {
            return (TblVanDe.Destroy(IdVanDe) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid IdVanDe,Guid IdDuAn,Guid? IdCongViecBiAnhHuong,string TenVanDe,string MoTaChiTiet,int? MucDoAnhHuong,string KeHoachXuLy,byte TrangThai,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat,string MaVanDe,Guid? IdCongViecPhatSinh,int? NguonGocVanDe)
	    {
		    TblVanDe item = new TblVanDe();
		    
            item.IdVanDe = IdVanDe;
            
            item.IdDuAn = IdDuAn;
            
            item.IdCongViecBiAnhHuong = IdCongViecBiAnhHuong;
            
            item.TenVanDe = TenVanDe;
            
            item.MoTaChiTiet = MoTaChiTiet;
            
            item.MucDoAnhHuong = MucDoAnhHuong;
            
            item.KeHoachXuLy = KeHoachXuLy;
            
            item.TrangThai = TrangThai;
            
            item.DaXoa = DaXoa;
            
            item.NguoiTao = NguoiTao;
            
            item.NgayTao = NgayTao;
            
            item.NguoiCapNhat = NguoiCapNhat;
            
            item.NgayCapNhat = NgayCapNhat;
            
            item.MaVanDe = MaVanDe;
            
            item.IdCongViecPhatSinh = IdCongViecPhatSinh;
            
            item.NguonGocVanDe = NguonGocVanDe;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid IdVanDe,Guid IdDuAn,Guid? IdCongViecBiAnhHuong,string TenVanDe,string MoTaChiTiet,int? MucDoAnhHuong,string KeHoachXuLy,byte TrangThai,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat,string MaVanDe,Guid? IdCongViecPhatSinh,int? NguonGocVanDe)
	    {
		    TblVanDe item = new TblVanDe();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.IdVanDe = IdVanDe;
				
			item.IdDuAn = IdDuAn;
				
			item.IdCongViecBiAnhHuong = IdCongViecBiAnhHuong;
				
			item.TenVanDe = TenVanDe;
				
			item.MoTaChiTiet = MoTaChiTiet;
				
			item.MucDoAnhHuong = MucDoAnhHuong;
				
			item.KeHoachXuLy = KeHoachXuLy;
				
			item.TrangThai = TrangThai;
				
			item.DaXoa = DaXoa;
				
			item.NguoiTao = NguoiTao;
				
			item.NgayTao = NgayTao;
				
			item.NguoiCapNhat = NguoiCapNhat;
				
			item.NgayCapNhat = NgayCapNhat;
				
			item.MaVanDe = MaVanDe;
				
			item.IdCongViecPhatSinh = IdCongViecPhatSinh;
				
			item.NguonGocVanDe = NguonGocVanDe;
				
	        item.Save(UserName);
	    }
    }
}
