//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweetSoft.QLDA.BackOffice.fDocuments.Controls
{
    public partial class CtrlDocumentDetail
    {
        protected global::System.Web.UI.UpdatePanel upDetail;
        protected global::System.Web.UI.WebControls.HiddenField hdfIdTaiLieu;
        protected global::System.Web.UI.WebControls.Label lblDocumentName;
        protected global::System.Web.UI.WebControls.Label lblDocumentCode;
        protected global::System.Web.UI.WebControls.Label lblDocumentStatus;
        protected global::SweetSoft.QLDA.Controls.ExtraButton btnBack;
        protected global::System.Web.UI.WebControls.Panel pnlOfficialFile;
        protected global::System.Web.UI.WebControls.HyperLink lnkOfficialFile;
        protected global::System.Web.UI.WebControls.Label lblOfficialFileMeta;
        protected global::System.Web.UI.WebControls.Panel pnlNoOfficialFile;
        protected global::System.Web.UI.WebControls.Label lblSigningSummary;
        protected global::System.Web.UI.WebControls.Label lblCustomerSummary;
        protected global::System.Web.UI.WebControls.Label lblStorageSummary;
        protected global::System.Web.UI.WebControls.Label lblVersionCount;
        protected global::System.Web.UI.WebControls.PlaceHolder phSigningTab;
        protected global::System.Web.UI.WebControls.PlaceHolder phCustomerTab;
        protected global::System.Web.UI.WebControls.PlaceHolder phStorageTab;
        protected global::System.Web.UI.WebControls.Label lblDocumentGroup;
        protected global::System.Web.UI.WebControls.Label lblDocumentType;
        protected global::System.Web.UI.WebControls.Label lblResponsibleEmployee;
        protected global::System.Web.UI.WebControls.Label lblCreatedBy;
        protected global::System.Web.UI.WebControls.Label lblCreatedDate;
        protected global::System.Web.UI.WebControls.Label lblUpdatedDate;
        protected global::System.Web.UI.WebControls.Label lblDescription;
        protected global::System.Web.UI.WebControls.Panel pnlVersionUploader;
        protected global::SweetSoft.QLDA.BackOffice.fFilesBox.FilesBox fbVersions;
        protected global::System.Web.UI.WebControls.Panel pnlNoVersions;
        protected global::System.Web.UI.WebControls.Panel pnlVersions;
        protected global::System.Web.UI.WebControls.Repeater rptVersions;
        protected global::System.Web.UI.WebControls.PlaceHolder phSigningPane;
        protected global::System.Web.UI.WebControls.Panel pnlNoSigning;
        protected global::System.Web.UI.WebControls.Panel pnlSigning;
        protected global::System.Web.UI.WebControls.Repeater rptSigning;
        protected global::System.Web.UI.WebControls.PlaceHolder phCustomerPane;
        protected global::System.Web.UI.WebControls.Panel pnlNoCustomer;
        protected global::System.Web.UI.WebControls.Panel pnlCustomer;
        protected global::System.Web.UI.WebControls.Repeater rptCustomer;
        protected global::System.Web.UI.WebControls.PlaceHolder phStoragePane;
        protected global::System.Web.UI.WebControls.Panel pnlNoStorage;
        protected global::System.Web.UI.WebControls.Panel pnlStorage;
        protected global::System.Web.UI.WebControls.Repeater rptStorage;
        protected global::System.Web.UI.WebControls.Panel pnlNoActivity;
        protected global::System.Web.UI.WebControls.Panel pnlActivity;
        protected global::System.Web.UI.WebControls.Repeater rptActivity;
    }
}
