//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweetSoft.QLDA.BackOffice.fDocuments.Controls
{
    public partial class CtrlStorageLocations
    {
        protected global::System.Web.UI.UpdatePanel upMain;
        protected global::System.Web.UI.WebControls.Panel pnlSearchDefault;
        protected global::SweetSoft.QLDA.Controls.BootstrapDropdown ddlSearchStatus;
        protected global::SweetSoft.QLDA.Controls.BootstrapDropdown ddlSearchCapLuuTru;
        protected global::SweetSoft.QLDA.Controls.ExtraTextBox txtSearch;
        protected global::SweetSoft.QLDA.Controls.ExtraButton btnSearch;
        protected global::SweetSoft.QLDA.Controls.ExtraButton btnAdd;
        protected global::SweetSoft.QLDA.Controls.ExtraSearchBox searchTagBox;
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        protected global::System.Web.UI.WebControls.HiddenField hdfIdNoiLuuTru;
        protected global::System.Web.UI.WebControls.Literal litFormTitle;
        protected global::SweetSoft.QLDA.Controls.ExtraTextBox txtMaNoiLuuTru;
        protected global::SweetSoft.QLDA.Controls.ExtraTextBox txtTenNoiLuuTru;
        protected global::SweetSoft.QLDA.Controls.ExtraDropdown ddlCapLuuTru;
        protected global::SweetSoft.QLDA.Controls.ExtraDropdown ddlNoiLuuTruCha;
        protected global::SweetSoft.QLDA.Controls.ExtraDropdown ddlNguoiPhuTrach;
        protected global::SweetSoft.QLDA.Controls.ExtraTextBox txtMoTa;
        protected global::SweetSoft.QLDA.Controls.ExtraTextBox txtThuTuHienThi;
        protected global::SweetSoft.QLDA.Controls.ExtraCheckbox chkKichHoat;
        protected global::SweetSoft.QLDA.Controls.ExtraButton btnSave;
        protected global::SweetSoft.QLDA.Controls.ExtraButton btnCancel;
        protected global::SweetSoft.QLDA.Controls.GridviewExtension grvData;
        protected global::SweetSoft.QLDA.BackOffice.Controls.GridviewPaging ctrlGridviewPaging;
        protected global::SweetSoft.QLDA.Controls.ExtraButton btnSearchAdvanced;
        protected global::SweetSoft.QLDA.Controls.ExtraButton btnResetSearch;
        protected global::System.Web.UI.UpdatePanel pnlSearch;
        protected global::System.Web.UI.WebControls.Panel pnlSearchPopup;
        protected global::SweetSoft.QLDA.Controls.ExtraTextBox txtSearchMaNoiLuuTru;
        protected global::SweetSoft.QLDA.Controls.ExtraTextBox txtSearchTenNoiLuuTru;
        protected global::SweetSoft.QLDA.Controls.ExtraDropdown ddlSearchNguoiPhuTrach;
        protected global::SweetSoft.QLDA.Controls.ExtraTextBox txtSearchMoTa;
    }
}
