using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
	#region Tables Struct
	public partial struct Tables
	{
		
		public static readonly string AspnetApplication = @"aspnet_Applications";
        
		public static readonly string AspnetAssignRole = @"aspnet_AssignRoles";
        
		public static readonly string AspnetFunction = @"aspnet_Functions";
        
		public static readonly string AspnetMembership = @"aspnet_Membership";
        
		public static readonly string AspnetPath = @"aspnet_Paths";
        
		public static readonly string AspnetPermission = @"aspnet_Permission";
        
		public static readonly string AspnetPersonalizationAllUser = @"aspnet_PersonalizationAllUsers";
        
		public static readonly string AspnetPersonalizationPerUser = @"aspnet_PersonalizationPerUser";
        
		public static readonly string AspnetProfile = @"aspnet_Profile";
        
		public static readonly string AspnetRole = @"aspnet_Roles";
        
		public static readonly string AspnetSchemaVersion = @"aspnet_SchemaVersions";
        
		public static readonly string AspnetUser = @"aspnet_Users";
        
		public static readonly string AspnetUsersInRole = @"aspnet_UsersInRoles";
        
		public static readonly string AspnetWebEventEvent = @"aspnet_WebEvent_Events";
        
		public static readonly string TblAuditLog2026 = @"TblAuditLog_2026";
        
		public static readonly string TblCongViec = @"TblCongViec";
        
		public static readonly string TblCongViecNhanVien = @"TblCongViec_NhanVien";
        
		public static readonly string TblChiPhi = @"TblChiPhi";
        
		public static readonly string TblChucDanh = @"TblChucDanh";
        
		public static readonly string TblDoUuTien = @"TblDoUuTien";
        
		public static readonly string TblDuAn = @"TblDuAn";
        
		public static readonly string TblEmailHistory = @"TblEmailHistory";
        
		public static readonly string TblEmailTemplate = @"TblEmailTemplate";
        
		public static readonly string TblGuiNhanKhachHang = @"TblGuiNhanKhachHang";
        
		public static readonly string TblGiaiDoan = @"TblGiaiDoan";
        
		public static readonly string TblGiaiDoanDuAn = @"TblGiaiDoanDuAn";
        
		public static readonly string TblHopDongThucHien = @"TblHopDongThucHien";
        
		public static readonly string TblKhachHang = @"TblKhachHang";
        
		public static readonly string TblLichHop = @"TblLichHop";
        
		public static readonly string TblLichSuChinhSua = @"TblLichSuChinhSua";
        
		public static readonly string TblLichSuDuAn = @"TblLichSuDuAn";
        
		public static readonly string TblLichSuTaiLieu = @"TblLichSuTaiLieu";
        
		public static readonly string TblLoaiDuAn = @"TblLoaiDuAn";
        
		public static readonly string TblLoaiKhachHang = @"TblLoaiKhachHang";
        
		public static readonly string TblLoaiTaiLieu = @"TblLoaiTaiLieu";
        
		public static readonly string TblLuuTruVatLy = @"TblLuuTruVatLy";
        
		public static readonly string TblMauTaiLieu = @"TblMauTaiLieu";
        
		public static readonly string TblNoiLuuTru = @"TblNoiLuuTru";
        
		public static readonly string TblNhanVien = @"TblNhanVien";
        
		public static readonly string TblNhomTaiLieu = @"TblNhomTaiLieu";
        
		public static readonly string TblPhienBanTaiLieu = @"TblPhienBanTaiLieu";
        
		public static readonly string TblPhongBan = @"TblPhongBan";
        
		public static readonly string TblRuiRo = @"TblRuiRo";
        
		public static readonly string TblSetting = @"TblSettings";
        
		public static readonly string TblTaiLieu = @"TblTaiLieu";
        
		public static readonly string TblThanhToan = @"TblThanhToan";
        
		public static readonly string TblThanhVienDuAn = @"TblThanhVienDuAn";
        
		public static readonly string TblThongBao = @"TblThongBao";
        
		public static readonly string TblTrinhKyTaiLieu = @"TblTrinhKyTaiLieu";
        
		public static readonly string TblUploadFile = @"TblUploadFile";
        
		public static readonly string TblVaiTroDuAn = @"TblVaiTroDuAn";
        
		public static readonly string TblVanDe = @"TblVanDe";
        
	}
	#endregion
    #region Schemas
    public partial class Schemas {
		
		public static TableSchema.Table AspnetApplication
		{
            get { return DataService.GetSchema("aspnet_Applications", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table AspnetAssignRole
		{
            get { return DataService.GetSchema("aspnet_AssignRoles", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table AspnetFunction
		{
            get { return DataService.GetSchema("aspnet_Functions", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table AspnetMembership
		{
            get { return DataService.GetSchema("aspnet_Membership", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table AspnetPath
		{
            get { return DataService.GetSchema("aspnet_Paths", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table AspnetPermission
		{
            get { return DataService.GetSchema("aspnet_Permission", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table AspnetPersonalizationAllUser
		{
            get { return DataService.GetSchema("aspnet_PersonalizationAllUsers", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table AspnetPersonalizationPerUser
		{
            get { return DataService.GetSchema("aspnet_PersonalizationPerUser", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table AspnetProfile
		{
            get { return DataService.GetSchema("aspnet_Profile", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table AspnetRole
		{
            get { return DataService.GetSchema("aspnet_Roles", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table AspnetSchemaVersion
		{
            get { return DataService.GetSchema("aspnet_SchemaVersions", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table AspnetUser
		{
            get { return DataService.GetSchema("aspnet_Users", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table AspnetUsersInRole
		{
            get { return DataService.GetSchema("aspnet_UsersInRoles", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table AspnetWebEventEvent
		{
            get { return DataService.GetSchema("aspnet_WebEvent_Events", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblAuditLog2026
		{
            get { return DataService.GetSchema("TblAuditLog_2026", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblCongViec
		{
            get { return DataService.GetSchema("TblCongViec", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblCongViecNhanVien
		{
            get { return DataService.GetSchema("TblCongViec_NhanVien", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblChiPhi
		{
            get { return DataService.GetSchema("TblChiPhi", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblChucDanh
		{
            get { return DataService.GetSchema("TblChucDanh", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblDoUuTien
		{
            get { return DataService.GetSchema("TblDoUuTien", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblDuAn
		{
            get { return DataService.GetSchema("TblDuAn", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblEmailHistory
		{
            get { return DataService.GetSchema("TblEmailHistory", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblEmailTemplate
		{
            get { return DataService.GetSchema("TblEmailTemplate", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblGuiNhanKhachHang
		{
            get { return DataService.GetSchema("TblGuiNhanKhachHang", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblGiaiDoan
		{
            get { return DataService.GetSchema("TblGiaiDoan", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblGiaiDoanDuAn
		{
            get { return DataService.GetSchema("TblGiaiDoanDuAn", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblHopDongThucHien
		{
            get { return DataService.GetSchema("TblHopDongThucHien", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblKhachHang
		{
            get { return DataService.GetSchema("TblKhachHang", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblLichHop
		{
            get { return DataService.GetSchema("TblLichHop", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblLichSuChinhSua
		{
            get { return DataService.GetSchema("TblLichSuChinhSua", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblLichSuDuAn
		{
            get { return DataService.GetSchema("TblLichSuDuAn", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblLichSuTaiLieu
		{
            get { return DataService.GetSchema("TblLichSuTaiLieu", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblLoaiDuAn
		{
            get { return DataService.GetSchema("TblLoaiDuAn", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblLoaiKhachHang
		{
            get { return DataService.GetSchema("TblLoaiKhachHang", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblLoaiTaiLieu
		{
            get { return DataService.GetSchema("TblLoaiTaiLieu", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblLuuTruVatLy
		{
            get { return DataService.GetSchema("TblLuuTruVatLy", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblMauTaiLieu
		{
            get { return DataService.GetSchema("TblMauTaiLieu", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblNoiLuuTru
		{
            get { return DataService.GetSchema("TblNoiLuuTru", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblNhanVien
		{
            get { return DataService.GetSchema("TblNhanVien", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblNhomTaiLieu
		{
            get { return DataService.GetSchema("TblNhomTaiLieu", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblPhienBanTaiLieu
		{
            get { return DataService.GetSchema("TblPhienBanTaiLieu", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblPhongBan
		{
            get { return DataService.GetSchema("TblPhongBan", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblRuiRo
		{
            get { return DataService.GetSchema("TblRuiRo", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblSetting
		{
            get { return DataService.GetSchema("TblSettings", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblTaiLieu
		{
            get { return DataService.GetSchema("TblTaiLieu", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblThanhToan
		{
            get { return DataService.GetSchema("TblThanhToan", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblThanhVienDuAn
		{
            get { return DataService.GetSchema("TblThanhVienDuAn", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblThongBao
		{
            get { return DataService.GetSchema("TblThongBao", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblTrinhKyTaiLieu
		{
            get { return DataService.GetSchema("TblTrinhKyTaiLieu", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblUploadFile
		{
            get { return DataService.GetSchema("TblUploadFile", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblVaiTroDuAn
		{
            get { return DataService.GetSchema("TblVaiTroDuAn", "DataAccessProvider"); }
		}
        
		public static TableSchema.Table TblVanDe
		{
            get { return DataService.GetSchema("TblVanDe", "DataAccessProvider"); }
		}
        
	
    }
    #endregion
    #region View Struct
    public partial struct Views 
    {
		
		public static readonly string VwAspnetApplication = @"vw_aspnet_Applications";
        
		public static readonly string VwAspnetMembershipUser = @"vw_aspnet_MembershipUsers";
        
		public static readonly string VwAspnetProfile = @"vw_aspnet_Profiles";
        
		public static readonly string VwAspnetRole = @"vw_aspnet_Roles";
        
		public static readonly string VwAspnetUser = @"vw_aspnet_Users";
        
		public static readonly string VwAspnetUsersInRole = @"vw_aspnet_UsersInRoles";
        
		public static readonly string VwAspnetWebPartStatePath = @"vw_aspnet_WebPartState_Paths";
        
		public static readonly string VwAspnetWebPartStateShared = @"vw_aspnet_WebPartState_Shared";
        
		public static readonly string VwAspnetWebPartStateUser = @"vw_aspnet_WebPartState_User";
        
    }
    #endregion
    
    #region Query Factories
	public static partial class DB
	{
        public static DataProvider _provider = DataService.Providers["DataAccessProvider"];
        static ISubSonicRepository _repository;
        public static ISubSonicRepository Repository 
        {
            get 
            {
                if (_repository == null)
                    return new SubSonicRepository(_provider);
                return _repository; 
            }
            set { _repository = value; }
        }
        public static Select SelectAllColumnsFrom<T>() where T : RecordBase<T>, new()
	    {
            return Repository.SelectAllColumnsFrom<T>();
	    }
	    public static Select Select()
	    {
            return Repository.Select();
	    }
	    
		public static Select Select(params string[] columns)
		{
            return Repository.Select(columns);
        }
	    
		public static Select Select(params Aggregate[] aggregates)
		{
            return Repository.Select(aggregates);
        }
   
	    public static Update Update<T>() where T : RecordBase<T>, new()
	    {
            return Repository.Update<T>();
	    }
	    
	    public static Insert Insert()
	    {
            return Repository.Insert();
	    }
	    
	    public static Delete Delete()
	    {
            return Repository.Delete();
	    }
	    
	    public static InlineQuery Query()
	    {
            return Repository.Query();
	    }
	    	    
	    
	}
    #endregion
    
}
#region Databases
public partial struct Databases 
{
	
	public static readonly string DataAccessProvider = @"DataAccessProvider";
    
}
#endregion