using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblLuuTruVatLy class.
	/// </summary>
    [Serializable]
	public partial class TblLuuTruVatLyCollection : ActiveList<TblLuuTruVatLy, TblLuuTruVatLyCollection>
	{	   
		public TblLuuTruVatLyCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblLuuTruVatLyCollection</returns>
		public TblLuuTruVatLyCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblLuuTruVatLy o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblLuuTruVatLy table.
	/// </summary>
	[Serializable]
	public partial class TblLuuTruVatLy : ActiveRecord<TblLuuTruVatLy>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblLuuTruVatLy()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblLuuTruVatLy(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblLuuTruVatLy(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblLuuTruVatLy(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblLuuTruVatLy", TableType.Table, DataService.GetInstance("DataAccessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarIdLuuTruVatLy = new TableSchema.TableColumn(schema);
				colvarIdLuuTruVatLy.ColumnName = "IdLuuTruVatLy";
				colvarIdLuuTruVatLy.DataType = DbType.Guid;
				colvarIdLuuTruVatLy.MaxLength = 0;
				colvarIdLuuTruVatLy.AutoIncrement = false;
				colvarIdLuuTruVatLy.IsNullable = false;
				colvarIdLuuTruVatLy.IsPrimaryKey = true;
				colvarIdLuuTruVatLy.IsForeignKey = false;
				colvarIdLuuTruVatLy.IsReadOnly = false;
				
						colvarIdLuuTruVatLy.DefaultSetting = @"(newid())";
				colvarIdLuuTruVatLy.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIdLuuTruVatLy);
				
				TableSchema.TableColumn colvarIdTaiLieu = new TableSchema.TableColumn(schema);
				colvarIdTaiLieu.ColumnName = "IdTaiLieu";
				colvarIdTaiLieu.DataType = DbType.Guid;
				colvarIdTaiLieu.MaxLength = 0;
				colvarIdTaiLieu.AutoIncrement = false;
				colvarIdTaiLieu.IsNullable = false;
				colvarIdTaiLieu.IsPrimaryKey = false;
				colvarIdTaiLieu.IsForeignKey = true;
				colvarIdTaiLieu.IsReadOnly = false;
				colvarIdTaiLieu.DefaultSetting = @"";
				
					colvarIdTaiLieu.ForeignKeyTableName = "TblTaiLieu";
				schema.Columns.Add(colvarIdTaiLieu);
				
				TableSchema.TableColumn colvarIdNoiLuuTru = new TableSchema.TableColumn(schema);
				colvarIdNoiLuuTru.ColumnName = "IdNoiLuuTru";
				colvarIdNoiLuuTru.DataType = DbType.Guid;
				colvarIdNoiLuuTru.MaxLength = 0;
				colvarIdNoiLuuTru.AutoIncrement = false;
				colvarIdNoiLuuTru.IsNullable = false;
				colvarIdNoiLuuTru.IsPrimaryKey = false;
				colvarIdNoiLuuTru.IsForeignKey = true;
				colvarIdNoiLuuTru.IsReadOnly = false;
				colvarIdNoiLuuTru.DefaultSetting = @"";
				
					colvarIdNoiLuuTru.ForeignKeyTableName = "TblNoiLuuTru";
				schema.Columns.Add(colvarIdNoiLuuTru);
				
				TableSchema.TableColumn colvarIdNguoiThucHien = new TableSchema.TableColumn(schema);
				colvarIdNguoiThucHien.ColumnName = "IdNguoiThucHien";
				colvarIdNguoiThucHien.DataType = DbType.Guid;
				colvarIdNguoiThucHien.MaxLength = 0;
				colvarIdNguoiThucHien.AutoIncrement = false;
				colvarIdNguoiThucHien.IsNullable = false;
				colvarIdNguoiThucHien.IsPrimaryKey = false;
				colvarIdNguoiThucHien.IsForeignKey = true;
				colvarIdNguoiThucHien.IsReadOnly = false;
				colvarIdNguoiThucHien.DefaultSetting = @"";
				
					colvarIdNguoiThucHien.ForeignKeyTableName = "TblNhanVien";
				schema.Columns.Add(colvarIdNguoiThucHien);
				
				TableSchema.TableColumn colvarMaLuuTru = new TableSchema.TableColumn(schema);
				colvarMaLuuTru.ColumnName = "MaLuuTru";
				colvarMaLuuTru.DataType = DbType.AnsiString;
				colvarMaLuuTru.MaxLength = 100;
				colvarMaLuuTru.AutoIncrement = false;
				colvarMaLuuTru.IsNullable = false;
				colvarMaLuuTru.IsPrimaryKey = false;
				colvarMaLuuTru.IsForeignKey = false;
				colvarMaLuuTru.IsReadOnly = false;
				colvarMaLuuTru.DefaultSetting = @"";
				colvarMaLuuTru.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMaLuuTru);
				
				TableSchema.TableColumn colvarTrangThaiLuuTru = new TableSchema.TableColumn(schema);
				colvarTrangThaiLuuTru.ColumnName = "TrangThaiLuuTru";
				colvarTrangThaiLuuTru.DataType = DbType.AnsiString;
				colvarTrangThaiLuuTru.MaxLength = 30;
				colvarTrangThaiLuuTru.AutoIncrement = false;
				colvarTrangThaiLuuTru.IsNullable = false;
				colvarTrangThaiLuuTru.IsPrimaryKey = false;
				colvarTrangThaiLuuTru.IsForeignKey = false;
				colvarTrangThaiLuuTru.IsReadOnly = false;
				
						colvarTrangThaiLuuTru.DefaultSetting = @"('DA_LUU')";
				colvarTrangThaiLuuTru.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTrangThaiLuuTru);
				
				TableSchema.TableColumn colvarTinhTrangBanGoc = new TableSchema.TableColumn(schema);
				colvarTinhTrangBanGoc.ColumnName = "TinhTrangBanGoc";
				colvarTinhTrangBanGoc.DataType = DbType.String;
				colvarTinhTrangBanGoc.MaxLength = 255;
				colvarTinhTrangBanGoc.AutoIncrement = false;
				colvarTinhTrangBanGoc.IsNullable = true;
				colvarTinhTrangBanGoc.IsPrimaryKey = false;
				colvarTinhTrangBanGoc.IsForeignKey = false;
				colvarTinhTrangBanGoc.IsReadOnly = false;
				colvarTinhTrangBanGoc.DefaultSetting = @"";
				colvarTinhTrangBanGoc.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTinhTrangBanGoc);
				
				TableSchema.TableColumn colvarNgayLuu = new TableSchema.TableColumn(schema);
				colvarNgayLuu.ColumnName = "NgayLuu";
				colvarNgayLuu.DataType = DbType.DateTime;
				colvarNgayLuu.MaxLength = 0;
				colvarNgayLuu.AutoIncrement = false;
				colvarNgayLuu.IsNullable = false;
				colvarNgayLuu.IsPrimaryKey = false;
				colvarNgayLuu.IsForeignKey = false;
				colvarNgayLuu.IsReadOnly = false;
				
						colvarNgayLuu.DefaultSetting = @"(getdate())";
				colvarNgayLuu.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayLuu);
				
				TableSchema.TableColumn colvarNgayLayRa = new TableSchema.TableColumn(schema);
				colvarNgayLayRa.ColumnName = "NgayLayRa";
				colvarNgayLayRa.DataType = DbType.DateTime;
				colvarNgayLayRa.MaxLength = 0;
				colvarNgayLayRa.AutoIncrement = false;
				colvarNgayLayRa.IsNullable = true;
				colvarNgayLayRa.IsPrimaryKey = false;
				colvarNgayLayRa.IsForeignKey = false;
				colvarNgayLayRa.IsReadOnly = false;
				colvarNgayLayRa.DefaultSetting = @"";
				colvarNgayLayRa.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayLayRa);
				
				TableSchema.TableColumn colvarNgayHoanTra = new TableSchema.TableColumn(schema);
				colvarNgayHoanTra.ColumnName = "NgayHoanTra";
				colvarNgayHoanTra.DataType = DbType.DateTime;
				colvarNgayHoanTra.MaxLength = 0;
				colvarNgayHoanTra.AutoIncrement = false;
				colvarNgayHoanTra.IsNullable = true;
				colvarNgayHoanTra.IsPrimaryKey = false;
				colvarNgayHoanTra.IsForeignKey = false;
				colvarNgayHoanTra.IsReadOnly = false;
				colvarNgayHoanTra.DefaultSetting = @"";
				colvarNgayHoanTra.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayHoanTra);
				
				TableSchema.TableColumn colvarLaViTriHienTai = new TableSchema.TableColumn(schema);
				colvarLaViTriHienTai.ColumnName = "LaViTriHienTai";
				colvarLaViTriHienTai.DataType = DbType.Boolean;
				colvarLaViTriHienTai.MaxLength = 0;
				colvarLaViTriHienTai.AutoIncrement = false;
				colvarLaViTriHienTai.IsNullable = false;
				colvarLaViTriHienTai.IsPrimaryKey = false;
				colvarLaViTriHienTai.IsForeignKey = false;
				colvarLaViTriHienTai.IsReadOnly = false;
				
						colvarLaViTriHienTai.DefaultSetting = @"((1))";
				colvarLaViTriHienTai.ForeignKeyTableName = "";
				schema.Columns.Add(colvarLaViTriHienTai);
				
				TableSchema.TableColumn colvarGhiChu = new TableSchema.TableColumn(schema);
				colvarGhiChu.ColumnName = "GhiChu";
				colvarGhiChu.DataType = DbType.String;
				colvarGhiChu.MaxLength = 500;
				colvarGhiChu.AutoIncrement = false;
				colvarGhiChu.IsNullable = true;
				colvarGhiChu.IsPrimaryKey = false;
				colvarGhiChu.IsForeignKey = false;
				colvarGhiChu.IsReadOnly = false;
				colvarGhiChu.DefaultSetting = @"";
				colvarGhiChu.ForeignKeyTableName = "";
				schema.Columns.Add(colvarGhiChu);
				
				TableSchema.TableColumn colvarDaXoa = new TableSchema.TableColumn(schema);
				colvarDaXoa.ColumnName = "DaXoa";
				colvarDaXoa.DataType = DbType.Boolean;
				colvarDaXoa.MaxLength = 0;
				colvarDaXoa.AutoIncrement = false;
				colvarDaXoa.IsNullable = false;
				colvarDaXoa.IsPrimaryKey = false;
				colvarDaXoa.IsForeignKey = false;
				colvarDaXoa.IsReadOnly = false;
				
						colvarDaXoa.DefaultSetting = @"((0))";
				colvarDaXoa.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDaXoa);
				
				TableSchema.TableColumn colvarNguoiTao = new TableSchema.TableColumn(schema);
				colvarNguoiTao.ColumnName = "NguoiTao";
				colvarNguoiTao.DataType = DbType.String;
				colvarNguoiTao.MaxLength = 150;
				colvarNguoiTao.AutoIncrement = false;
				colvarNguoiTao.IsNullable = false;
				colvarNguoiTao.IsPrimaryKey = false;
				colvarNguoiTao.IsForeignKey = false;
				colvarNguoiTao.IsReadOnly = false;
				colvarNguoiTao.DefaultSetting = @"";
				colvarNguoiTao.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNguoiTao);
				
				TableSchema.TableColumn colvarNgayTao = new TableSchema.TableColumn(schema);
				colvarNgayTao.ColumnName = "NgayTao";
				colvarNgayTao.DataType = DbType.DateTime;
				colvarNgayTao.MaxLength = 0;
				colvarNgayTao.AutoIncrement = false;
				colvarNgayTao.IsNullable = false;
				colvarNgayTao.IsPrimaryKey = false;
				colvarNgayTao.IsForeignKey = false;
				colvarNgayTao.IsReadOnly = false;
				
						colvarNgayTao.DefaultSetting = @"(getdate())";
				colvarNgayTao.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayTao);
				
				TableSchema.TableColumn colvarNguoiCapNhat = new TableSchema.TableColumn(schema);
				colvarNguoiCapNhat.ColumnName = "NguoiCapNhat";
				colvarNguoiCapNhat.DataType = DbType.String;
				colvarNguoiCapNhat.MaxLength = 150;
				colvarNguoiCapNhat.AutoIncrement = false;
				colvarNguoiCapNhat.IsNullable = true;
				colvarNguoiCapNhat.IsPrimaryKey = false;
				colvarNguoiCapNhat.IsForeignKey = false;
				colvarNguoiCapNhat.IsReadOnly = false;
				colvarNguoiCapNhat.DefaultSetting = @"";
				colvarNguoiCapNhat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNguoiCapNhat);
				
				TableSchema.TableColumn colvarNgayCapNhat = new TableSchema.TableColumn(schema);
				colvarNgayCapNhat.ColumnName = "NgayCapNhat";
				colvarNgayCapNhat.DataType = DbType.DateTime;
				colvarNgayCapNhat.MaxLength = 0;
				colvarNgayCapNhat.AutoIncrement = false;
				colvarNgayCapNhat.IsNullable = true;
				colvarNgayCapNhat.IsPrimaryKey = false;
				colvarNgayCapNhat.IsForeignKey = false;
				colvarNgayCapNhat.IsReadOnly = false;
				colvarNgayCapNhat.DefaultSetting = @"";
				colvarNgayCapNhat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayCapNhat);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAccessProvider"].AddSchema("TblLuuTruVatLy",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("IdLuuTruVatLy")]
		[Bindable(true)]
		public Guid IdLuuTruVatLy 
		{
			get { return GetColumnValue<Guid>(Columns.IdLuuTruVatLy); }
			set { SetColumnValue(Columns.IdLuuTruVatLy, value); }
		}
		  
		[XmlAttribute("IdTaiLieu")]
		[Bindable(true)]
		public Guid IdTaiLieu 
		{
			get { return GetColumnValue<Guid>(Columns.IdTaiLieu); }
			set { SetColumnValue(Columns.IdTaiLieu, value); }
		}
		  
		[XmlAttribute("IdNoiLuuTru")]
		[Bindable(true)]
		public Guid IdNoiLuuTru 
		{
			get { return GetColumnValue<Guid>(Columns.IdNoiLuuTru); }
			set { SetColumnValue(Columns.IdNoiLuuTru, value); }
		}
		  
		[XmlAttribute("IdNguoiThucHien")]
		[Bindable(true)]
		public Guid IdNguoiThucHien 
		{
			get { return GetColumnValue<Guid>(Columns.IdNguoiThucHien); }
			set { SetColumnValue(Columns.IdNguoiThucHien, value); }
		}
		  
		[XmlAttribute("MaLuuTru")]
		[Bindable(true)]
		public string MaLuuTru 
		{
			get { return GetColumnValue<string>(Columns.MaLuuTru); }
			set { SetColumnValue(Columns.MaLuuTru, value); }
		}
		  
		[XmlAttribute("TrangThaiLuuTru")]
		[Bindable(true)]
		public string TrangThaiLuuTru 
		{
			get { return GetColumnValue<string>(Columns.TrangThaiLuuTru); }
			set { SetColumnValue(Columns.TrangThaiLuuTru, value); }
		}
		  
		[XmlAttribute("TinhTrangBanGoc")]
		[Bindable(true)]
		public string TinhTrangBanGoc 
		{
			get { return GetColumnValue<string>(Columns.TinhTrangBanGoc); }
			set { SetColumnValue(Columns.TinhTrangBanGoc, value); }
		}
		  
		[XmlAttribute("NgayLuu")]
		[Bindable(true)]
		public DateTime NgayLuu 
		{
			get { return GetColumnValue<DateTime>(Columns.NgayLuu); }
			set { SetColumnValue(Columns.NgayLuu, value); }
		}
		  
		[XmlAttribute("NgayLayRa")]
		[Bindable(true)]
		public DateTime? NgayLayRa 
		{
			get { return GetColumnValue<DateTime?>(Columns.NgayLayRa); }
			set { SetColumnValue(Columns.NgayLayRa, value); }
		}
		  
		[XmlAttribute("NgayHoanTra")]
		[Bindable(true)]
		public DateTime? NgayHoanTra 
		{
			get { return GetColumnValue<DateTime?>(Columns.NgayHoanTra); }
			set { SetColumnValue(Columns.NgayHoanTra, value); }
		}
		  
		[XmlAttribute("LaViTriHienTai")]
		[Bindable(true)]
		public bool LaViTriHienTai 
		{
			get { return GetColumnValue<bool>(Columns.LaViTriHienTai); }
			set { SetColumnValue(Columns.LaViTriHienTai, value); }
		}
		  
		[XmlAttribute("GhiChu")]
		[Bindable(true)]
		public string GhiChu 
		{
			get { return GetColumnValue<string>(Columns.GhiChu); }
			set { SetColumnValue(Columns.GhiChu, value); }
		}
		  
		[XmlAttribute("DaXoa")]
		[Bindable(true)]
		public bool DaXoa 
		{
			get { return GetColumnValue<bool>(Columns.DaXoa); }
			set { SetColumnValue(Columns.DaXoa, value); }
		}
		  
		[XmlAttribute("NguoiTao")]
		[Bindable(true)]
		public string NguoiTao 
		{
			get { return GetColumnValue<string>(Columns.NguoiTao); }
			set { SetColumnValue(Columns.NguoiTao, value); }
		}
		  
		[XmlAttribute("NgayTao")]
		[Bindable(true)]
		public DateTime NgayTao 
		{
			get { return GetColumnValue<DateTime>(Columns.NgayTao); }
			set { SetColumnValue(Columns.NgayTao, value); }
		}
		  
		[XmlAttribute("NguoiCapNhat")]
		[Bindable(true)]
		public string NguoiCapNhat 
		{
			get { return GetColumnValue<string>(Columns.NguoiCapNhat); }
			set { SetColumnValue(Columns.NguoiCapNhat, value); }
		}
		  
		[XmlAttribute("NgayCapNhat")]
		[Bindable(true)]
		public DateTime? NgayCapNhat 
		{
			get { return GetColumnValue<DateTime?>(Columns.NgayCapNhat); }
			set { SetColumnValue(Columns.NgayCapNhat, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a TblNhanVien ActiveRecord object related to this TblLuuTruVatLy
		/// 
		/// </summary>
		public SweetSoft.QLDA.DataAccess.TblNhanVien TblNhanVien
		{
			get { return SweetSoft.QLDA.DataAccess.TblNhanVien.FetchByID(this.IdNguoiThucHien); }
			set { SetColumnValue("IdNguoiThucHien", value.IdNhanVien); }
		}
		
		
		/// <summary>
		/// Returns a TblNoiLuuTru ActiveRecord object related to this TblLuuTruVatLy
		/// 
		/// </summary>
		public SweetSoft.QLDA.DataAccess.TblNoiLuuTru TblNoiLuuTru
		{
			get { return SweetSoft.QLDA.DataAccess.TblNoiLuuTru.FetchByID(this.IdNoiLuuTru); }
			set { SetColumnValue("IdNoiLuuTru", value.IdNoiLuuTru); }
		}
		
		
		/// <summary>
		/// Returns a TblTaiLieu ActiveRecord object related to this TblLuuTruVatLy
		/// 
		/// </summary>
		public SweetSoft.QLDA.DataAccess.TblTaiLieu TblTaiLieu
		{
			get { return SweetSoft.QLDA.DataAccess.TblTaiLieu.FetchByID(this.IdTaiLieu); }
			set { SetColumnValue("IdTaiLieu", value.IdTaiLieu); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varIdLuuTruVatLy,Guid varIdTaiLieu,Guid varIdNoiLuuTru,Guid varIdNguoiThucHien,string varMaLuuTru,string varTrangThaiLuuTru,string varTinhTrangBanGoc,DateTime varNgayLuu,DateTime? varNgayLayRa,DateTime? varNgayHoanTra,bool varLaViTriHienTai,string varGhiChu,bool varDaXoa,string varNguoiTao,DateTime varNgayTao,string varNguoiCapNhat,DateTime? varNgayCapNhat)
		{
			TblLuuTruVatLy item = new TblLuuTruVatLy();
			
			item.IdLuuTruVatLy = varIdLuuTruVatLy;
			
			item.IdTaiLieu = varIdTaiLieu;
			
			item.IdNoiLuuTru = varIdNoiLuuTru;
			
			item.IdNguoiThucHien = varIdNguoiThucHien;
			
			item.MaLuuTru = varMaLuuTru;
			
			item.TrangThaiLuuTru = varTrangThaiLuuTru;
			
			item.TinhTrangBanGoc = varTinhTrangBanGoc;
			
			item.NgayLuu = varNgayLuu;
			
			item.NgayLayRa = varNgayLayRa;
			
			item.NgayHoanTra = varNgayHoanTra;
			
			item.LaViTriHienTai = varLaViTriHienTai;
			
			item.GhiChu = varGhiChu;
			
			item.DaXoa = varDaXoa;
			
			item.NguoiTao = varNguoiTao;
			
			item.NgayTao = varNgayTao;
			
			item.NguoiCapNhat = varNguoiCapNhat;
			
			item.NgayCapNhat = varNgayCapNhat;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varIdLuuTruVatLy,Guid varIdTaiLieu,Guid varIdNoiLuuTru,Guid varIdNguoiThucHien,string varMaLuuTru,string varTrangThaiLuuTru,string varTinhTrangBanGoc,DateTime varNgayLuu,DateTime? varNgayLayRa,DateTime? varNgayHoanTra,bool varLaViTriHienTai,string varGhiChu,bool varDaXoa,string varNguoiTao,DateTime varNgayTao,string varNguoiCapNhat,DateTime? varNgayCapNhat)
		{
			TblLuuTruVatLy item = new TblLuuTruVatLy();
			
				item.IdLuuTruVatLy = varIdLuuTruVatLy;
			
				item.IdTaiLieu = varIdTaiLieu;
			
				item.IdNoiLuuTru = varIdNoiLuuTru;
			
				item.IdNguoiThucHien = varIdNguoiThucHien;
			
				item.MaLuuTru = varMaLuuTru;
			
				item.TrangThaiLuuTru = varTrangThaiLuuTru;
			
				item.TinhTrangBanGoc = varTinhTrangBanGoc;
			
				item.NgayLuu = varNgayLuu;
			
				item.NgayLayRa = varNgayLayRa;
			
				item.NgayHoanTra = varNgayHoanTra;
			
				item.LaViTriHienTai = varLaViTriHienTai;
			
				item.GhiChu = varGhiChu;
			
				item.DaXoa = varDaXoa;
			
				item.NguoiTao = varNguoiTao;
			
				item.NgayTao = varNgayTao;
			
				item.NguoiCapNhat = varNguoiCapNhat;
			
				item.NgayCapNhat = varNgayCapNhat;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdLuuTruVatLyColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn IdTaiLieuColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn IdNoiLuuTruColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn IdNguoiThucHienColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn MaLuuTruColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn TrangThaiLuuTruColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn TinhTrangBanGocColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayLuuColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayLayRaColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayHoanTraColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn LaViTriHienTaiColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        public static TableSchema.TableColumn GhiChuColumn
        {
            get { return Schema.Columns[11]; }
        }
        
        
        
        public static TableSchema.TableColumn DaXoaColumn
        {
            get { return Schema.Columns[12]; }
        }
        
        
        
        public static TableSchema.TableColumn NguoiTaoColumn
        {
            get { return Schema.Columns[13]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayTaoColumn
        {
            get { return Schema.Columns[14]; }
        }
        
        
        
        public static TableSchema.TableColumn NguoiCapNhatColumn
        {
            get { return Schema.Columns[15]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayCapNhatColumn
        {
            get { return Schema.Columns[16]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string IdLuuTruVatLy = @"IdLuuTruVatLy";
			 public static string IdTaiLieu = @"IdTaiLieu";
			 public static string IdNoiLuuTru = @"IdNoiLuuTru";
			 public static string IdNguoiThucHien = @"IdNguoiThucHien";
			 public static string MaLuuTru = @"MaLuuTru";
			 public static string TrangThaiLuuTru = @"TrangThaiLuuTru";
			 public static string TinhTrangBanGoc = @"TinhTrangBanGoc";
			 public static string NgayLuu = @"NgayLuu";
			 public static string NgayLayRa = @"NgayLayRa";
			 public static string NgayHoanTra = @"NgayHoanTra";
			 public static string LaViTriHienTai = @"LaViTriHienTai";
			 public static string GhiChu = @"GhiChu";
			 public static string DaXoa = @"DaXoa";
			 public static string NguoiTao = @"NguoiTao";
			 public static string NgayTao = @"NgayTao";
			 public static string NguoiCapNhat = @"NguoiCapNhat";
			 public static string NgayCapNhat = @"NgayCapNhat";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
