using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    /// <summary>
    /// Controller class for TblUploadFile
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblUploadFileController
    {
        // Preload our schema..
        TblUploadFile thisSchemaLoad = new TblUploadFile();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblUploadFileCollection FetchAll()
        {
            TblUploadFileCollection coll = new TblUploadFileCollection();
            Query qry = new Query(TblUploadFile.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblUploadFileCollection FetchByID(object Id)
        {
            TblUploadFileCollection coll = new TblUploadFileCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblUploadFileCollection FetchByQuery(Query qry)
        {
            TblUploadFileCollection coll = new TblUploadFileCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblUploadFile.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblUploadFile.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid Id,Guid OwnerId,DateTime CreatedDate,bool IsDeleted,string Name,string FileUrl,string FileType,string Ext,Guid RefId,string RefType,int DisplayOrder,int FileSize,string MimeType,string OriginalFileName,bool IsHost,bool IsSecretary,bool IsParticipant)
	    {
		    TblUploadFile item = new TblUploadFile();
		    
            item.Id = Id;
            
            item.OwnerId = OwnerId;
            
            item.CreatedDate = CreatedDate;
            
            item.IsDeleted = IsDeleted;
            
            item.Name = Name;
            
            item.FileUrl = FileUrl;
            
            item.FileType = FileType;
            
            item.Ext = Ext;
            
            item.RefId = RefId;
            
            item.RefType = RefType;
            
            item.DisplayOrder = DisplayOrder;
            
            item.FileSize = FileSize;
            
            item.MimeType = MimeType;
            
            item.OriginalFileName = OriginalFileName;
            
            item.IsHost = IsHost;
            
            item.IsSecretary = IsSecretary;
            
            item.IsParticipant = IsParticipant;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid Id,Guid OwnerId,DateTime CreatedDate,bool IsDeleted,string Name,string FileUrl,string FileType,string Ext,Guid RefId,string RefType,int DisplayOrder,int FileSize,string MimeType,string OriginalFileName,bool IsHost,bool IsSecretary,bool IsParticipant)
	    {
		    TblUploadFile item = new TblUploadFile();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.OwnerId = OwnerId;
				
			item.CreatedDate = CreatedDate;
				
			item.IsDeleted = IsDeleted;
				
			item.Name = Name;
				
			item.FileUrl = FileUrl;
				
			item.FileType = FileType;
				
			item.Ext = Ext;
				
			item.RefId = RefId;
				
			item.RefType = RefType;
				
			item.DisplayOrder = DisplayOrder;
				
			item.FileSize = FileSize;
				
			item.MimeType = MimeType;
				
			item.OriginalFileName = OriginalFileName;
				
			item.IsHost = IsHost;
				
			item.IsSecretary = IsSecretary;
				
			item.IsParticipant = IsParticipant;
				
	        item.Save(UserName);
	    }
    }
}
