using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblChiPhi class.
	/// </summary>
    [Serializable]
	public partial class TblChiPhiCollection : ActiveList<TblChiPhi, TblChiPhiCollection>
	{	   
		public TblChiPhiCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblChiPhiCollection</returns>
		public TblChiPhiCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblChiPhi o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblChiPhi table.
	/// </summary>
	[Serializable]
	public partial class TblChiPhi : ActiveRecord<TblChiPhi>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblChiPhi()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblChiPhi(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblChiPhi(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblChiPhi(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblChiPhi", TableType.Table, DataService.GetInstance("DataAccessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarIdChiPhi = new TableSchema.TableColumn(schema);
				colvarIdChiPhi.ColumnName = "IdChiPhi";
				colvarIdChiPhi.DataType = DbType.Guid;
				colvarIdChiPhi.MaxLength = 0;
				colvarIdChiPhi.AutoIncrement = false;
				colvarIdChiPhi.IsNullable = false;
				colvarIdChiPhi.IsPrimaryKey = true;
				colvarIdChiPhi.IsForeignKey = false;
				colvarIdChiPhi.IsReadOnly = false;
				
						colvarIdChiPhi.DefaultSetting = @"(newid())";
				colvarIdChiPhi.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIdChiPhi);
				
				TableSchema.TableColumn colvarIdDuAn = new TableSchema.TableColumn(schema);
				colvarIdDuAn.ColumnName = "IdDuAn";
				colvarIdDuAn.DataType = DbType.Guid;
				colvarIdDuAn.MaxLength = 0;
				colvarIdDuAn.AutoIncrement = false;
				colvarIdDuAn.IsNullable = false;
				colvarIdDuAn.IsPrimaryKey = false;
				colvarIdDuAn.IsForeignKey = true;
				colvarIdDuAn.IsReadOnly = false;
				colvarIdDuAn.DefaultSetting = @"";
				
					colvarIdDuAn.ForeignKeyTableName = "TblDuAn";
				schema.Columns.Add(colvarIdDuAn);
				
				TableSchema.TableColumn colvarIdCongViec = new TableSchema.TableColumn(schema);
				colvarIdCongViec.ColumnName = "IdCongViec";
				colvarIdCongViec.DataType = DbType.Guid;
				colvarIdCongViec.MaxLength = 0;
				colvarIdCongViec.AutoIncrement = false;
				colvarIdCongViec.IsNullable = true;
				colvarIdCongViec.IsPrimaryKey = false;
				colvarIdCongViec.IsForeignKey = true;
				colvarIdCongViec.IsReadOnly = false;
				colvarIdCongViec.DefaultSetting = @"";
				
					colvarIdCongViec.ForeignKeyTableName = "TblCongViec";
				schema.Columns.Add(colvarIdCongViec);
				
				TableSchema.TableColumn colvarIdNhanVienDeNghi = new TableSchema.TableColumn(schema);
				colvarIdNhanVienDeNghi.ColumnName = "IdNhanVienDeNghi";
				colvarIdNhanVienDeNghi.DataType = DbType.Guid;
				colvarIdNhanVienDeNghi.MaxLength = 0;
				colvarIdNhanVienDeNghi.AutoIncrement = false;
				colvarIdNhanVienDeNghi.IsNullable = true;
				colvarIdNhanVienDeNghi.IsPrimaryKey = false;
				colvarIdNhanVienDeNghi.IsForeignKey = true;
				colvarIdNhanVienDeNghi.IsReadOnly = false;
				colvarIdNhanVienDeNghi.DefaultSetting = @"";
				
					colvarIdNhanVienDeNghi.ForeignKeyTableName = "TblNhanVien";
				schema.Columns.Add(colvarIdNhanVienDeNghi);
				
				TableSchema.TableColumn colvarMaKhoanChi = new TableSchema.TableColumn(schema);
				colvarMaKhoanChi.ColumnName = "MaKhoanChi";
				colvarMaKhoanChi.DataType = DbType.AnsiString;
				colvarMaKhoanChi.MaxLength = 50;
				colvarMaKhoanChi.AutoIncrement = false;
				colvarMaKhoanChi.IsNullable = true;
				colvarMaKhoanChi.IsPrimaryKey = false;
				colvarMaKhoanChi.IsForeignKey = false;
				colvarMaKhoanChi.IsReadOnly = false;
				colvarMaKhoanChi.DefaultSetting = @"";
				colvarMaKhoanChi.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMaKhoanChi);
				
				TableSchema.TableColumn colvarTenKhoanChi = new TableSchema.TableColumn(schema);
				colvarTenKhoanChi.ColumnName = "TenKhoanChi";
				colvarTenKhoanChi.DataType = DbType.String;
				colvarTenKhoanChi.MaxLength = 255;
				colvarTenKhoanChi.AutoIncrement = false;
				colvarTenKhoanChi.IsNullable = false;
				colvarTenKhoanChi.IsPrimaryKey = false;
				colvarTenKhoanChi.IsForeignKey = false;
				colvarTenKhoanChi.IsReadOnly = false;
				colvarTenKhoanChi.DefaultSetting = @"";
				colvarTenKhoanChi.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTenKhoanChi);
				
				TableSchema.TableColumn colvarNgayPhatSinh = new TableSchema.TableColumn(schema);
				colvarNgayPhatSinh.ColumnName = "NgayPhatSinh";
				colvarNgayPhatSinh.DataType = DbType.DateTime;
				colvarNgayPhatSinh.MaxLength = 0;
				colvarNgayPhatSinh.AutoIncrement = false;
				colvarNgayPhatSinh.IsNullable = false;
				colvarNgayPhatSinh.IsPrimaryKey = false;
				colvarNgayPhatSinh.IsForeignKey = false;
				colvarNgayPhatSinh.IsReadOnly = false;
				colvarNgayPhatSinh.DefaultSetting = @"";
				colvarNgayPhatSinh.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayPhatSinh);
				
				TableSchema.TableColumn colvarSoTien = new TableSchema.TableColumn(schema);
				colvarSoTien.ColumnName = "SoTien";
				colvarSoTien.DataType = DbType.Decimal;
				colvarSoTien.MaxLength = 0;
				colvarSoTien.AutoIncrement = false;
				colvarSoTien.IsNullable = false;
				colvarSoTien.IsPrimaryKey = false;
				colvarSoTien.IsForeignKey = false;
				colvarSoTien.IsReadOnly = false;
				colvarSoTien.DefaultSetting = @"";
				colvarSoTien.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSoTien);
				
				TableSchema.TableColumn colvarMoTaChiTiet = new TableSchema.TableColumn(schema);
				colvarMoTaChiTiet.ColumnName = "MoTaChiTiet";
				colvarMoTaChiTiet.DataType = DbType.String;
				colvarMoTaChiTiet.MaxLength = -1;
				colvarMoTaChiTiet.AutoIncrement = false;
				colvarMoTaChiTiet.IsNullable = true;
				colvarMoTaChiTiet.IsPrimaryKey = false;
				colvarMoTaChiTiet.IsForeignKey = false;
				colvarMoTaChiTiet.IsReadOnly = false;
				colvarMoTaChiTiet.DefaultSetting = @"";
				colvarMoTaChiTiet.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMoTaChiTiet);
				
				TableSchema.TableColumn colvarTrangThai = new TableSchema.TableColumn(schema);
				colvarTrangThai.ColumnName = "TrangThai";
				colvarTrangThai.DataType = DbType.Byte;
				colvarTrangThai.MaxLength = 0;
				colvarTrangThai.AutoIncrement = false;
				colvarTrangThai.IsNullable = false;
				colvarTrangThai.IsPrimaryKey = false;
				colvarTrangThai.IsForeignKey = false;
				colvarTrangThai.IsReadOnly = false;
				
						colvarTrangThai.DefaultSetting = @"((0))";
				colvarTrangThai.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTrangThai);
				
				TableSchema.TableColumn colvarDaXoa = new TableSchema.TableColumn(schema);
				colvarDaXoa.ColumnName = "DaXoa";
				colvarDaXoa.DataType = DbType.Boolean;
				colvarDaXoa.MaxLength = 0;
				colvarDaXoa.AutoIncrement = false;
				colvarDaXoa.IsNullable = false;
				colvarDaXoa.IsPrimaryKey = false;
				colvarDaXoa.IsForeignKey = false;
				colvarDaXoa.IsReadOnly = false;
				
						colvarDaXoa.DefaultSetting = @"((0))";
				colvarDaXoa.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDaXoa);
				
				TableSchema.TableColumn colvarNguoiTao = new TableSchema.TableColumn(schema);
				colvarNguoiTao.ColumnName = "NguoiTao";
				colvarNguoiTao.DataType = DbType.String;
				colvarNguoiTao.MaxLength = 150;
				colvarNguoiTao.AutoIncrement = false;
				colvarNguoiTao.IsNullable = false;
				colvarNguoiTao.IsPrimaryKey = false;
				colvarNguoiTao.IsForeignKey = false;
				colvarNguoiTao.IsReadOnly = false;
				colvarNguoiTao.DefaultSetting = @"";
				colvarNguoiTao.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNguoiTao);
				
				TableSchema.TableColumn colvarNgayTao = new TableSchema.TableColumn(schema);
				colvarNgayTao.ColumnName = "NgayTao";
				colvarNgayTao.DataType = DbType.DateTime;
				colvarNgayTao.MaxLength = 0;
				colvarNgayTao.AutoIncrement = false;
				colvarNgayTao.IsNullable = false;
				colvarNgayTao.IsPrimaryKey = false;
				colvarNgayTao.IsForeignKey = false;
				colvarNgayTao.IsReadOnly = false;
				
						colvarNgayTao.DefaultSetting = @"(getdate())";
				colvarNgayTao.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayTao);
				
				TableSchema.TableColumn colvarNguoiCapNhat = new TableSchema.TableColumn(schema);
				colvarNguoiCapNhat.ColumnName = "NguoiCapNhat";
				colvarNguoiCapNhat.DataType = DbType.String;
				colvarNguoiCapNhat.MaxLength = 150;
				colvarNguoiCapNhat.AutoIncrement = false;
				colvarNguoiCapNhat.IsNullable = true;
				colvarNguoiCapNhat.IsPrimaryKey = false;
				colvarNguoiCapNhat.IsForeignKey = false;
				colvarNguoiCapNhat.IsReadOnly = false;
				colvarNguoiCapNhat.DefaultSetting = @"";
				colvarNguoiCapNhat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNguoiCapNhat);
				
				TableSchema.TableColumn colvarNgayCapNhat = new TableSchema.TableColumn(schema);
				colvarNgayCapNhat.ColumnName = "NgayCapNhat";
				colvarNgayCapNhat.DataType = DbType.DateTime;
				colvarNgayCapNhat.MaxLength = 0;
				colvarNgayCapNhat.AutoIncrement = false;
				colvarNgayCapNhat.IsNullable = true;
				colvarNgayCapNhat.IsPrimaryKey = false;
				colvarNgayCapNhat.IsForeignKey = false;
				colvarNgayCapNhat.IsReadOnly = false;
				colvarNgayCapNhat.DefaultSetting = @"";
				colvarNgayCapNhat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayCapNhat);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAccessProvider"].AddSchema("TblChiPhi",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("IdChiPhi")]
		[Bindable(true)]
		public Guid IdChiPhi 
		{
			get { return GetColumnValue<Guid>(Columns.IdChiPhi); }
			set { SetColumnValue(Columns.IdChiPhi, value); }
		}
		  
		[XmlAttribute("IdDuAn")]
		[Bindable(true)]
		public Guid IdDuAn 
		{
			get { return GetColumnValue<Guid>(Columns.IdDuAn); }
			set { SetColumnValue(Columns.IdDuAn, value); }
		}
		  
		[XmlAttribute("IdCongViec")]
		[Bindable(true)]
		public Guid? IdCongViec 
		{
			get { return GetColumnValue<Guid?>(Columns.IdCongViec); }
			set { SetColumnValue(Columns.IdCongViec, value); }
		}
		  
		[XmlAttribute("IdNhanVienDeNghi")]
		[Bindable(true)]
		public Guid? IdNhanVienDeNghi 
		{
			get { return GetColumnValue<Guid?>(Columns.IdNhanVienDeNghi); }
			set { SetColumnValue(Columns.IdNhanVienDeNghi, value); }
		}
		  
		[XmlAttribute("MaKhoanChi")]
		[Bindable(true)]
		public string MaKhoanChi 
		{
			get { return GetColumnValue<string>(Columns.MaKhoanChi); }
			set { SetColumnValue(Columns.MaKhoanChi, value); }
		}
		  
		[XmlAttribute("TenKhoanChi")]
		[Bindable(true)]
		public string TenKhoanChi 
		{
			get { return GetColumnValue<string>(Columns.TenKhoanChi); }
			set { SetColumnValue(Columns.TenKhoanChi, value); }
		}
		  
		[XmlAttribute("NgayPhatSinh")]
		[Bindable(true)]
		public DateTime NgayPhatSinh 
		{
			get { return GetColumnValue<DateTime>(Columns.NgayPhatSinh); }
			set { SetColumnValue(Columns.NgayPhatSinh, value); }
		}
		  
		[XmlAttribute("SoTien")]
		[Bindable(true)]
		public decimal SoTien 
		{
			get { return GetColumnValue<decimal>(Columns.SoTien); }
			set { SetColumnValue(Columns.SoTien, value); }
		}
		  
		[XmlAttribute("MoTaChiTiet")]
		[Bindable(true)]
		public string MoTaChiTiet 
		{
			get { return GetColumnValue<string>(Columns.MoTaChiTiet); }
			set { SetColumnValue(Columns.MoTaChiTiet, value); }
		}
		  
		[XmlAttribute("TrangThai")]
		[Bindable(true)]
		public byte TrangThai 
		{
			get { return GetColumnValue<byte>(Columns.TrangThai); }
			set { SetColumnValue(Columns.TrangThai, value); }
		}
		  
		[XmlAttribute("DaXoa")]
		[Bindable(true)]
		public bool DaXoa 
		{
			get { return GetColumnValue<bool>(Columns.DaXoa); }
			set { SetColumnValue(Columns.DaXoa, value); }
		}
		  
		[XmlAttribute("NguoiTao")]
		[Bindable(true)]
		public string NguoiTao 
		{
			get { return GetColumnValue<string>(Columns.NguoiTao); }
			set { SetColumnValue(Columns.NguoiTao, value); }
		}
		  
		[XmlAttribute("NgayTao")]
		[Bindable(true)]
		public DateTime NgayTao 
		{
			get { return GetColumnValue<DateTime>(Columns.NgayTao); }
			set { SetColumnValue(Columns.NgayTao, value); }
		}
		  
		[XmlAttribute("NguoiCapNhat")]
		[Bindable(true)]
		public string NguoiCapNhat 
		{
			get { return GetColumnValue<string>(Columns.NguoiCapNhat); }
			set { SetColumnValue(Columns.NguoiCapNhat, value); }
		}
		  
		[XmlAttribute("NgayCapNhat")]
		[Bindable(true)]
		public DateTime? NgayCapNhat 
		{
			get { return GetColumnValue<DateTime?>(Columns.NgayCapNhat); }
			set { SetColumnValue(Columns.NgayCapNhat, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a TblCongViec ActiveRecord object related to this TblChiPhi
		/// 
		/// </summary>
		public SweetSoft.QLDA.DataAccess.TblCongViec TblCongViec
		{
			get { return SweetSoft.QLDA.DataAccess.TblCongViec.FetchByID(this.IdCongViec); }
			set { SetColumnValue("IdCongViec", value.IdCongViec); }
		}
		
		
		/// <summary>
		/// Returns a TblDuAn ActiveRecord object related to this TblChiPhi
		/// 
		/// </summary>
		public SweetSoft.QLDA.DataAccess.TblDuAn TblDuAn
		{
			get { return SweetSoft.QLDA.DataAccess.TblDuAn.FetchByID(this.IdDuAn); }
			set { SetColumnValue("IdDuAn", value.IdDuAn); }
		}
		
		
		/// <summary>
		/// Returns a TblNhanVien ActiveRecord object related to this TblChiPhi
		/// 
		/// </summary>
		public SweetSoft.QLDA.DataAccess.TblNhanVien TblNhanVien
		{
			get { return SweetSoft.QLDA.DataAccess.TblNhanVien.FetchByID(this.IdNhanVienDeNghi); }
			set { SetColumnValue("IdNhanVienDeNghi", value.IdNhanVien); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varIdChiPhi,Guid varIdDuAn,Guid? varIdCongViec,Guid? varIdNhanVienDeNghi,string varMaKhoanChi,string varTenKhoanChi,DateTime varNgayPhatSinh,decimal varSoTien,string varMoTaChiTiet,byte varTrangThai,bool varDaXoa,string varNguoiTao,DateTime varNgayTao,string varNguoiCapNhat,DateTime? varNgayCapNhat)
		{
			TblChiPhi item = new TblChiPhi();
			
			item.IdChiPhi = varIdChiPhi;
			
			item.IdDuAn = varIdDuAn;
			
			item.IdCongViec = varIdCongViec;
			
			item.IdNhanVienDeNghi = varIdNhanVienDeNghi;
			
			item.MaKhoanChi = varMaKhoanChi;
			
			item.TenKhoanChi = varTenKhoanChi;
			
			item.NgayPhatSinh = varNgayPhatSinh;
			
			item.SoTien = varSoTien;
			
			item.MoTaChiTiet = varMoTaChiTiet;
			
			item.TrangThai = varTrangThai;
			
			item.DaXoa = varDaXoa;
			
			item.NguoiTao = varNguoiTao;
			
			item.NgayTao = varNgayTao;
			
			item.NguoiCapNhat = varNguoiCapNhat;
			
			item.NgayCapNhat = varNgayCapNhat;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varIdChiPhi,Guid varIdDuAn,Guid? varIdCongViec,Guid? varIdNhanVienDeNghi,string varMaKhoanChi,string varTenKhoanChi,DateTime varNgayPhatSinh,decimal varSoTien,string varMoTaChiTiet,byte varTrangThai,bool varDaXoa,string varNguoiTao,DateTime varNgayTao,string varNguoiCapNhat,DateTime? varNgayCapNhat)
		{
			TblChiPhi item = new TblChiPhi();
			
				item.IdChiPhi = varIdChiPhi;
			
				item.IdDuAn = varIdDuAn;
			
				item.IdCongViec = varIdCongViec;
			
				item.IdNhanVienDeNghi = varIdNhanVienDeNghi;
			
				item.MaKhoanChi = varMaKhoanChi;
			
				item.TenKhoanChi = varTenKhoanChi;
			
				item.NgayPhatSinh = varNgayPhatSinh;
			
				item.SoTien = varSoTien;
			
				item.MoTaChiTiet = varMoTaChiTiet;
			
				item.TrangThai = varTrangThai;
			
				item.DaXoa = varDaXoa;
			
				item.NguoiTao = varNguoiTao;
			
				item.NgayTao = varNgayTao;
			
				item.NguoiCapNhat = varNguoiCapNhat;
			
				item.NgayCapNhat = varNgayCapNhat;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdChiPhiColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn IdDuAnColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn IdCongViecColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn IdNhanVienDeNghiColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn MaKhoanChiColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn TenKhoanChiColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayPhatSinhColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn SoTienColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn MoTaChiTietColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn TrangThaiColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn DaXoaColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        public static TableSchema.TableColumn NguoiTaoColumn
        {
            get { return Schema.Columns[11]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayTaoColumn
        {
            get { return Schema.Columns[12]; }
        }
        
        
        
        public static TableSchema.TableColumn NguoiCapNhatColumn
        {
            get { return Schema.Columns[13]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayCapNhatColumn
        {
            get { return Schema.Columns[14]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string IdChiPhi = @"IdChiPhi";
			 public static string IdDuAn = @"IdDuAn";
			 public static string IdCongViec = @"IdCongViec";
			 public static string IdNhanVienDeNghi = @"IdNhanVienDeNghi";
			 public static string MaKhoanChi = @"MaKhoanChi";
			 public static string TenKhoanChi = @"TenKhoanChi";
			 public static string NgayPhatSinh = @"NgayPhatSinh";
			 public static string SoTien = @"SoTien";
			 public static string MoTaChiTiet = @"MoTaChiTiet";
			 public static string TrangThai = @"TrangThai";
			 public static string DaXoa = @"DaXoa";
			 public static string NguoiTao = @"NguoiTao";
			 public static string NgayTao = @"NgayTao";
			 public static string NguoiCapNhat = @"NguoiCapNhat";
			 public static string NgayCapNhat = @"NgayCapNhat";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
