using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblEmailTemplate class.
	/// </summary>
    [Serializable]
	public partial class TblEmailTemplateCollection : ActiveList<TblEmailTemplate, TblEmailTemplateCollection>
	{	   
		public TblEmailTemplateCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblEmailTemplateCollection</returns>
		public TblEmailTemplateCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblEmailTemplate o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblEmailTemplate table.
	/// </summary>
	[Serializable]
	public partial class TblEmailTemplate : ActiveRecord<TblEmailTemplate>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblEmailTemplate()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblEmailTemplate(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblEmailTemplate(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblEmailTemplate(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblEmailTemplate", TableType.Table, DataService.GetInstance("DataAccessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "Id";
				colvarId.DataType = DbType.Guid;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = false;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				
						colvarId.DefaultSetting = @"(newid())";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarCreatedUser = new TableSchema.TableColumn(schema);
				colvarCreatedUser.ColumnName = "CreatedUser";
				colvarCreatedUser.DataType = DbType.String;
				colvarCreatedUser.MaxLength = 150;
				colvarCreatedUser.AutoIncrement = false;
				colvarCreatedUser.IsNullable = false;
				colvarCreatedUser.IsPrimaryKey = false;
				colvarCreatedUser.IsForeignKey = false;
				colvarCreatedUser.IsReadOnly = false;
				colvarCreatedUser.DefaultSetting = @"";
				colvarCreatedUser.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCreatedUser);
				
				TableSchema.TableColumn colvarCreatedDate = new TableSchema.TableColumn(schema);
				colvarCreatedDate.ColumnName = "CreatedDate";
				colvarCreatedDate.DataType = DbType.DateTime;
				colvarCreatedDate.MaxLength = 0;
				colvarCreatedDate.AutoIncrement = false;
				colvarCreatedDate.IsNullable = false;
				colvarCreatedDate.IsPrimaryKey = false;
				colvarCreatedDate.IsForeignKey = false;
				colvarCreatedDate.IsReadOnly = false;
				
						colvarCreatedDate.DefaultSetting = @"(getdate())";
				colvarCreatedDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCreatedDate);
				
				TableSchema.TableColumn colvarUpdatedUser = new TableSchema.TableColumn(schema);
				colvarUpdatedUser.ColumnName = "UpdatedUser";
				colvarUpdatedUser.DataType = DbType.String;
				colvarUpdatedUser.MaxLength = 150;
				colvarUpdatedUser.AutoIncrement = false;
				colvarUpdatedUser.IsNullable = false;
				colvarUpdatedUser.IsPrimaryKey = false;
				colvarUpdatedUser.IsForeignKey = false;
				colvarUpdatedUser.IsReadOnly = false;
				colvarUpdatedUser.DefaultSetting = @"";
				colvarUpdatedUser.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUpdatedUser);
				
				TableSchema.TableColumn colvarUpdatedDate = new TableSchema.TableColumn(schema);
				colvarUpdatedDate.ColumnName = "UpdatedDate";
				colvarUpdatedDate.DataType = DbType.DateTime;
				colvarUpdatedDate.MaxLength = 0;
				colvarUpdatedDate.AutoIncrement = false;
				colvarUpdatedDate.IsNullable = false;
				colvarUpdatedDate.IsPrimaryKey = false;
				colvarUpdatedDate.IsForeignKey = false;
				colvarUpdatedDate.IsReadOnly = false;
				
						colvarUpdatedDate.DefaultSetting = @"(getdate())";
				colvarUpdatedDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUpdatedDate);
				
				TableSchema.TableColumn colvarIsDeleted = new TableSchema.TableColumn(schema);
				colvarIsDeleted.ColumnName = "IsDeleted";
				colvarIsDeleted.DataType = DbType.Boolean;
				colvarIsDeleted.MaxLength = 0;
				colvarIsDeleted.AutoIncrement = false;
				colvarIsDeleted.IsNullable = false;
				colvarIsDeleted.IsPrimaryKey = false;
				colvarIsDeleted.IsForeignKey = false;
				colvarIsDeleted.IsReadOnly = false;
				
						colvarIsDeleted.DefaultSetting = @"((0))";
				colvarIsDeleted.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIsDeleted);
				
				TableSchema.TableColumn colvarIsActivated = new TableSchema.TableColumn(schema);
				colvarIsActivated.ColumnName = "IsActivated";
				colvarIsActivated.DataType = DbType.Boolean;
				colvarIsActivated.MaxLength = 0;
				colvarIsActivated.AutoIncrement = false;
				colvarIsActivated.IsNullable = false;
				colvarIsActivated.IsPrimaryKey = false;
				colvarIsActivated.IsForeignKey = false;
				colvarIsActivated.IsReadOnly = false;
				
						colvarIsActivated.DefaultSetting = @"((0))";
				colvarIsActivated.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIsActivated);
				
				TableSchema.TableColumn colvarName = new TableSchema.TableColumn(schema);
				colvarName.ColumnName = "Name";
				colvarName.DataType = DbType.String;
				colvarName.MaxLength = 250;
				colvarName.AutoIncrement = false;
				colvarName.IsNullable = false;
				colvarName.IsPrimaryKey = false;
				colvarName.IsForeignKey = false;
				colvarName.IsReadOnly = false;
				
						colvarName.DefaultSetting = @"('')";
				colvarName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarName);
				
				TableSchema.TableColumn colvarSubject = new TableSchema.TableColumn(schema);
				colvarSubject.ColumnName = "Subject";
				colvarSubject.DataType = DbType.String;
				colvarSubject.MaxLength = 255;
				colvarSubject.AutoIncrement = false;
				colvarSubject.IsNullable = false;
				colvarSubject.IsPrimaryKey = false;
				colvarSubject.IsForeignKey = false;
				colvarSubject.IsReadOnly = false;
				colvarSubject.DefaultSetting = @"";
				colvarSubject.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSubject);
				
				TableSchema.TableColumn colvarBody = new TableSchema.TableColumn(schema);
				colvarBody.ColumnName = "Body";
				colvarBody.DataType = DbType.String;
				colvarBody.MaxLength = -1;
				colvarBody.AutoIncrement = false;
				colvarBody.IsNullable = false;
				colvarBody.IsPrimaryKey = false;
				colvarBody.IsForeignKey = false;
				colvarBody.IsReadOnly = false;
				colvarBody.DefaultSetting = @"";
				colvarBody.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBody);
				
				TableSchema.TableColumn colvarCCEmail = new TableSchema.TableColumn(schema);
				colvarCCEmail.ColumnName = "CCEmail";
				colvarCCEmail.DataType = DbType.String;
				colvarCCEmail.MaxLength = 2000;
				colvarCCEmail.AutoIncrement = false;
				colvarCCEmail.IsNullable = false;
				colvarCCEmail.IsPrimaryKey = false;
				colvarCCEmail.IsForeignKey = false;
				colvarCCEmail.IsReadOnly = false;
				colvarCCEmail.DefaultSetting = @"";
				colvarCCEmail.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCCEmail);
				
				TableSchema.TableColumn colvarBCCEmail = new TableSchema.TableColumn(schema);
				colvarBCCEmail.ColumnName = "BCCEmail";
				colvarBCCEmail.DataType = DbType.String;
				colvarBCCEmail.MaxLength = 2000;
				colvarBCCEmail.AutoIncrement = false;
				colvarBCCEmail.IsNullable = false;
				colvarBCCEmail.IsPrimaryKey = false;
				colvarBCCEmail.IsForeignKey = false;
				colvarBCCEmail.IsReadOnly = false;
				colvarBCCEmail.DefaultSetting = @"";
				colvarBCCEmail.ForeignKeyTableName = "";
				schema.Columns.Add(colvarBCCEmail);
				
				TableSchema.TableColumn colvarTemplateKey = new TableSchema.TableColumn(schema);
				colvarTemplateKey.ColumnName = "TemplateKey";
				colvarTemplateKey.DataType = DbType.String;
				colvarTemplateKey.MaxLength = 150;
				colvarTemplateKey.AutoIncrement = false;
				colvarTemplateKey.IsNullable = false;
				colvarTemplateKey.IsPrimaryKey = false;
				colvarTemplateKey.IsForeignKey = false;
				colvarTemplateKey.IsReadOnly = false;
				colvarTemplateKey.DefaultSetting = @"";
				colvarTemplateKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTemplateKey);
				
				TableSchema.TableColumn colvarEmailType = new TableSchema.TableColumn(schema);
				colvarEmailType.ColumnName = "EmailType";
				colvarEmailType.DataType = DbType.Byte;
				colvarEmailType.MaxLength = 0;
				colvarEmailType.AutoIncrement = false;
				colvarEmailType.IsNullable = false;
				colvarEmailType.IsPrimaryKey = false;
				colvarEmailType.IsForeignKey = false;
				colvarEmailType.IsReadOnly = false;
				colvarEmailType.DefaultSetting = @"";
				colvarEmailType.ForeignKeyTableName = "";
				schema.Columns.Add(colvarEmailType);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAccessProvider"].AddSchema("TblEmailTemplate",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public Guid Id 
		{
			get { return GetColumnValue<Guid>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("CreatedUser")]
		[Bindable(true)]
		public string CreatedUser 
		{
			get { return GetColumnValue<string>(Columns.CreatedUser); }
			set { SetColumnValue(Columns.CreatedUser, value); }
		}
		  
		[XmlAttribute("CreatedDate")]
		[Bindable(true)]
		public DateTime CreatedDate 
		{
			get { return GetColumnValue<DateTime>(Columns.CreatedDate); }
			set { SetColumnValue(Columns.CreatedDate, value); }
		}
		  
		[XmlAttribute("UpdatedUser")]
		[Bindable(true)]
		public string UpdatedUser 
		{
			get { return GetColumnValue<string>(Columns.UpdatedUser); }
			set { SetColumnValue(Columns.UpdatedUser, value); }
		}
		  
		[XmlAttribute("UpdatedDate")]
		[Bindable(true)]
		public DateTime UpdatedDate 
		{
			get { return GetColumnValue<DateTime>(Columns.UpdatedDate); }
			set { SetColumnValue(Columns.UpdatedDate, value); }
		}
		  
		[XmlAttribute("IsDeleted")]
		[Bindable(true)]
		public bool IsDeleted 
		{
			get { return GetColumnValue<bool>(Columns.IsDeleted); }
			set { SetColumnValue(Columns.IsDeleted, value); }
		}
		  
		[XmlAttribute("IsActivated")]
		[Bindable(true)]
		public bool IsActivated 
		{
			get { return GetColumnValue<bool>(Columns.IsActivated); }
			set { SetColumnValue(Columns.IsActivated, value); }
		}
		  
		[XmlAttribute("Name")]
		[Bindable(true)]
		public string Name 
		{
			get { return GetColumnValue<string>(Columns.Name); }
			set { SetColumnValue(Columns.Name, value); }
		}
		  
		[XmlAttribute("Subject")]
		[Bindable(true)]
		public string Subject 
		{
			get { return GetColumnValue<string>(Columns.Subject); }
			set { SetColumnValue(Columns.Subject, value); }
		}
		  
		[XmlAttribute("Body")]
		[Bindable(true)]
		public string Body 
		{
			get { return GetColumnValue<string>(Columns.Body); }
			set { SetColumnValue(Columns.Body, value); }
		}
		  
		[XmlAttribute("CCEmail")]
		[Bindable(true)]
		public string CCEmail 
		{
			get { return GetColumnValue<string>(Columns.CCEmail); }
			set { SetColumnValue(Columns.CCEmail, value); }
		}
		  
		[XmlAttribute("BCCEmail")]
		[Bindable(true)]
		public string BCCEmail 
		{
			get { return GetColumnValue<string>(Columns.BCCEmail); }
			set { SetColumnValue(Columns.BCCEmail, value); }
		}
		  
		[XmlAttribute("TemplateKey")]
		[Bindable(true)]
		public string TemplateKey 
		{
			get { return GetColumnValue<string>(Columns.TemplateKey); }
			set { SetColumnValue(Columns.TemplateKey, value); }
		}
		  
		[XmlAttribute("EmailType")]
		[Bindable(true)]
		public byte EmailType 
		{
			get { return GetColumnValue<byte>(Columns.EmailType); }
			set { SetColumnValue(Columns.EmailType, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varId,string varCreatedUser,DateTime varCreatedDate,string varUpdatedUser,DateTime varUpdatedDate,bool varIsDeleted,bool varIsActivated,string varName,string varSubject,string varBody,string varCCEmail,string varBCCEmail,string varTemplateKey,byte varEmailType)
		{
			TblEmailTemplate item = new TblEmailTemplate();
			
			item.Id = varId;
			
			item.CreatedUser = varCreatedUser;
			
			item.CreatedDate = varCreatedDate;
			
			item.UpdatedUser = varUpdatedUser;
			
			item.UpdatedDate = varUpdatedDate;
			
			item.IsDeleted = varIsDeleted;
			
			item.IsActivated = varIsActivated;
			
			item.Name = varName;
			
			item.Subject = varSubject;
			
			item.Body = varBody;
			
			item.CCEmail = varCCEmail;
			
			item.BCCEmail = varBCCEmail;
			
			item.TemplateKey = varTemplateKey;
			
			item.EmailType = varEmailType;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varId,string varCreatedUser,DateTime varCreatedDate,string varUpdatedUser,DateTime varUpdatedDate,bool varIsDeleted,bool varIsActivated,string varName,string varSubject,string varBody,string varCCEmail,string varBCCEmail,string varTemplateKey,byte varEmailType)
		{
			TblEmailTemplate item = new TblEmailTemplate();
			
				item.Id = varId;
			
				item.CreatedUser = varCreatedUser;
			
				item.CreatedDate = varCreatedDate;
			
				item.UpdatedUser = varUpdatedUser;
			
				item.UpdatedDate = varUpdatedDate;
			
				item.IsDeleted = varIsDeleted;
			
				item.IsActivated = varIsActivated;
			
				item.Name = varName;
			
				item.Subject = varSubject;
			
				item.Body = varBody;
			
				item.CCEmail = varCCEmail;
			
				item.BCCEmail = varBCCEmail;
			
				item.TemplateKey = varTemplateKey;
			
				item.EmailType = varEmailType;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedUserColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn CreatedDateColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn UpdatedUserColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn UpdatedDateColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn IsDeletedColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn IsActivatedColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn NameColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn SubjectColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn BodyColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn CCEmailColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        public static TableSchema.TableColumn BCCEmailColumn
        {
            get { return Schema.Columns[11]; }
        }
        
        
        
        public static TableSchema.TableColumn TemplateKeyColumn
        {
            get { return Schema.Columns[12]; }
        }
        
        
        
        public static TableSchema.TableColumn EmailTypeColumn
        {
            get { return Schema.Columns[13]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"Id";
			 public static string CreatedUser = @"CreatedUser";
			 public static string CreatedDate = @"CreatedDate";
			 public static string UpdatedUser = @"UpdatedUser";
			 public static string UpdatedDate = @"UpdatedDate";
			 public static string IsDeleted = @"IsDeleted";
			 public static string IsActivated = @"IsActivated";
			 public static string Name = @"Name";
			 public static string Subject = @"Subject";
			 public static string Body = @"Body";
			 public static string CCEmail = @"CCEmail";
			 public static string BCCEmail = @"BCCEmail";
			 public static string TemplateKey = @"TemplateKey";
			 public static string EmailType = @"EmailType";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
