using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    /// <summary>
    /// Controller class for TblLichSuChinhSua
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblLichSuChinhSuaController
    {
        // Preload our schema..
        TblLichSuChinhSua thisSchemaLoad = new TblLichSuChinhSua();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblLichSuChinhSuaCollection FetchAll()
        {
            TblLichSuChinhSuaCollection coll = new TblLichSuChinhSuaCollection();
            Query qry = new Query(TblLichSuChinhSua.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblLichSuChinhSuaCollection FetchByID(object IdLichSuChinhSua)
        {
            TblLichSuChinhSuaCollection coll = new TblLichSuChinhSuaCollection().Where("IdLichSuChinhSua", IdLichSuChinhSua).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblLichSuChinhSuaCollection FetchByQuery(Query qry)
        {
            TblLichSuChinhSuaCollection coll = new TblLichSuChinhSuaCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdLichSuChinhSua)
        {
            return (TblLichSuChinhSua.Delete(IdLichSuChinhSua) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdLichSuChinhSua)
        {
            return (TblLichSuChinhSua.Destroy(IdLichSuChinhSua) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid IdLichSuChinhSua,Guid IdPhienBanTaiLieu,string NoiDungSnapshot,string MoTaThayDoi,Guid? IdNhanVienThucHien,string NguoiThucHien,bool LaMocThuCong,DateTime NgayTao)
	    {
		    TblLichSuChinhSua item = new TblLichSuChinhSua();
		    
            item.IdLichSuChinhSua = IdLichSuChinhSua;
            
            item.IdPhienBanTaiLieu = IdPhienBanTaiLieu;
            
            item.NoiDungSnapshot = NoiDungSnapshot;
            
            item.MoTaThayDoi = MoTaThayDoi;
            
            item.IdNhanVienThucHien = IdNhanVienThucHien;
            
            item.NguoiThucHien = NguoiThucHien;
            
            item.LaMocThuCong = LaMocThuCong;
            
            item.NgayTao = NgayTao;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid IdLichSuChinhSua,Guid IdPhienBanTaiLieu,string NoiDungSnapshot,string MoTaThayDoi,Guid? IdNhanVienThucHien,string NguoiThucHien,bool LaMocThuCong,DateTime NgayTao)
	    {
		    TblLichSuChinhSua item = new TblLichSuChinhSua();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.IdLichSuChinhSua = IdLichSuChinhSua;
				
			item.IdPhienBanTaiLieu = IdPhienBanTaiLieu;
				
			item.NoiDungSnapshot = NoiDungSnapshot;
				
			item.MoTaThayDoi = MoTaThayDoi;
				
			item.IdNhanVienThucHien = IdNhanVienThucHien;
				
			item.NguoiThucHien = NguoiThucHien;
				
			item.LaMocThuCong = LaMocThuCong;
				
			item.NgayTao = NgayTao;
				
	        item.Save(UserName);
	    }
    }
}
