using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblLoaiTaiLieu class.
	/// </summary>
    [Serializable]
	public partial class TblLoaiTaiLieuCollection : ActiveList<TblLoaiTaiLieu, TblLoaiTaiLieuCollection>
	{	   
		public TblLoaiTaiLieuCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblLoaiTaiLieuCollection</returns>
		public TblLoaiTaiLieuCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblLoaiTaiLieu o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblLoaiTaiLieu table.
	/// </summary>
	[Serializable]
	public partial class TblLoaiTaiLieu : ActiveRecord<TblLoaiTaiLieu>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblLoaiTaiLieu()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblLoaiTaiLieu(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblLoaiTaiLieu(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblLoaiTaiLieu(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblLoaiTaiLieu", TableType.Table, DataService.GetInstance("DataAccessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarIdLoaiTaiLieu = new TableSchema.TableColumn(schema);
				colvarIdLoaiTaiLieu.ColumnName = "IdLoaiTaiLieu";
				colvarIdLoaiTaiLieu.DataType = DbType.Guid;
				colvarIdLoaiTaiLieu.MaxLength = 0;
				colvarIdLoaiTaiLieu.AutoIncrement = false;
				colvarIdLoaiTaiLieu.IsNullable = false;
				colvarIdLoaiTaiLieu.IsPrimaryKey = true;
				colvarIdLoaiTaiLieu.IsForeignKey = false;
				colvarIdLoaiTaiLieu.IsReadOnly = false;
				
						colvarIdLoaiTaiLieu.DefaultSetting = @"(newid())";
				colvarIdLoaiTaiLieu.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIdLoaiTaiLieu);
				
				TableSchema.TableColumn colvarIdNhomTaiLieu = new TableSchema.TableColumn(schema);
				colvarIdNhomTaiLieu.ColumnName = "IdNhomTaiLieu";
				colvarIdNhomTaiLieu.DataType = DbType.Guid;
				colvarIdNhomTaiLieu.MaxLength = 0;
				colvarIdNhomTaiLieu.AutoIncrement = false;
				colvarIdNhomTaiLieu.IsNullable = false;
				colvarIdNhomTaiLieu.IsPrimaryKey = false;
				colvarIdNhomTaiLieu.IsForeignKey = true;
				colvarIdNhomTaiLieu.IsReadOnly = false;
				colvarIdNhomTaiLieu.DefaultSetting = @"";
				
					colvarIdNhomTaiLieu.ForeignKeyTableName = "TblNhomTaiLieu";
				schema.Columns.Add(colvarIdNhomTaiLieu);
				
				TableSchema.TableColumn colvarMaLoai = new TableSchema.TableColumn(schema);
				colvarMaLoai.ColumnName = "MaLoai";
				colvarMaLoai.DataType = DbType.AnsiString;
				colvarMaLoai.MaxLength = 50;
				colvarMaLoai.AutoIncrement = false;
				colvarMaLoai.IsNullable = false;
				colvarMaLoai.IsPrimaryKey = false;
				colvarMaLoai.IsForeignKey = false;
				colvarMaLoai.IsReadOnly = false;
				colvarMaLoai.DefaultSetting = @"";
				colvarMaLoai.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMaLoai);
				
				TableSchema.TableColumn colvarTenLoai = new TableSchema.TableColumn(schema);
				colvarTenLoai.ColumnName = "TenLoai";
				colvarTenLoai.DataType = DbType.String;
				colvarTenLoai.MaxLength = 150;
				colvarTenLoai.AutoIncrement = false;
				colvarTenLoai.IsNullable = false;
				colvarTenLoai.IsPrimaryKey = false;
				colvarTenLoai.IsForeignKey = false;
				colvarTenLoai.IsReadOnly = false;
				colvarTenLoai.DefaultSetting = @"";
				colvarTenLoai.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTenLoai);
				
				TableSchema.TableColumn colvarMoTa = new TableSchema.TableColumn(schema);
				colvarMoTa.ColumnName = "MoTa";
				colvarMoTa.DataType = DbType.String;
				colvarMoTa.MaxLength = 500;
				colvarMoTa.AutoIncrement = false;
				colvarMoTa.IsNullable = true;
				colvarMoTa.IsPrimaryKey = false;
				colvarMoTa.IsForeignKey = false;
				colvarMoTa.IsReadOnly = false;
				colvarMoTa.DefaultSetting = @"";
				colvarMoTa.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMoTa);
				
				TableSchema.TableColumn colvarCanTrinhKy = new TableSchema.TableColumn(schema);
				colvarCanTrinhKy.ColumnName = "CanTrinhKy";
				colvarCanTrinhKy.DataType = DbType.Boolean;
				colvarCanTrinhKy.MaxLength = 0;
				colvarCanTrinhKy.AutoIncrement = false;
				colvarCanTrinhKy.IsNullable = false;
				colvarCanTrinhKy.IsPrimaryKey = false;
				colvarCanTrinhKy.IsForeignKey = false;
				colvarCanTrinhKy.IsReadOnly = false;
				
						colvarCanTrinhKy.DefaultSetting = @"((0))";
				colvarCanTrinhKy.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCanTrinhKy);
				
				TableSchema.TableColumn colvarHinhThucKyMacDinh = new TableSchema.TableColumn(schema);
				colvarHinhThucKyMacDinh.ColumnName = "HinhThucKyMacDinh";
				colvarHinhThucKyMacDinh.DataType = DbType.AnsiString;
				colvarHinhThucKyMacDinh.MaxLength = 20;
				colvarHinhThucKyMacDinh.AutoIncrement = false;
				colvarHinhThucKyMacDinh.IsNullable = true;
				colvarHinhThucKyMacDinh.IsPrimaryKey = false;
				colvarHinhThucKyMacDinh.IsForeignKey = false;
				colvarHinhThucKyMacDinh.IsReadOnly = false;
				colvarHinhThucKyMacDinh.DefaultSetting = @"";
				colvarHinhThucKyMacDinh.ForeignKeyTableName = "";
				schema.Columns.Add(colvarHinhThucKyMacDinh);
				
				TableSchema.TableColumn colvarCanGuiKhachHang = new TableSchema.TableColumn(schema);
				colvarCanGuiKhachHang.ColumnName = "CanGuiKhachHang";
				colvarCanGuiKhachHang.DataType = DbType.Boolean;
				colvarCanGuiKhachHang.MaxLength = 0;
				colvarCanGuiKhachHang.AutoIncrement = false;
				colvarCanGuiKhachHang.IsNullable = false;
				colvarCanGuiKhachHang.IsPrimaryKey = false;
				colvarCanGuiKhachHang.IsForeignKey = false;
				colvarCanGuiKhachHang.IsReadOnly = false;
				
						colvarCanGuiKhachHang.DefaultSetting = @"((0))";
				colvarCanGuiKhachHang.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCanGuiKhachHang);
				
				TableSchema.TableColumn colvarCanLuuVatLy = new TableSchema.TableColumn(schema);
				colvarCanLuuVatLy.ColumnName = "CanLuuVatLy";
				colvarCanLuuVatLy.DataType = DbType.Boolean;
				colvarCanLuuVatLy.MaxLength = 0;
				colvarCanLuuVatLy.AutoIncrement = false;
				colvarCanLuuVatLy.IsNullable = false;
				colvarCanLuuVatLy.IsPrimaryKey = false;
				colvarCanLuuVatLy.IsForeignKey = false;
				colvarCanLuuVatLy.IsReadOnly = false;
				
						colvarCanLuuVatLy.DefaultSetting = @"((0))";
				colvarCanLuuVatLy.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCanLuuVatLy);
				
				TableSchema.TableColumn colvarThuTuHienThi = new TableSchema.TableColumn(schema);
				colvarThuTuHienThi.ColumnName = "ThuTuHienThi";
				colvarThuTuHienThi.DataType = DbType.Int32;
				colvarThuTuHienThi.MaxLength = 0;
				colvarThuTuHienThi.AutoIncrement = false;
				colvarThuTuHienThi.IsNullable = false;
				colvarThuTuHienThi.IsPrimaryKey = false;
				colvarThuTuHienThi.IsForeignKey = false;
				colvarThuTuHienThi.IsReadOnly = false;
				
						colvarThuTuHienThi.DefaultSetting = @"((0))";
				colvarThuTuHienThi.ForeignKeyTableName = "";
				schema.Columns.Add(colvarThuTuHienThi);
				
				TableSchema.TableColumn colvarKichHoat = new TableSchema.TableColumn(schema);
				colvarKichHoat.ColumnName = "KichHoat";
				colvarKichHoat.DataType = DbType.Boolean;
				colvarKichHoat.MaxLength = 0;
				colvarKichHoat.AutoIncrement = false;
				colvarKichHoat.IsNullable = false;
				colvarKichHoat.IsPrimaryKey = false;
				colvarKichHoat.IsForeignKey = false;
				colvarKichHoat.IsReadOnly = false;
				
						colvarKichHoat.DefaultSetting = @"((1))";
				colvarKichHoat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarKichHoat);
				
				TableSchema.TableColumn colvarDaXoa = new TableSchema.TableColumn(schema);
				colvarDaXoa.ColumnName = "DaXoa";
				colvarDaXoa.DataType = DbType.Boolean;
				colvarDaXoa.MaxLength = 0;
				colvarDaXoa.AutoIncrement = false;
				colvarDaXoa.IsNullable = false;
				colvarDaXoa.IsPrimaryKey = false;
				colvarDaXoa.IsForeignKey = false;
				colvarDaXoa.IsReadOnly = false;
				
						colvarDaXoa.DefaultSetting = @"((0))";
				colvarDaXoa.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDaXoa);
				
				TableSchema.TableColumn colvarNguoiTao = new TableSchema.TableColumn(schema);
				colvarNguoiTao.ColumnName = "NguoiTao";
				colvarNguoiTao.DataType = DbType.String;
				colvarNguoiTao.MaxLength = 150;
				colvarNguoiTao.AutoIncrement = false;
				colvarNguoiTao.IsNullable = false;
				colvarNguoiTao.IsPrimaryKey = false;
				colvarNguoiTao.IsForeignKey = false;
				colvarNguoiTao.IsReadOnly = false;
				colvarNguoiTao.DefaultSetting = @"";
				colvarNguoiTao.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNguoiTao);
				
				TableSchema.TableColumn colvarNgayTao = new TableSchema.TableColumn(schema);
				colvarNgayTao.ColumnName = "NgayTao";
				colvarNgayTao.DataType = DbType.DateTime;
				colvarNgayTao.MaxLength = 0;
				colvarNgayTao.AutoIncrement = false;
				colvarNgayTao.IsNullable = false;
				colvarNgayTao.IsPrimaryKey = false;
				colvarNgayTao.IsForeignKey = false;
				colvarNgayTao.IsReadOnly = false;
				
						colvarNgayTao.DefaultSetting = @"(getdate())";
				colvarNgayTao.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayTao);
				
				TableSchema.TableColumn colvarNguoiCapNhat = new TableSchema.TableColumn(schema);
				colvarNguoiCapNhat.ColumnName = "NguoiCapNhat";
				colvarNguoiCapNhat.DataType = DbType.String;
				colvarNguoiCapNhat.MaxLength = 150;
				colvarNguoiCapNhat.AutoIncrement = false;
				colvarNguoiCapNhat.IsNullable = true;
				colvarNguoiCapNhat.IsPrimaryKey = false;
				colvarNguoiCapNhat.IsForeignKey = false;
				colvarNguoiCapNhat.IsReadOnly = false;
				colvarNguoiCapNhat.DefaultSetting = @"";
				colvarNguoiCapNhat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNguoiCapNhat);
				
				TableSchema.TableColumn colvarNgayCapNhat = new TableSchema.TableColumn(schema);
				colvarNgayCapNhat.ColumnName = "NgayCapNhat";
				colvarNgayCapNhat.DataType = DbType.DateTime;
				colvarNgayCapNhat.MaxLength = 0;
				colvarNgayCapNhat.AutoIncrement = false;
				colvarNgayCapNhat.IsNullable = true;
				colvarNgayCapNhat.IsPrimaryKey = false;
				colvarNgayCapNhat.IsForeignKey = false;
				colvarNgayCapNhat.IsReadOnly = false;
				colvarNgayCapNhat.DefaultSetting = @"";
				colvarNgayCapNhat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNgayCapNhat);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAccessProvider"].AddSchema("TblLoaiTaiLieu",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("IdLoaiTaiLieu")]
		[Bindable(true)]
		public Guid IdLoaiTaiLieu 
		{
			get { return GetColumnValue<Guid>(Columns.IdLoaiTaiLieu); }
			set { SetColumnValue(Columns.IdLoaiTaiLieu, value); }
		}
		  
		[XmlAttribute("IdNhomTaiLieu")]
		[Bindable(true)]
		public Guid IdNhomTaiLieu 
		{
			get { return GetColumnValue<Guid>(Columns.IdNhomTaiLieu); }
			set { SetColumnValue(Columns.IdNhomTaiLieu, value); }
		}
		  
		[XmlAttribute("MaLoai")]
		[Bindable(true)]
		public string MaLoai 
		{
			get { return GetColumnValue<string>(Columns.MaLoai); }
			set { SetColumnValue(Columns.MaLoai, value); }
		}
		  
		[XmlAttribute("TenLoai")]
		[Bindable(true)]
		public string TenLoai 
		{
			get { return GetColumnValue<string>(Columns.TenLoai); }
			set { SetColumnValue(Columns.TenLoai, value); }
		}
		  
		[XmlAttribute("MoTa")]
		[Bindable(true)]
		public string MoTa 
		{
			get { return GetColumnValue<string>(Columns.MoTa); }
			set { SetColumnValue(Columns.MoTa, value); }
		}
		  
		[XmlAttribute("CanTrinhKy")]
		[Bindable(true)]
		public bool CanTrinhKy 
		{
			get { return GetColumnValue<bool>(Columns.CanTrinhKy); }
			set { SetColumnValue(Columns.CanTrinhKy, value); }
		}
		  
		[XmlAttribute("HinhThucKyMacDinh")]
		[Bindable(true)]
		public string HinhThucKyMacDinh 
		{
			get { return GetColumnValue<string>(Columns.HinhThucKyMacDinh); }
			set { SetColumnValue(Columns.HinhThucKyMacDinh, value); }
		}
		  
		[XmlAttribute("CanGuiKhachHang")]
		[Bindable(true)]
		public bool CanGuiKhachHang 
		{
			get { return GetColumnValue<bool>(Columns.CanGuiKhachHang); }
			set { SetColumnValue(Columns.CanGuiKhachHang, value); }
		}
		  
		[XmlAttribute("CanLuuVatLy")]
		[Bindable(true)]
		public bool CanLuuVatLy 
		{
			get { return GetColumnValue<bool>(Columns.CanLuuVatLy); }
			set { SetColumnValue(Columns.CanLuuVatLy, value); }
		}
		  
		[XmlAttribute("ThuTuHienThi")]
		[Bindable(true)]
		public int ThuTuHienThi 
		{
			get { return GetColumnValue<int>(Columns.ThuTuHienThi); }
			set { SetColumnValue(Columns.ThuTuHienThi, value); }
		}
		  
		[XmlAttribute("KichHoat")]
		[Bindable(true)]
		public bool KichHoat 
		{
			get { return GetColumnValue<bool>(Columns.KichHoat); }
			set { SetColumnValue(Columns.KichHoat, value); }
		}
		  
		[XmlAttribute("DaXoa")]
		[Bindable(true)]
		public bool DaXoa 
		{
			get { return GetColumnValue<bool>(Columns.DaXoa); }
			set { SetColumnValue(Columns.DaXoa, value); }
		}
		  
		[XmlAttribute("NguoiTao")]
		[Bindable(true)]
		public string NguoiTao 
		{
			get { return GetColumnValue<string>(Columns.NguoiTao); }
			set { SetColumnValue(Columns.NguoiTao, value); }
		}
		  
		[XmlAttribute("NgayTao")]
		[Bindable(true)]
		public DateTime NgayTao 
		{
			get { return GetColumnValue<DateTime>(Columns.NgayTao); }
			set { SetColumnValue(Columns.NgayTao, value); }
		}
		  
		[XmlAttribute("NguoiCapNhat")]
		[Bindable(true)]
		public string NguoiCapNhat 
		{
			get { return GetColumnValue<string>(Columns.NguoiCapNhat); }
			set { SetColumnValue(Columns.NguoiCapNhat, value); }
		}
		  
		[XmlAttribute("NgayCapNhat")]
		[Bindable(true)]
		public DateTime? NgayCapNhat 
		{
			get { return GetColumnValue<DateTime?>(Columns.NgayCapNhat); }
			set { SetColumnValue(Columns.NgayCapNhat, value); }
		}
		
		#endregion
		
		
		#region PrimaryKey Methods		
		
        protected override void SetPrimaryKey(object oValue)
        {
            base.SetPrimaryKey(oValue);
            
            SetPKValues();
        }
        
		
		private SweetSoft.QLDA.DataAccess.TblMauTaiLieuCollection colTblMauTaiLieuRecords;
		public SweetSoft.QLDA.DataAccess.TblMauTaiLieuCollection TblMauTaiLieuRecords()
		{
			if(colTblMauTaiLieuRecords == null)
			{
				colTblMauTaiLieuRecords = new SweetSoft.QLDA.DataAccess.TblMauTaiLieuCollection().Where(TblMauTaiLieu.Columns.IdLoaiTaiLieu, IdLoaiTaiLieu).Load();
				colTblMauTaiLieuRecords.ListChanged += new ListChangedEventHandler(colTblMauTaiLieuRecords_ListChanged);
			}
			return colTblMauTaiLieuRecords;
		}
				
		void colTblMauTaiLieuRecords_ListChanged(object sender, ListChangedEventArgs e)
		{
            if (e.ListChangedType == ListChangedType.ItemAdded)
            {
		        // Set foreign key value
		        colTblMauTaiLieuRecords[e.NewIndex].IdLoaiTaiLieu = IdLoaiTaiLieu;
            }
		}
		private SweetSoft.QLDA.DataAccess.TblTaiLieuCollection colTblTaiLieuRecords;
		public SweetSoft.QLDA.DataAccess.TblTaiLieuCollection TblTaiLieuRecords()
		{
			if(colTblTaiLieuRecords == null)
			{
				colTblTaiLieuRecords = new SweetSoft.QLDA.DataAccess.TblTaiLieuCollection().Where(TblTaiLieu.Columns.IdLoaiTaiLieu, IdLoaiTaiLieu).Load();
				colTblTaiLieuRecords.ListChanged += new ListChangedEventHandler(colTblTaiLieuRecords_ListChanged);
			}
			return colTblTaiLieuRecords;
		}
				
		void colTblTaiLieuRecords_ListChanged(object sender, ListChangedEventArgs e)
		{
            if (e.ListChangedType == ListChangedType.ItemAdded)
            {
		        // Set foreign key value
		        colTblTaiLieuRecords[e.NewIndex].IdLoaiTaiLieu = IdLoaiTaiLieu;
            }
		}
		#endregion
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a TblNhomTaiLieu ActiveRecord object related to this TblLoaiTaiLieu
		/// 
		/// </summary>
		public SweetSoft.QLDA.DataAccess.TblNhomTaiLieu TblNhomTaiLieu
		{
			get { return SweetSoft.QLDA.DataAccess.TblNhomTaiLieu.FetchByID(this.IdNhomTaiLieu); }
			set { SetColumnValue("IdNhomTaiLieu", value.IdNhomTaiLieu); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varIdLoaiTaiLieu,Guid varIdNhomTaiLieu,string varMaLoai,string varTenLoai,string varMoTa,bool varCanTrinhKy,string varHinhThucKyMacDinh,bool varCanGuiKhachHang,bool varCanLuuVatLy,int varThuTuHienThi,bool varKichHoat,bool varDaXoa,string varNguoiTao,DateTime varNgayTao,string varNguoiCapNhat,DateTime? varNgayCapNhat)
		{
			TblLoaiTaiLieu item = new TblLoaiTaiLieu();
			
			item.IdLoaiTaiLieu = varIdLoaiTaiLieu;
			
			item.IdNhomTaiLieu = varIdNhomTaiLieu;
			
			item.MaLoai = varMaLoai;
			
			item.TenLoai = varTenLoai;
			
			item.MoTa = varMoTa;
			
			item.CanTrinhKy = varCanTrinhKy;
			
			item.HinhThucKyMacDinh = varHinhThucKyMacDinh;
			
			item.CanGuiKhachHang = varCanGuiKhachHang;
			
			item.CanLuuVatLy = varCanLuuVatLy;
			
			item.ThuTuHienThi = varThuTuHienThi;
			
			item.KichHoat = varKichHoat;
			
			item.DaXoa = varDaXoa;
			
			item.NguoiTao = varNguoiTao;
			
			item.NgayTao = varNgayTao;
			
			item.NguoiCapNhat = varNguoiCapNhat;
			
			item.NgayCapNhat = varNgayCapNhat;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varIdLoaiTaiLieu,Guid varIdNhomTaiLieu,string varMaLoai,string varTenLoai,string varMoTa,bool varCanTrinhKy,string varHinhThucKyMacDinh,bool varCanGuiKhachHang,bool varCanLuuVatLy,int varThuTuHienThi,bool varKichHoat,bool varDaXoa,string varNguoiTao,DateTime varNgayTao,string varNguoiCapNhat,DateTime? varNgayCapNhat)
		{
			TblLoaiTaiLieu item = new TblLoaiTaiLieu();
			
				item.IdLoaiTaiLieu = varIdLoaiTaiLieu;
			
				item.IdNhomTaiLieu = varIdNhomTaiLieu;
			
				item.MaLoai = varMaLoai;
			
				item.TenLoai = varTenLoai;
			
				item.MoTa = varMoTa;
			
				item.CanTrinhKy = varCanTrinhKy;
			
				item.HinhThucKyMacDinh = varHinhThucKyMacDinh;
			
				item.CanGuiKhachHang = varCanGuiKhachHang;
			
				item.CanLuuVatLy = varCanLuuVatLy;
			
				item.ThuTuHienThi = varThuTuHienThi;
			
				item.KichHoat = varKichHoat;
			
				item.DaXoa = varDaXoa;
			
				item.NguoiTao = varNguoiTao;
			
				item.NgayTao = varNgayTao;
			
				item.NguoiCapNhat = varNguoiCapNhat;
			
				item.NgayCapNhat = varNgayCapNhat;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdLoaiTaiLieuColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn IdNhomTaiLieuColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn MaLoaiColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn TenLoaiColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn MoTaColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn CanTrinhKyColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn HinhThucKyMacDinhColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn CanGuiKhachHangColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn CanLuuVatLyColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn ThuTuHienThiColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn KichHoatColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        public static TableSchema.TableColumn DaXoaColumn
        {
            get { return Schema.Columns[11]; }
        }
        
        
        
        public static TableSchema.TableColumn NguoiTaoColumn
        {
            get { return Schema.Columns[12]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayTaoColumn
        {
            get { return Schema.Columns[13]; }
        }
        
        
        
        public static TableSchema.TableColumn NguoiCapNhatColumn
        {
            get { return Schema.Columns[14]; }
        }
        
        
        
        public static TableSchema.TableColumn NgayCapNhatColumn
        {
            get { return Schema.Columns[15]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string IdLoaiTaiLieu = @"IdLoaiTaiLieu";
			 public static string IdNhomTaiLieu = @"IdNhomTaiLieu";
			 public static string MaLoai = @"MaLoai";
			 public static string TenLoai = @"TenLoai";
			 public static string MoTa = @"MoTa";
			 public static string CanTrinhKy = @"CanTrinhKy";
			 public static string HinhThucKyMacDinh = @"HinhThucKyMacDinh";
			 public static string CanGuiKhachHang = @"CanGuiKhachHang";
			 public static string CanLuuVatLy = @"CanLuuVatLy";
			 public static string ThuTuHienThi = @"ThuTuHienThi";
			 public static string KichHoat = @"KichHoat";
			 public static string DaXoa = @"DaXoa";
			 public static string NguoiTao = @"NguoiTao";
			 public static string NgayTao = @"NgayTao";
			 public static string NguoiCapNhat = @"NguoiCapNhat";
			 public static string NgayCapNhat = @"NgayCapNhat";
						
		}
		#endregion
		
		#region Update PK Collections
		
        public void SetPKValues()
        {
                if (colTblMauTaiLieuRecords != null)
                {
                    foreach (SweetSoft.QLDA.DataAccess.TblMauTaiLieu item in colTblMauTaiLieuRecords)
                    {
                        if (item.IdLoaiTaiLieu != IdLoaiTaiLieu)
                        {
                            item.IdLoaiTaiLieu = IdLoaiTaiLieu;
                        }
                    }
               }
		
                if (colTblTaiLieuRecords != null)
                {
                    foreach (SweetSoft.QLDA.DataAccess.TblTaiLieu item in colTblTaiLieuRecords)
                    {
                        if (item.IdLoaiTaiLieu != IdLoaiTaiLieu)
                        {
                            item.IdLoaiTaiLieu = IdLoaiTaiLieu;
                        }
                    }
               }
		}
        #endregion
    
        #region Deep Save
		
        public void DeepSave()
        {
            Save();
            
                if (colTblMauTaiLieuRecords != null)
                {
                    colTblMauTaiLieuRecords.SaveAll();
               }
		
                if (colTblTaiLieuRecords != null)
                {
                    colTblTaiLieuRecords.SaveAll();
               }
		}
        #endregion
	}
}
