using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    /// <summary>
    /// Controller class for TblNhanVien
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblNhanVienController
    {
        // Preload our schema..
        TblNhanVien thisSchemaLoad = new TblNhanVien();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblNhanVienCollection FetchAll()
        {
            TblNhanVienCollection coll = new TblNhanVienCollection();
            Query qry = new Query(TblNhanVien.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblNhanVienCollection FetchByID(object MaNhanVien)
        {
            TblNhanVienCollection coll = new TblNhanVienCollection().Where("MaNhanVien", MaNhanVien).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblNhanVienCollection FetchByQuery(Query qry)
        {
            TblNhanVienCollection coll = new TblNhanVienCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object MaNhanVien)
        {
            return (TblNhanVien.Delete(MaNhanVien) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object MaNhanVien)
        {
            return (TblNhanVien.Destroy(MaNhanVien) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid MaNhanVien,Guid? MaTaiKhoan,Guid? MaPhongBan,Guid? MaChucDanh,string TenNhanVien,DateTime? NgaySinh,string GioiTinh,string MaCCCD,string AnhDaiDien,string DiaChi,DateTime? NgayGiaNhap,string TrinhDo,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
	    {
		    TblNhanVien item = new TblNhanVien();
		    
            item.MaNhanVien = MaNhanVien;
            
            item.MaTaiKhoan = MaTaiKhoan;
            
            item.MaPhongBan = MaPhongBan;
            
            item.MaChucDanh = MaChucDanh;
            
            item.TenNhanVien = TenNhanVien;
            
            item.NgaySinh = NgaySinh;
            
            item.GioiTinh = GioiTinh;
            
            item.MaCCCD = MaCCCD;
            
            item.AnhDaiDien = AnhDaiDien;
            
            item.DiaChi = DiaChi;
            
            item.NgayGiaNhap = NgayGiaNhap;
            
            item.TrinhDo = TrinhDo;
            
            item.DaXoa = DaXoa;
            
            item.NguoiTao = NguoiTao;
            
            item.NgayTao = NgayTao;
            
            item.NguoiCapNhat = NguoiCapNhat;
            
            item.NgayCapNhat = NgayCapNhat;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid MaNhanVien,Guid? MaTaiKhoan,Guid? MaPhongBan,Guid? MaChucDanh,string TenNhanVien,DateTime? NgaySinh,string GioiTinh,string MaCCCD,string AnhDaiDien,string DiaChi,DateTime? NgayGiaNhap,string TrinhDo,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
	    {
		    TblNhanVien item = new TblNhanVien();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.MaNhanVien = MaNhanVien;
				
			item.MaTaiKhoan = MaTaiKhoan;
				
			item.MaPhongBan = MaPhongBan;
				
			item.MaChucDanh = MaChucDanh;
				
			item.TenNhanVien = TenNhanVien;
				
			item.NgaySinh = NgaySinh;
				
			item.GioiTinh = GioiTinh;
				
			item.MaCCCD = MaCCCD;
				
			item.AnhDaiDien = AnhDaiDien;
				
			item.DiaChi = DiaChi;
				
			item.NgayGiaNhap = NgayGiaNhap;
				
			item.TrinhDo = TrinhDo;
				
			item.DaXoa = DaXoa;
				
			item.NguoiTao = NguoiTao;
				
			item.NgayTao = NgayTao;
				
			item.NguoiCapNhat = NguoiCapNhat;
				
			item.NgayCapNhat = NgayCapNhat;
				
	        item.Save(UserName);
	    }
    }
}
