using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    /// <summary>
    /// Controller class for TblPhongBan
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblPhongBanController
    {
        // Preload our schema..
        TblPhongBan thisSchemaLoad = new TblPhongBan();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblPhongBanCollection FetchAll()
        {
            TblPhongBanCollection coll = new TblPhongBanCollection();
            Query qry = new Query(TblPhongBan.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblPhongBanCollection FetchByID(object MaPhongBan)
        {
            TblPhongBanCollection coll = new TblPhongBanCollection().Where("MaPhongBan", MaPhongBan).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblPhongBanCollection FetchByQuery(Query qry)
        {
            TblPhongBanCollection coll = new TblPhongBanCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object MaPhongBan)
        {
            return (TblPhongBan.Delete(MaPhongBan) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object MaPhongBan)
        {
            return (TblPhongBan.Destroy(MaPhongBan) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid MaPhongBan,string TenPhongBan,string MoTa,int ThuTuHienThi,bool KichHoat,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
	    {
		    TblPhongBan item = new TblPhongBan();
		    
            item.MaPhongBan = MaPhongBan;
            
            item.TenPhongBan = TenPhongBan;
            
            item.MoTa = MoTa;
            
            item.ThuTuHienThi = ThuTuHienThi;
            
            item.KichHoat = KichHoat;
            
            item.DaXoa = DaXoa;
            
            item.NguoiTao = NguoiTao;
            
            item.NgayTao = NgayTao;
            
            item.NguoiCapNhat = NguoiCapNhat;
            
            item.NgayCapNhat = NgayCapNhat;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid MaPhongBan,string TenPhongBan,string MoTa,int ThuTuHienThi,bool KichHoat,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
	    {
		    TblPhongBan item = new TblPhongBan();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.MaPhongBan = MaPhongBan;
				
			item.TenPhongBan = TenPhongBan;
				
			item.MoTa = MoTa;
				
			item.ThuTuHienThi = ThuTuHienThi;
				
			item.KichHoat = KichHoat;
				
			item.DaXoa = DaXoa;
				
			item.NguoiTao = NguoiTao;
				
			item.NgayTao = NgayTao;
				
			item.NguoiCapNhat = NguoiCapNhat;
				
			item.NgayCapNhat = NgayCapNhat;
				
	        item.Save(UserName);
	    }
    }
}
