using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblSetting class.
	/// </summary>
    [Serializable]
	public partial class TblSettingCollection : ActiveList<TblSetting, TblSettingCollection>
	{	   
		public TblSettingCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblSettingCollection</returns>
		public TblSettingCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblSetting o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblSettings table.
	/// </summary>
	[Serializable]
	public partial class TblSetting : ActiveRecord<TblSetting>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblSetting()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblSetting(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblSetting(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblSetting(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblSettings", TableType.Table, DataService.GetInstance("DataAccessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "Id";
				colvarId.DataType = DbType.Guid;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = false;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarSettingName = new TableSchema.TableColumn(schema);
				colvarSettingName.ColumnName = "SettingName";
				colvarSettingName.DataType = DbType.String;
				colvarSettingName.MaxLength = 255;
				colvarSettingName.AutoIncrement = false;
				colvarSettingName.IsNullable = false;
				colvarSettingName.IsPrimaryKey = false;
				colvarSettingName.IsForeignKey = false;
				colvarSettingName.IsReadOnly = false;
				
						colvarSettingName.DefaultSetting = @"('')";
				colvarSettingName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSettingName);
				
				TableSchema.TableColumn colvarSettingValue = new TableSchema.TableColumn(schema);
				colvarSettingValue.ColumnName = "SettingValue";
				colvarSettingValue.DataType = DbType.String;
				colvarSettingValue.MaxLength = 1073741823;
				colvarSettingValue.AutoIncrement = false;
				colvarSettingValue.IsNullable = false;
				colvarSettingValue.IsPrimaryKey = false;
				colvarSettingValue.IsForeignKey = false;
				colvarSettingValue.IsReadOnly = false;
				
						colvarSettingValue.DefaultSetting = @"('')";
				colvarSettingValue.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSettingValue);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAccessProvider"].AddSchema("TblSettings",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public Guid Id 
		{
			get { return GetColumnValue<Guid>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("SettingName")]
		[Bindable(true)]
		public string SettingName 
		{
			get { return GetColumnValue<string>(Columns.SettingName); }
			set { SetColumnValue(Columns.SettingName, value); }
		}
		  
		[XmlAttribute("SettingValue")]
		[Bindable(true)]
		public string SettingValue 
		{
			get { return GetColumnValue<string>(Columns.SettingValue); }
			set { SetColumnValue(Columns.SettingValue, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varId,string varSettingName,string varSettingValue)
		{
			TblSetting item = new TblSetting();
			
			item.Id = varId;
			
			item.SettingName = varSettingName;
			
			item.SettingValue = varSettingValue;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varId,string varSettingName,string varSettingValue)
		{
			TblSetting item = new TblSetting();
			
				item.Id = varId;
			
				item.SettingName = varSettingName;
			
				item.SettingValue = varSettingValue;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn SettingNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn SettingValueColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"Id";
			 public static string SettingName = @"SettingName";
			 public static string SettingValue = @"SettingValue";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
