using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
    /// <summary>
    /// Controller class for TblThongBao
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblThongBaoController
    {
        // Preload our schema..
        TblThongBao thisSchemaLoad = new TblThongBao();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblThongBaoCollection FetchAll()
        {
            TblThongBaoCollection coll = new TblThongBaoCollection();
            Query qry = new Query(TblThongBao.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblThongBaoCollection FetchByID(object IdThongBao)
        {
            TblThongBaoCollection coll = new TblThongBaoCollection().Where("IdThongBao", IdThongBao).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblThongBaoCollection FetchByQuery(Query qry)
        {
            TblThongBaoCollection coll = new TblThongBaoCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object IdThongBao)
        {
            return (TblThongBao.Delete(IdThongBao) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object IdThongBao)
        {
            return (TblThongBao.Destroy(IdThongBao) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(Guid IdThongBao,Guid UserId,Guid? IdCongViec,Guid? IdDuAn,string TieuDe,string NoiDung,string LoaiThongBao,string DuongDanLienKet,bool DaDoc,DateTime? NgayDoc,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
	    {
		    TblThongBao item = new TblThongBao();
		    
            item.IdThongBao = IdThongBao;
            
            item.UserId = UserId;
            
            item.IdCongViec = IdCongViec;
            
            item.IdDuAn = IdDuAn;
            
            item.TieuDe = TieuDe;
            
            item.NoiDung = NoiDung;
            
            item.LoaiThongBao = LoaiThongBao;
            
            item.DuongDanLienKet = DuongDanLienKet;
            
            item.DaDoc = DaDoc;
            
            item.NgayDoc = NgayDoc;
            
            item.DaXoa = DaXoa;
            
            item.NguoiTao = NguoiTao;
            
            item.NgayTao = NgayTao;
            
            item.NguoiCapNhat = NguoiCapNhat;
            
            item.NgayCapNhat = NgayCapNhat;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(Guid IdThongBao,Guid UserId,Guid? IdCongViec,Guid? IdDuAn,string TieuDe,string NoiDung,string LoaiThongBao,string DuongDanLienKet,bool DaDoc,DateTime? NgayDoc,bool DaXoa,string NguoiTao,DateTime NgayTao,string NguoiCapNhat,DateTime? NgayCapNhat)
	    {
		    TblThongBao item = new TblThongBao();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.IdThongBao = IdThongBao;
				
			item.UserId = UserId;
				
			item.IdCongViec = IdCongViec;
				
			item.IdDuAn = IdDuAn;
				
			item.TieuDe = TieuDe;
				
			item.NoiDung = NoiDung;
				
			item.LoaiThongBao = LoaiThongBao;
				
			item.DuongDanLienKet = DuongDanLienKet;
				
			item.DaDoc = DaDoc;
				
			item.NgayDoc = NgayDoc;
				
			item.DaXoa = DaXoa;
				
			item.NguoiTao = NguoiTao;
				
			item.NgayTao = NgayTao;
				
			item.NguoiCapNhat = NguoiCapNhat;
				
			item.NgayCapNhat = NgayCapNhat;
				
	        item.Save(UserName);
	    }
    }
}
