using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetSoft.QLDA.DataAccess
{
	/// <summary>
	/// Strongly-typed collection for the TblAuditLog2025 class.
	/// </summary>
    [Serializable]
	public partial class TblAuditLog2025Collection : ActiveList<TblAuditTemp, TblAuditLog2025Collection>
	{	   
		public TblAuditLog2025Collection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TblAuditLog2025Collection</returns>
		public TblAuditLog2025Collection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TblAuditTemp o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the TblAuditLog_2025 table.
	/// </summary>
	[Serializable]
	public partial class TblAuditTemp : ActiveRecord<TblAuditTemp>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TblAuditTemp()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TblAuditTemp(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TblAuditTemp(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TblAuditTemp(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("TblAuditLog_2025", TableType.Table, DataService.GetInstance("DataAccessProvider"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarId = new TableSchema.TableColumn(schema);
				colvarId.ColumnName = "Id";
				colvarId.DataType = DbType.Guid;
				colvarId.MaxLength = 0;
				colvarId.AutoIncrement = false;
				colvarId.IsNullable = false;
				colvarId.IsPrimaryKey = true;
				colvarId.IsForeignKey = false;
				colvarId.IsReadOnly = false;
				colvarId.DefaultSetting = @"";
				colvarId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarId);
				
				TableSchema.TableColumn colvarTitle = new TableSchema.TableColumn(schema);
				colvarTitle.ColumnName = "Title";
				colvarTitle.DataType = DbType.String;
				colvarTitle.MaxLength = 250;
				colvarTitle.AutoIncrement = false;
				colvarTitle.IsNullable = true;
				colvarTitle.IsPrimaryKey = false;
				colvarTitle.IsForeignKey = false;
				colvarTitle.IsReadOnly = false;
				colvarTitle.DefaultSetting = @"";
				colvarTitle.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTitle);
				
				TableSchema.TableColumn colvarCustomerId = new TableSchema.TableColumn(schema);
				colvarCustomerId.ColumnName = "CustomerId";
				colvarCustomerId.DataType = DbType.Guid;
				colvarCustomerId.MaxLength = 0;
				colvarCustomerId.AutoIncrement = false;
				colvarCustomerId.IsNullable = true;
				colvarCustomerId.IsPrimaryKey = false;
				colvarCustomerId.IsForeignKey = false;
				colvarCustomerId.IsReadOnly = false;
				colvarCustomerId.DefaultSetting = @"";
				colvarCustomerId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCustomerId);
				
				TableSchema.TableColumn colvarReferenceId = new TableSchema.TableColumn(schema);
				colvarReferenceId.ColumnName = "ReferenceId";
				colvarReferenceId.DataType = DbType.Guid;
				colvarReferenceId.MaxLength = 0;
				colvarReferenceId.AutoIncrement = false;
				colvarReferenceId.IsNullable = true;
				colvarReferenceId.IsPrimaryKey = false;
				colvarReferenceId.IsForeignKey = false;
				colvarReferenceId.IsReadOnly = false;
				colvarReferenceId.DefaultSetting = @"";
				colvarReferenceId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarReferenceId);
				
				TableSchema.TableColumn colvarTableName = new TableSchema.TableColumn(schema);
				colvarTableName.ColumnName = "TableName";
				colvarTableName.DataType = DbType.String;
				colvarTableName.MaxLength = 100;
				colvarTableName.AutoIncrement = false;
				colvarTableName.IsNullable = true;
				colvarTableName.IsPrimaryKey = false;
				colvarTableName.IsForeignKey = false;
				colvarTableName.IsReadOnly = false;
				colvarTableName.DefaultSetting = @"";
				colvarTableName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTableName);
				
				TableSchema.TableColumn colvarRecordId = new TableSchema.TableColumn(schema);
				colvarRecordId.ColumnName = "RecordId";
				colvarRecordId.DataType = DbType.Guid;
				colvarRecordId.MaxLength = 0;
				colvarRecordId.AutoIncrement = false;
				colvarRecordId.IsNullable = true;
				colvarRecordId.IsPrimaryKey = false;
				colvarRecordId.IsForeignKey = false;
				colvarRecordId.IsReadOnly = false;
				colvarRecordId.DefaultSetting = @"";
				colvarRecordId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarRecordId);
				
				TableSchema.TableColumn colvarActionType = new TableSchema.TableColumn(schema);
				colvarActionType.ColumnName = "ActionType";
				colvarActionType.DataType = DbType.String;
				colvarActionType.MaxLength = 10;
				colvarActionType.AutoIncrement = false;
				colvarActionType.IsNullable = false;
				colvarActionType.IsPrimaryKey = false;
				colvarActionType.IsForeignKey = false;
				colvarActionType.IsReadOnly = false;
				colvarActionType.DefaultSetting = @"";
				colvarActionType.ForeignKeyTableName = "";
				schema.Columns.Add(colvarActionType);
				
				TableSchema.TableColumn colvarChanges = new TableSchema.TableColumn(schema);
				colvarChanges.ColumnName = "Changes";
				colvarChanges.DataType = DbType.String;
				colvarChanges.MaxLength = -1;
				colvarChanges.AutoIncrement = false;
				colvarChanges.IsNullable = true;
				colvarChanges.IsPrimaryKey = false;
				colvarChanges.IsForeignKey = false;
				colvarChanges.IsReadOnly = false;
				colvarChanges.DefaultSetting = @"";
				colvarChanges.ForeignKeyTableName = "";
				schema.Columns.Add(colvarChanges);
				
				TableSchema.TableColumn colvarIPAddress = new TableSchema.TableColumn(schema);
				colvarIPAddress.ColumnName = "IPAddress";
				colvarIPAddress.DataType = DbType.String;
				colvarIPAddress.MaxLength = 50;
				colvarIPAddress.AutoIncrement = false;
				colvarIPAddress.IsNullable = true;
				colvarIPAddress.IsPrimaryKey = false;
				colvarIPAddress.IsForeignKey = false;
				colvarIPAddress.IsReadOnly = false;
				colvarIPAddress.DefaultSetting = @"";
				colvarIPAddress.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIPAddress);
				
				TableSchema.TableColumn colvarUserAgent = new TableSchema.TableColumn(schema);
				colvarUserAgent.ColumnName = "UserAgent";
				colvarUserAgent.DataType = DbType.String;
				colvarUserAgent.MaxLength = -1;
				colvarUserAgent.AutoIncrement = false;
				colvarUserAgent.IsNullable = true;
				colvarUserAgent.IsPrimaryKey = false;
				colvarUserAgent.IsForeignKey = false;
				colvarUserAgent.IsReadOnly = false;
				colvarUserAgent.DefaultSetting = @"";
				colvarUserAgent.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUserAgent);
				
				TableSchema.TableColumn colvarUserId = new TableSchema.TableColumn(schema);
				colvarUserId.ColumnName = "UserId";
				colvarUserId.DataType = DbType.Guid;
				colvarUserId.MaxLength = 0;
				colvarUserId.AutoIncrement = false;
				colvarUserId.IsNullable = true;
				colvarUserId.IsPrimaryKey = false;
				colvarUserId.IsForeignKey = false;
				colvarUserId.IsReadOnly = false;
				colvarUserId.DefaultSetting = @"";
				colvarUserId.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUserId);
				
				TableSchema.TableColumn colvarChangedBy = new TableSchema.TableColumn(schema);
				colvarChangedBy.ColumnName = "ChangedBy";
				colvarChangedBy.DataType = DbType.String;
				colvarChangedBy.MaxLength = 150;
				colvarChangedBy.AutoIncrement = false;
				colvarChangedBy.IsNullable = true;
				colvarChangedBy.IsPrimaryKey = false;
				colvarChangedBy.IsForeignKey = false;
				colvarChangedBy.IsReadOnly = false;
				colvarChangedBy.DefaultSetting = @"";
				colvarChangedBy.ForeignKeyTableName = "";
				schema.Columns.Add(colvarChangedBy);
				
				TableSchema.TableColumn colvarChangedAt = new TableSchema.TableColumn(schema);
				colvarChangedAt.ColumnName = "ChangedAt";
				colvarChangedAt.DataType = DbType.DateTime;
				colvarChangedAt.MaxLength = 0;
				colvarChangedAt.AutoIncrement = false;
				colvarChangedAt.IsNullable = false;
				colvarChangedAt.IsPrimaryKey = true;
				colvarChangedAt.IsForeignKey = false;
				colvarChangedAt.IsReadOnly = false;
				
						colvarChangedAt.DefaultSetting = @"(getdate())";
				colvarChangedAt.ForeignKeyTableName = "";
				schema.Columns.Add(colvarChangedAt);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DataAccessProvider"].AddSchema("TblAuditLog_2025",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Id")]
		[Bindable(true)]
		public Guid Id 
		{
			get { return GetColumnValue<Guid>(Columns.Id); }
			set { SetColumnValue(Columns.Id, value); }
		}
		  
		[XmlAttribute("Title")]
		[Bindable(true)]
		public string Title 
		{
			get { return GetColumnValue<string>(Columns.Title); }
			set { SetColumnValue(Columns.Title, value); }
		}
		  
		[XmlAttribute("CustomerId")]
		[Bindable(true)]
		public Guid? CustomerId 
		{
			get { return GetColumnValue<Guid?>(Columns.CustomerId); }
			set { SetColumnValue(Columns.CustomerId, value); }
		}
		  
		[XmlAttribute("ReferenceId")]
		[Bindable(true)]
		public Guid? ReferenceId 
		{
			get { return GetColumnValue<Guid?>(Columns.ReferenceId); }
			set { SetColumnValue(Columns.ReferenceId, value); }
		}
		  
		[XmlAttribute("TableName")]
		[Bindable(true)]
		public string TableName 
		{
			get { return GetColumnValue<string>(Columns.TableName); }
			set { SetColumnValue(Columns.TableName, value); }
		}
		  
		[XmlAttribute("RecordId")]
		[Bindable(true)]
		public Guid? RecordId 
		{
			get { return GetColumnValue<Guid?>(Columns.RecordId); }
			set { SetColumnValue(Columns.RecordId, value); }
		}
		  
		[XmlAttribute("ActionType")]
		[Bindable(true)]
		public string ActionType 
		{
			get { return GetColumnValue<string>(Columns.ActionType); }
			set { SetColumnValue(Columns.ActionType, value); }
		}
		  
		[XmlAttribute("Changes")]
		[Bindable(true)]
		public string Changes 
		{
			get { return GetColumnValue<string>(Columns.Changes); }
			set { SetColumnValue(Columns.Changes, value); }
		}
		  
		[XmlAttribute("IPAddress")]
		[Bindable(true)]
		public string IPAddress 
		{
			get { return GetColumnValue<string>(Columns.IPAddress); }
			set { SetColumnValue(Columns.IPAddress, value); }
		}
		  
		[XmlAttribute("UserAgent")]
		[Bindable(true)]
		public string UserAgent 
		{
			get { return GetColumnValue<string>(Columns.UserAgent); }
			set { SetColumnValue(Columns.UserAgent, value); }
		}
		  
		[XmlAttribute("UserId")]
		[Bindable(true)]
		public Guid? UserId 
		{
			get { return GetColumnValue<Guid?>(Columns.UserId); }
			set { SetColumnValue(Columns.UserId, value); }
		}
		  
		[XmlAttribute("ChangedBy")]
		[Bindable(true)]
		public string ChangedBy 
		{
			get { return GetColumnValue<string>(Columns.ChangedBy); }
			set { SetColumnValue(Columns.ChangedBy, value); }
		}
		  
		[XmlAttribute("ChangedAt")]
		[Bindable(true)]
		public DateTime ChangedAt 
		{
			get { return GetColumnValue<DateTime>(Columns.ChangedAt); }
			set { SetColumnValue(Columns.ChangedAt, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(Guid varId,string varTitle,Guid? varCustomerId,Guid? varReferenceId,string varTableName,Guid? varRecordId,string varActionType,string varChanges,string varIPAddress,string varUserAgent,Guid? varUserId,string varChangedBy,DateTime varChangedAt)
		{
			TblAuditTemp item = new TblAuditTemp();
			
			item.Id = varId;
			
			item.Title = varTitle;
			
			item.CustomerId = varCustomerId;
			
			item.ReferenceId = varReferenceId;
			
			item.TableName = varTableName;
			
			item.RecordId = varRecordId;
			
			item.ActionType = varActionType;
			
			item.Changes = varChanges;
			
			item.IPAddress = varIPAddress;
			
			item.UserAgent = varUserAgent;
			
			item.UserId = varUserId;
			
			item.ChangedBy = varChangedBy;
			
			item.ChangedAt = varChangedAt;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(Guid varId,string varTitle,Guid? varCustomerId,Guid? varReferenceId,string varTableName,Guid? varRecordId,string varActionType,string varChanges,string varIPAddress,string varUserAgent,Guid? varUserId,string varChangedBy,DateTime varChangedAt)
		{
			TblAuditTemp item = new TblAuditTemp();
			
				item.Id = varId;
			
				item.Title = varTitle;
			
				item.CustomerId = varCustomerId;
			
				item.ReferenceId = varReferenceId;
			
				item.TableName = varTableName;
			
				item.RecordId = varRecordId;
			
				item.ActionType = varActionType;
			
				item.Changes = varChanges;
			
				item.IPAddress = varIPAddress;
			
				item.UserAgent = varUserAgent;
			
				item.UserId = varUserId;
			
				item.ChangedBy = varChangedBy;
			
				item.ChangedAt = varChangedAt;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn IdColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn TitleColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn CustomerIdColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn ReferenceIdColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn TableNameColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn RecordIdColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn ActionTypeColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn ChangesColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn IPAddressColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn UserAgentColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn UserIdColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        public static TableSchema.TableColumn ChangedByColumn
        {
            get { return Schema.Columns[11]; }
        }
        
        
        
        public static TableSchema.TableColumn ChangedAtColumn
        {
            get { return Schema.Columns[12]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Id = @"Id";
			 public static string Title = @"Title";
			 public static string CustomerId = @"CustomerId";
			 public static string ReferenceId = @"ReferenceId";
			 public static string TableName = @"TableName";
			 public static string RecordId = @"RecordId";
			 public static string ActionType = @"ActionType";
			 public static string Changes = @"Changes";
			 public static string IPAddress = @"IPAddress";
			 public static string UserAgent = @"UserAgent";
			 public static string UserId = @"UserId";
			 public static string ChangedBy = @"ChangedBy";
			 public static string ChangedAt = @"ChangedAt";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
