//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweetSoft.QLDA.BackOffice.Controls.Dashboard
{
    public partial class CtrlDashboardCost
    {
        protected global::SweetSoft.QLDA.Controls.ExtraDropdown ddlProjectFilter;

        protected global::SweetSoft.QLDA.Controls.ExtraDropdown ddlCompletionPeriod;

        protected global::SweetSoft.QLDA.Controls.ExtraButton btnApplyCostFilter;
    }
}
