using OfficeOpenXml;
using OfficeOpenXml.Drawing;
using OfficeOpenXml.FormulaParsing;
using OfficeOpenXml.Style;
using SubSonic;
using SweetSoft.QLDA.Core.EnumHelper;
using SweetSoft.QLDA.Core.Helpers;
using SweetSoft.QLDA.Core.Infrastructure;
using SweetSoft.QLDA.Core.Managers;
using SweetSoft.QLDA.Core.Utils;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.IO;
using System.IO.Packaging;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;
using System.Web;
using static SweetSoft.QLDA.Core.SysManager.LogActions;
//---------------------- PROGRAMMER LOG ----------------------//
//Created by: Truong, 09 Apr 2025
namespace SweetSoft.QLDA.Core.ExcelManager
{
    public class ExcelExportCore
    {
        private static readonly Color DefaultHeaderColor = ColorTranslator.FromHtml("#002c6c");

        public ExcelExportCore(DataProvider dataProvider = null)
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
        }

        public byte[] ExportToExcelMultipleSheets(Dictionary<string, DataTable> sheetData, string subject, ExcelExportOptions options, Action<int> onRowProcessed = null)
        {
            if (sheetData == null || sheetData.Count == 0)
            {
                return null;
            }

            var context = CreateExportContext(subject);
            options = EnsureOptions(options);
            ApplyDefaultDocumentOptions(options, context);

            var baseHeaderLines = CloneHeaderLines(options.HeaderRows);

            var worksheets = sheetData
                .Where(entry => entry.Value != null)
                .Select(entry => new WorksheetRequest
                {
                    SheetName = entry.Key,
                    Table = entry.Value,
                    Rows = entry.Value.Rows.Cast<DataRow>(),
                    Options = options,
                    HeaderLines = CreateSheetHeaderLines(baseHeaderLines, entry.Value.Rows.Count, includeRowCount: true)
                })
                .ToList();

            return GenerateWorkbook(worksheets, onRowProcessed);
        }

        public byte[] ExportToExcelFromPagedTable(DataTable table, string subject, int maxRowsPerSheet, string baseSheetName, ExcelExportOptions options, Action<int> onRowProcessed = null)
        {
            if (table == null || table.Rows.Count == 0)
            {
                return null;
            }

            var context = CreateExportContext(subject);
            options = EnsureOptions(options);
            ApplyDefaultDocumentOptions(options, context);

            var baseHeaderLines = CloneHeaderLines(options.HeaderRows);

            int totalRows = table.Rows.Count;
            int sheetCount = (int)Math.Ceiling(totalRows / (double)maxRowsPerSheet);
            var worksheets = new List<WorksheetRequest>();

            for (int sheetIndex = 0; sheetIndex < sheetCount; sheetIndex++)
            {
                int startRowIndex = sheetIndex * maxRowsPerSheet;
                int length = Math.Min(maxRowsPerSheet, totalRows - startRowIndex);
                var rows = table.AsEnumerable().Skip(startRowIndex).Take(length).ToList();

                worksheets.Add(new WorksheetRequest
                {
                    SheetName = sheetIndex == 0 ? baseSheetName : $"{baseSheetName}_{sheetIndex + 1}",
                    Table = table,
                    Rows = rows,
                    Options = options,
                    HeaderLines = CreateSheetHeaderLines(baseHeaderLines, rows.Count, includeRowCount: true)
                });
            }

            return GenerateWorkbook(worksheets, onRowProcessed);
        }

        public byte[] ExportToExcelMultipleSheets(List<ExcelSheetItem> sheets, string subject, Action<int> onRowProcessed = null)
        {
            if (sheets == null || sheets.Count == 0)
            {
                return null;
            }

            string appVersion = Assembly.GetExecutingAssembly().GetName().Version.ToString();

            foreach (var sheet in sheets.Where(sheet => sheet?.Options != null))
            {
                var options = EnsureOptions(sheet.Options);
                options.EvenRowColor = Color.White;
                options.OddRowColor = Color.FromArgb(240, 240, 240);

                options.ExcelProperties = sheet.Options.ExcelProperties ?? new ExcelDocumentProperties();
                options.ExcelProperties.Title = subject;
                options.ExcelProperties.Subject = subject;
                options.ExcelProperties.Comments = $"Generated by PM Quản Lý Dự Án {appVersion}";
            }

            var worksheets = sheets
                .Where(sheet => sheet?.Table != null)
                .Select(sheet => new WorksheetRequest
                {
                    SheetName = sheet.SheetName,
                    Table = sheet.Table,
                    Rows = sheet.Table.Rows.Cast<DataRow>(),
                    Options = EnsureOptions(sheet.Options),
                    HeaderLines = CloneHeaderLines(sheet.Options?.HeaderRows)
                })
                .ToList();

            return GenerateWorkbook(worksheets, onRowProcessed);
        }

        public byte[] ExportExcel(string sqlQuery, string subject, Action<int> onRowProcessed = null)
        {
            if (string.IsNullOrWhiteSpace(sqlQuery))
            {
                return null;
            }

            var context = CreateExportContext(subject);
            var options = BuildDefaultOptions(context);

            DataTable data = GetDataTable(sqlQuery);
            return ExportExcel(data, options, onRowProcessed);
        }

        public byte[] ExportExcel(string sqlQuery, ExcelExportOptions options, Action<int> onRowProcessed = null)
        {
            DataTable dt = GetDataTable(sqlQuery);
            return ExportExcel(dt, options, onRowProcessed);
        }

        public byte[] ExportExcel(DataTable dt, ExcelExportOptions options, Action<int> onRowProcessed = null)
        {
            if (dt == null)
                dt = new DataTable();
            options = EnsureOptions(options);

            var headerLines = CreateSheetHeaderLines(CloneHeaderLines(options.HeaderRows), dt.Rows.Count, includeRowCount: true);

            var worksheets = new List<WorksheetRequest>
            {
                new WorksheetRequest
                {
                    SheetName = options.SheetName,
                    Table = dt,
                    Rows = dt.Rows.Cast<DataRow>(),
                    Options = options,
                    HeaderLines = headerLines
                }
            };

            return GenerateWorkbook(worksheets, onRowProcessed);
        }

        public byte[] ExportExcel(DataTable dt, string subject, ExcelExportOptions options, Action<int> onRowProcessed = null)
        {
            if (dt == null)
                dt = new DataTable();

            var context = CreateExportContext(subject);
            options = EnsureOptions(options);
            ApplyDefaultDocumentOptions(options, context);

            var worksheets = new List<WorksheetRequest>
            {
                new WorksheetRequest
                {
                    SheetName = options.SheetName,
                    Table = dt,
                    Rows = dt.Rows.Cast<DataRow>(),
                    Options = options,
                    HeaderLines = CreateSheetHeaderLines(CloneHeaderLines(options.HeaderRows), dt.Rows.Count, includeRowCount: true)
                }
            };

            return GenerateWorkbook(worksheets, onRowProcessed);
        }

        private byte[] GenerateWorkbook(IEnumerable<WorksheetRequest> worksheetRequests, Action<int> onRowProcessed)
        {
            using (var package = new ExcelPackage())
            {
                var workbook = package.Workbook;
                var usedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

                foreach (var request in worksheetRequests)
                {
                    if (request == null)
                    {
                        continue;
                    }

                    var options = EnsureOptions(request.Options);
                    ApplyWorkbookProperties(package, options);

                    var sheetName = GetUniqueSheetName(workbook, request.SheetName);
                    sheetName = EnsureUniqueWorksheetName(sheetName, usedNames);
                    usedNames.Add(sheetName);

                    var worksheet = workbook.Worksheets.Add(sheetName);

                    ApplyProtection(package, worksheet, options);

                    var headerLines = request.HeaderLines ?? new List<HeaderLine>();
                    WriteWorksheet(worksheet, request.Table, request.Rows, headerLines, options, onRowProcessed);
                }

                return package.GetAsByteArray();
            }
        }

        private void WriteWorksheet(ExcelWorksheet worksheet, DataTable table, IEnumerable<DataRow> rows, IList<HeaderLine> headerLines, ExcelExportOptions options, Action<int> onRowProcessed)
        {
            var effectiveRows = rows?.ToList() ?? table?.Rows.Cast<DataRow>().ToList() ?? new List<DataRow>();
            var displayColumns = ResolveDisplayColumns(table, options);
            int columnCount = Math.Max(1, displayColumns.Count);

            var originalHeaderRows = options.HeaderRows;
            options.HeaderRows = headerLines?.ToList();

            int row = 1;

            if (options.LogoImageBytes != null)
            {
                row = options.IsLogoCenter ? AddLogoCenter(worksheet, options) : AddLogo(worksheet, options);
                if (row == 0)
                {
                    row = 1;
                }
            }

            row = AddHeaders(worksheet, options, columnCount, row);

            int headerRowIndex = AddColumnHeaders(worksheet, displayColumns, row);
            if (options.IsFixedHeader)
            {
                worksheet.View.FreezePanes(headerRowIndex + 1, 1);
            }

            options.HeaderRows = originalHeaderRows;

            WriteDataRows(worksheet, table, effectiveRows, headerRowIndex, options, displayColumns, onRowProcessed);

            ApplyMergeCells(worksheet, options);
            ApplyGrouping(worksheet, options);
            ///

            ///
            AddCharts(worksheet, table, headerRowIndex, options);

            if (options.MasterDetailOptions == null)
            {
                ApplyColumnStyles(worksheet, table, headerRowIndex, options);
            }

            AdjustColumnWidth(worksheet, options, displayColumns);
            worksheet.View.ShowGridLines = options.ShowGridLines;
        }

        private ExportContext CreateExportContext(string subject)
        {
            string exportDate = FormatHelpers.ConvertDateTimeToStringByLanguage(DateTime.UtcNow, true, null);
            string exportBy = SweetContext.Current.User.DisplayName ?? "PM Quản Lý Dự Án";
            string userName = SweetContext.Current.UserName ?? "PM Quản Lý Dự Án";
            string companyName = SettingManager.Instance.GetSettingValue(SettingKeys.CompanyName);
            string logoPath = HttpContext.Current?.Server.MapPath("~/Styles/images/logo-export.png");
            byte[] logoBytes = !string.IsNullOrEmpty(logoPath) && File.Exists(logoPath)
                ? File.ReadAllBytes(logoPath)
                : null;

            string appVersion = Assembly.GetExecutingAssembly().GetName().Version.ToString();

            return new ExportContext
            {
                Subject = subject,
                ExportDate = exportDate,
                ExportBy = exportBy,
                UserName = userName,
                CompanyName = companyName,
                LogoBytes = logoBytes,
                AppVersion = appVersion
            };
        }

        private ExcelExportOptions EnsureOptions(ExcelExportOptions options)
        {
            return options ?? new ExcelExportOptions();
        }

        private ExcelExportOptions BuildDefaultOptions(ExportContext context)
        {
            var options = new ExcelExportOptions
            {
                SheetName = context.Subject,
                HeaderRows = CreateHeaderLines(context),
                IsFixedHeader = true,
                EnableZebraStripe = true,
                EvenRowColor = Color.White,
                OddRowColor = Color.FromArgb(240, 240, 240),
                LogoImageBytes = context.LogoBytes,
                ImageType = ePictureType.Png,
                LogoHeight = 80,
                LogoWidth = 256,
                LogoCols = 3,
                IsLogoCenter = true,
                DecryptColumns = new HashSet<string>(),
                ExcelProperties = new ExcelDocumentProperties
                {
                    Title = context.Subject,
                    Author = context.ExportBy,
                    Subject = context.Subject,
                    Comments = $"Tạo bởi PM Quản Lý Dự Án {context.AppVersion}",
                    Company = context.CompanyName,
                    LastSaveBy = context.ExportBy
                },
                ExcelProtections = new ExcelProtectionOptions
                {
                    Password = context.UserName.ToLower(),
                    ProtectWorkbookStructure = false,
                    ProtectWorksheet = false,
                    AllowSelectUnlockedCells = true,
                    AllowFormatCells = false,
                    AllowSort = false
                },
                ConditionalFormats = new List<ConditionalFormat>
                {
                    new ConditionalFormat
                    {
                        ColumnName = "Payment_Status",
                        Condition = val => val?.ToString() == "Failed",
                        HighlightColor = Color.Red
                    }
                }
            };

            options.HeaderRows.Add(new HeaderLine { Text = "Ngày xuất báo cáo: " + context.ExportDate, FontSize = 12 });
            options.HeaderRows.Add(new HeaderLine { Text = "Người xuất báo cáo: " + context.ExportBy, FontSize = 12 });

            options.ColumnStyles = new Dictionary<string, Action<ExcelRange>>
            {
                { "Order_Date", CreateDateStyle() },
                { "Transaction_Date", CreateDateStyle() },
                { "Order_Status", range => range.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center },
                { "Payment_Status", CreateDateStyle() },
                { "Sub_Total", CreateCurrencyStyle() },
                { "Total_Amount", CreateCurrencyStyle() },
                { "Total_Amount_Paid", CreateCurrencyStyle() }
            };

            return options;
        }

        private void ApplyDefaultDocumentOptions(ExcelExportOptions options, ExportContext context)
        {
            options.HeaderRows = CreateHeaderLines(context);
            options.HeaderRows.Add(new HeaderLine { Text = "Ngày xuất báo cáo: " + context.ExportDate, FontSize = 12 });
            options.HeaderRows.Add(new HeaderLine { Text = "Người xuất báo cáo: " + context.ExportBy, FontSize = 12 });

            options.EvenRowColor = Color.White;
            options.OddRowColor = Color.FromArgb(240, 240, 240);
            options.LogoImageBytes = context.LogoBytes;

            options.ExcelProperties = options.ExcelProperties ?? new ExcelDocumentProperties();
            options.ExcelProperties.Title = context.Subject;
            options.ExcelProperties.Author = context.ExportBy;
            options.ExcelProperties.Subject = context.Subject;
            options.ExcelProperties.Comments = $"Tạo bởi PM Quản Lý Dự Án {context.AppVersion}";
            options.ExcelProperties.Company = context.CompanyName;
            options.ExcelProperties.LastSaveBy = context.ExportBy;

            if (options.ExcelProtections == null)
            {
                options.ExcelProtections = new ExcelProtectionOptions
                {
                    Password = context.UserName?.ToLower(),
                    ProtectWorkbookStructure = false,
                    ProtectWorksheet = false,
                    AllowSelectUnlockedCells = true,
                    AllowFormatCells = false,
                    AllowSort = false
                };
            }
        }

        private List<HeaderLine> CreateHeaderLines(ExportContext context)
        {
            var headers = new List<HeaderLine>
            {
                new HeaderLine { Text = context.CompanyName, FontSize = 16, Bold = true, FontColor = DefaultHeaderColor },
                new HeaderLine { Text = context.Subject, FontSize = 14, Bold = true, FontColor = Color.Black }
            };

            return headers;
        }

        private List<HeaderLine> CreateSheetHeaderLines(IEnumerable<HeaderLine> baseHeaderLines, int rowCount, bool includeRowCount)
        {
            var headers = CloneHeaderLines(baseHeaderLines);
            if (includeRowCount)
            {
                headers.Add(new HeaderLine { Text = $"Tổng số dòng: {rowCount}", FontSize = 12 });
            }

            return headers;
        }

        private List<HeaderLine> CloneHeaderLines(IEnumerable<HeaderLine> headers)
        {
            if (headers == null)
            {
                return new List<HeaderLine>();
            }

            return headers
                .Select(header => new HeaderLine
                {
                    Text = header.Text,
                    FontSize = header.FontSize,
                    Bold = header.Bold,
                    FontColor = header.FontColor,
                    HorizontalAlignment = header.HorizontalAlignment
                })
                .ToList();
        }

        private void ApplyWorkbookProperties(ExcelPackage package, ExcelExportOptions options)
        {
            if (options?.ExcelProperties == null)
            {
                return;
            }

            var props = package.Workbook.Properties;
            props.Title = options.ExcelProperties.Title;
            props.Subject = options.ExcelProperties.Subject;
            props.Author = options.ExcelProperties.Author;
            props.Keywords = options.ExcelProperties.Keywords;
            props.Comments = options.ExcelProperties.Comments;
            props.Company = options.ExcelProperties.Company;
            props.Created = DateTime.UtcNow;
        }

        private void ApplyProtection(ExcelPackage package, ExcelWorksheet worksheet, ExcelExportOptions options)
        {
            if (options?.ExcelProtections == null)
            {
                return;
            }

            if (options.ExcelProtections.ProtectWorkbookStructure)
            {
                package.Workbook.Protection.SetPassword(options.ExcelProtections.Password);
                package.Workbook.Protection.LockStructure = true;
            }

            if (options.ExcelProtections.ProtectWorksheet)
            {
                worksheet.Protection.SetPassword(options.ExcelProtections.Password);
                worksheet.Protection.IsProtected = true;
                worksheet.Protection.AllowSelectLockedCells = options.ExcelProtections.AllowSelectLockedCells;
                worksheet.Protection.AllowSelectUnlockedCells = options.ExcelProtections.AllowSelectUnlockedCells;
                worksheet.Protection.AllowFormatCells = options.ExcelProtections.AllowFormatCells;
                worksheet.Protection.AllowDeleteColumns = options.ExcelProtections.AllowDeleteColumns;
                worksheet.Protection.AllowInsertRows = options.ExcelProtections.AllowInsertRows;
                worksheet.Protection.AllowSort = options.ExcelProtections.AllowSort;
            }
        }

        private string GetUniqueSheetName(ExcelWorkbook workbook, string requestedName)
        {
            string sheetName = string.IsNullOrWhiteSpace(requestedName) ? "Sheet" : requestedName;
            sheetName = sheetName.Length > 31 ? sheetName.Substring(0, 31) : sheetName;
            sheetName = Regex.Replace(sheetName, @"[:\\/?*\[\]]", "_");

            int suffix = 1;
            string uniqueName = sheetName;
            while (workbook.Worksheets.Any(w => string.Equals(w.Name, uniqueName, StringComparison.OrdinalIgnoreCase)))
            {
                uniqueName = $"{sheetName}_{suffix++}";
            }

            return uniqueName;
        }

        private string EnsureUniqueWorksheetName(string sheetName, ISet<string> usedNames)
        {
            string uniqueName = sheetName;
            int suffix = 1;
            while (usedNames.Contains(uniqueName))
            {
                uniqueName = $"{sheetName}_{suffix++}";
            }

            return uniqueName;
        }

        private List<ColumnDisplayInfo> ResolveDisplayColumns(DataTable table, ExcelExportOptions options)
        {
            options = EnsureOptions(options);

            var displayColumns = new List<ColumnDisplayInfo>();
            var showColumns = new List<string>();

            if (options.ShowColumns != null && options.ShowColumns.Any())
            {
                showColumns = options.ShowColumns
                    .Where(columnName => table == null || table.Columns.Contains(columnName))
                    .ToList();
            }
            else if (table != null)
            {
                showColumns = table.Columns.Cast<DataColumn>().Select(column => column.ColumnName).ToList();
            }

            if (table == null && showColumns.Count == 0 && options.ColumnNames != null && options.ShowColumns != null)
            {
                showColumns = options.ColumnNames.Select((_, index) => options.ShowColumns.ElementAtOrDefault(index)).Where(name => !string.IsNullOrEmpty(name)).ToList();
            }

            for (int i = 0; i < showColumns.Count; i++)
            {
                string columnName = showColumns[i];
                string displayName = options.ColumnNames != null && options.ColumnNames.Count > i
                    ? options.ColumnNames[i]
                    : GetDisplayNameFromColumn(columnName);

                displayColumns.Add(new ColumnDisplayInfo
                {
                    ColumnName = columnName,
                    DisplayName = displayName
                });
            }

            if (displayColumns.Count == 0 && table != null)
            {
                displayColumns.AddRange(table.Columns.Cast<DataColumn>().Select(column => new ColumnDisplayInfo
                {
                    ColumnName = column.ColumnName,
                    DisplayName = GetDisplayNameFromColumn(column.ColumnName)
                }));
            }

            return displayColumns;
        }

        private int AddHeaders(ExcelWorksheet worksheet, ExcelExportOptions options, int colCount, int startRow)
        {
            if (options.HeaderRows == null || options.HeaderRows.Count == 0)
            {
                return startRow;
            }

            int currentRow = startRow;
            int startCol = 1;

            foreach (var header in options.HeaderRows)
            {
                var cell = worksheet.Cells[currentRow, startCol, currentRow, colCount];
                cell.Merge = true;
                cell.Value = header.Text;

                if (header.FontSize.HasValue)
                {
                    cell.Style.Font.Size = header.FontSize.Value;
                }

                if (header.Bold.HasValue)
                {
                    cell.Style.Font.Bold = header.Bold.Value;
                }

                if (header.FontColor.HasValue)
                {
                    cell.Style.Font.Color.SetColor(header.FontColor.Value);
                }

                cell.Style.HorizontalAlignment = header.HorizontalAlignment ?? ExcelHorizontalAlignment.Left;
                cell.Style.VerticalAlignment = ExcelVerticalAlignment.Center;

                currentRow++;
            }

            return currentRow;
        }

        private int AddColumnHeaders(ExcelWorksheet worksheet, IList<ColumnDisplayInfo> columns, int row)
        {
            for (int columnIndex = 0; columnIndex < columns.Count; columnIndex++)
            {
                var headerCell = worksheet.Cells[row, columnIndex + 1];
                headerCell.Value = columns[columnIndex].DisplayName;
                headerCell.Style.Font.Bold = true;
                headerCell.Style.Font.Color.SetColor(Color.White);
                headerCell.Style.Font.Size = 14;
                headerCell.Style.Fill.PatternType = ExcelFillStyle.Solid;
                headerCell.Style.Fill.BackgroundColor.SetColor(DefaultHeaderColor);
                headerCell.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                headerCell.Style.VerticalAlignment = ExcelVerticalAlignment.Center;
                headerCell.Style.Border.Top.Style = ExcelBorderStyle.Thin;
                headerCell.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
                headerCell.Style.Border.Left.Style = ExcelBorderStyle.Thin;
                headerCell.Style.Border.Right.Style = ExcelBorderStyle.Thin;
            }

            return row;
        }

        private void WriteDataRows(ExcelWorksheet worksheet, DataTable table, IList<DataRow> rows, int headerRowIndex, ExcelExportOptions options, List<ColumnDisplayInfo> displayColumns, Action<int> onRowProcessed)
        {
            if (rows == null)
            {
                return;
            }

            int rowIdx = headerRowIndex + 1;
            int processed = 0;
            int columnCount = displayColumns.Count;
            bool hasSumColumns = options.SumColumns != null && options.SumColumns.Any();
            var grandTotals = hasSumColumns
                ? options.SumColumns.ToDictionary(column => column, _ => 0m)
                : new Dictionary<string, decimal>();

            string lastGroupValue = null;
            var groupRows = new List<DataRow>();
            int firstSumColumn = GetFirstSumColumnIndex(displayColumns.ToList(), options);

            for (int index = 0; index < rows.Count; index++)
            {
                var dataRow = rows[index];
                string currentGroup = !string.IsNullOrEmpty(options.GroupByColumn) ? dataRow[options.GroupByColumn]?.ToString() : null;

                if (!string.IsNullOrEmpty(options.GroupByColumn) && lastGroupValue != null && !string.Equals(lastGroupValue, currentGroup, StringComparison.Ordinal))
                {
                    AddGroupSummary(worksheet, rowIdx, groupRows, displayColumns.ToList(), options, firstSumColumn);
                    rowIdx++;
                    groupRows.Clear();
                }

                groupRows.Add(dataRow);
                lastGroupValue = currentGroup;

                Color backgroundColor = index % 2 == 0 ? options.EvenRowColor : options.OddRowColor;
                rowIdx = AddMasterRow(worksheet, dataRow, rowIdx, displayColumns, options, backgroundColor, index);

                if (options.MasterDetailOptions != null)
                {
                    rowIdx = AddDetailRows(worksheet, dataRow, rowIdx, displayColumns, options);
                }

                if (hasSumColumns)
                {
                    foreach (var columnInfo in displayColumns)
                    {
                        if (!options.SumColumns.Contains(columnInfo.ColumnName))
                        {
                            continue;
                        }

                        object value = dataRow[columnInfo.ColumnName];
                        if (decimal.TryParse(value?.ToString(), out decimal parsed))
                        {
                            grandTotals[columnInfo.ColumnName] += parsed;
                        }
                    }
                }

                processed++;
                onRowProcessed?.Invoke(processed);
            }

            if (!string.IsNullOrEmpty(options.GroupByColumn) && groupRows.Any())
            {
                AddGroupSummary(worksheet, rowIdx, groupRows, displayColumns, options, firstSumColumn);
                rowIdx++;
            }

            if (options.ShowGrandTotal && hasSumColumns)
            {
                AddGrandTotalRow(worksheet, rowIdx, displayColumns, options, grandTotals, firstSumColumn, columnCount);
            }
        }

        private void AdjustColumnWidth(ExcelWorksheet worksheet, ExcelExportOptions options, IList<ColumnDisplayInfo> displayColumns)
        {
            if (displayColumns == null || displayColumns.Count == 0)
            {
                return;
            }

            int columnCount = displayColumns.Count;

            if (options.ColumnWidths != null && options.ColumnWidths.Count > 0)
            {
                for (int index = 0; index < columnCount; index++)
                {
                    var columnInfo = displayColumns[index];
                    if (options.ColumnWidths.TryGetValue(columnInfo.ColumnName, out double width))
                    {
                        worksheet.Column(index + 1).Width = width;
                    }
                    else
                    {
                        worksheet.Column(index + 1).AutoFit(20, 120);
                    }
                }
            }
            else if (worksheet.Dimension != null)
            {
                worksheet.Cells[1, 1, worksheet.Dimension.End.Row, columnCount].AutoFitColumns();
            }
        }

        private Action<ExcelRange> CreateDateStyle()
        {
            return range =>
            {
                range.Style.Numberformat.Format = "dd-mmm-yyyy";
                range.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
            };
        }

        private Action<ExcelRange> CreateCurrencyStyle()
        {
            return range =>
            {
                range.Style.Numberformat.Format = "#,##0.##";
                range.Style.HorizontalAlignment = ExcelHorizontalAlignment.Right;
            };
        }

        private DataTable GetDataTable(string query)
        {
            using (var reader = new InlineQuery().ExecuteReader(query))
            {
                var table = new DataTable();
                table.Load(reader);
                return table;
            }
        }

        private int AddLogo(ExcelWorksheet worksheet, ExcelExportOptions options)
        {
            if (options.LogoImageBytes == null)
            {
                return 0;
            }

            var picture = worksheet.Drawings.AddPicture("Logo", new MemoryStream(options.LogoImageBytes), options.ImageType);
            picture.SetPosition(0, 0, 0, 0);
            picture.SetSize(options.LogoWidth, options.LogoHeight);

            int headerRowCount = options.HeaderRows?.Count ?? 1;

            worksheet.Cells[1, 1, headerRowCount, options.LogoCols].Merge = true;
            worksheet.Cells[1, 1, headerRowCount, options.LogoCols].Style.Border.BorderAround(ExcelBorderStyle.None);
            worksheet.Cells[1, 1, headerRowCount, options.LogoCols].Style.VerticalAlignment = ExcelVerticalAlignment.Center;

            return 1;
        }

        private int AddLogoCenter(ExcelWorksheet worksheet, ExcelExportOptions options)
        {
            if (options.LogoImageBytes == null)
            {
                return 0;
            }

            int headerRowCount = options.HeaderRows?.Count ?? 1;

            worksheet.Cells[1, 1, headerRowCount, options.LogoCols].Merge = true;
            worksheet.Cells[1, 1, headerRowCount, options.LogoCols].Style.Border.BorderAround(ExcelBorderStyle.None);
            worksheet.Cells[1, 1, headerRowCount, options.LogoCols].Style.VerticalAlignment = ExcelVerticalAlignment.Center;

            double totalHeightPoints = 0;
            for (int i = 1; i <= headerRowCount; i++)
            {
                totalHeightPoints += worksheet.Row(i).Height > 0 ? worksheet.Row(i).Height : worksheet.DefaultRowHeight;
            }

            double totalHeightPixels = totalHeightPoints * 1.555;
            double totalWidthPixels = 0;
            for (int i = 1; i <= options.LogoCols; i++)
            {
                double colWidth = worksheet.Column(i).Width > 0 ? worksheet.Column(i).Width : worksheet.DefaultColWidth;
                totalWidthPixels += colWidth * 7.5;
            }

            int offsetY = Math.Max((int)(totalHeightPixels - options.LogoHeight) / 2, 0);
            int offsetX = Math.Max((int)(totalWidthPixels - options.LogoWidth) / 2, 0);

            var picture = worksheet.Drawings.AddPicture("Logo", new MemoryStream(options.LogoImageBytes), options.ImageType);
            picture.SetPosition(0, Math.Max(offsetY, 0), 0, Math.Max(offsetX, 0));
            picture.SetSize(options.LogoWidth, options.LogoHeight);
            return 1;
        }

        private int AddMasterRow(ExcelWorksheet worksheet, DataRow row, int rowIdx, List<ColumnDisplayInfo> displayColumns, ExcelExportOptions options, Color backgroundColor, int rowIndex)
        {
            int columnCount = displayColumns.Count;
            bool hasMasterDetailOptions = options.MasterDetailOptions != null;

            for (int column = 0; column < columnCount; column++)
            {
                var columnInfo = displayColumns[column];
                string columnName = columnInfo.ColumnName;
                var cell = worksheet.Cells[rowIdx, column + 1];
                object value = row[columnName];

                SetCellValue(cell, value, columnName, options);

                if (hasMasterDetailOptions)
                {
                    ApplyMasterRowStyle(cell, options.MasterDetailOptions);
                }
                else
                {
                    ApplyCellStyle(cell, columnName, value, options, backgroundColor, rowIndex);
                }
            }

            return rowIdx + 1;
        }

        private int AddDetailRows(ExcelWorksheet worksheet, DataRow masterRow, int startRowIdx, List<ColumnDisplayInfo> displayColumns, ExcelExportOptions options)
        {
            if (options.MasterDetailOptions == null)
            {
                return startRowIdx;
            }

            var detailOptions = options.MasterDetailOptions;
            int currentRowIdx = startRowIdx;

            if (detailOptions.DetailDataTable == null || detailOptions.DetailColumns == null || detailOptions.DetailColumns.Count == 0)
            {
                return currentRowIdx;
            }

            object masterKeyValue = masterRow[detailOptions.MasterKeyColumn];
            if (masterKeyValue == null)
            {
                return currentRowIdx;
            }

            var detailRows = detailOptions.DetailDataTable.AsEnumerable()
                .Where(detailRow => detailRow[detailOptions.DetailForeignKeyColumn]?.ToString() == masterKeyValue.ToString())
                .ToList();

            if (!detailRows.Any())
            {
                return currentRowIdx;
            }

            if (detailOptions.ShowDetailHeaders)
            {
                currentRowIdx = AddDetailHeader(worksheet, currentRowIdx, displayColumns, detailOptions);
            }

            foreach (var detailRow in detailRows)
            {
                currentRowIdx = AddDetailRow(worksheet, detailRow, currentRowIdx, displayColumns, detailOptions);
            }

            return currentRowIdx;
        }

        private int AddDetailHeader(ExcelWorksheet worksheet, int rowIdx, List<ColumnDisplayInfo> displayColumns, MasterDetailOptions detailOptions)
        {
            if (detailOptions.DetailColumns == null)
            {
                return rowIdx;
            }

            int startCol = detailOptions.DetailIndentLevel + 1;

            for (int i = 0; i < detailOptions.DetailColumns.Count; i++)
            {
                string columnName = detailOptions.DetailColumns[i];
                var cell = worksheet.Cells[rowIdx, startCol + i];

                string displayName = detailOptions.DetailColumnNames != null && detailOptions.DetailColumnNames.ContainsKey(columnName)
                    ? detailOptions.DetailColumnNames[columnName]
                    : columnName;

                int span = 1;
                if (detailOptions.DetailHeaderMergeRightSpans != null && detailOptions.DetailHeaderMergeRightSpans.TryGetValue(columnName, out var mergeSpan) && mergeSpan > 1)
                {
                    span = mergeSpan;
                    var mergeRange = worksheet.Cells[rowIdx, startCol + i, rowIdx, startCol + i + span - 1];
                    mergeRange.Merge = true;
                    mergeRange.Value = displayName;

                    if (detailOptions.DetailHeaderStyle != null)
                    {
                        ApplyStyle(mergeRange, detailOptions.DetailHeaderStyle);
                    }
                    else
                    {
                        mergeRange.Style.Font.Bold = true;
                        mergeRange.Style.Fill.PatternType = ExcelFillStyle.Solid;
                        mergeRange.Style.Fill.BackgroundColor.SetColor(Color.LightGray);
                    }

                    mergeRange.Style.Border.Top.Style = ExcelBorderStyle.Thin;
                    mergeRange.Style.Border.Left.Style = ExcelBorderStyle.Thin;
                    mergeRange.Style.Border.Right.Style = ExcelBorderStyle.Thin;
                    mergeRange.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
                    mergeRange.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                    mergeRange.Style.VerticalAlignment = ExcelVerticalAlignment.Center;

                    i += span - 1;
                }
                else
                {
                    cell.Value = displayName;

                    if (detailOptions.DetailHeaderStyle != null)
                    {
                        ApplyStyle(cell, detailOptions.DetailHeaderStyle);
                    }
                    else
                    {
                        cell.Style.Font.Bold = true;
                        cell.Style.Fill.PatternType = ExcelFillStyle.Solid;
                        cell.Style.Fill.BackgroundColor.SetColor(Color.LightGray);
                    }

                    cell.Style.Border.Top.Style = ExcelBorderStyle.Thin;
                    cell.Style.Border.Left.Style = ExcelBorderStyle.Thin;
                    cell.Style.Border.Right.Style = ExcelBorderStyle.Thin;
                    cell.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
                    cell.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                    cell.Style.VerticalAlignment = ExcelVerticalAlignment.Center;
                }
            }

            return rowIdx + 1;
        }

        private int AddDetailRow(ExcelWorksheet worksheet, DataRow detailRow, int rowIdx, List<ColumnDisplayInfo> displayColumns, MasterDetailOptions detailOptions)
        {
            if (detailOptions.DetailColumns == null)
            {
                return rowIdx;
            }

            int startCol = detailOptions.DetailIndentLevel + 1;

            for (int i = 0; i < detailOptions.DetailColumns.Count; i++)
            {
                if (i >= detailOptions.DetailColumns.Count)
                {
                    break;
                }

                string columnName = detailOptions.DetailColumns[i];
                var cell = worksheet.Cells[rowIdx, startCol + i];
                object value = detailRow[columnName];

                SetDetailCellValue(cell, value, columnName, detailOptions);
                int skip = ApplyDetailColumnProperties(cell, columnName, detailOptions);
                ApplyDetailCellStyle(cell, columnName, detailOptions);

                cell.Style.Border.Top.Style = ExcelBorderStyle.Thin;
                cell.Style.Border.Left.Style = ExcelBorderStyle.Thin;
                cell.Style.Border.Right.Style = ExcelBorderStyle.Thin;
                cell.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
                i += skip;
            }

            return rowIdx + 1;
        }

        private static string ToExcelMultiline(string input)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(input))
                {
                    return string.Empty;
                }

                var parts = input.Split(new[] { '|' }, StringSplitOptions.RemoveEmptyEntries);
                return string.Join(Environment.NewLine, parts.Select(x => x.Trim()));
            }
            catch
            {
                return input;
            }
        }

        private void SetCellValue(ExcelRange cell, object val, string colName, ExcelExportOptions options)
        {
            if (options.DecryptColumns != null && options.DecryptColumns.Contains(colName))
            {
                cell.Value = SQLEncryption.Decrypt(val);
            }
            else if (options.EnumMappings != null && options.EnumMappings.TryGetValue(colName, out var enumType))
            {
                cell.Value = EnumHelpers.GetERenderText(enumType, val);
            }
            else if (val is DateTime dateTimeValue)
            {
                cell.Value = FormatHelpers.ConvertDateTimeToStringByLanguage(dateTimeValue, false, null);
            }
            else
            {
                var mapping = options.ConditionalMappingTexts?.FirstOrDefault(mp => mp.ColumnName == colName);
                if (mapping != null)
                {
                    string value = val?.ToString();
                    string mappedText = null;

                    if (!string.IsNullOrEmpty(value) && mapping.ValueMappings.TryGetValue(value, out var staticMapped))
                    {
                        mappedText = staticMapped;
                    }
                    else if (mapping.ResolveFromDb != null)
                    {
                        mappedText = mapping.ResolveFromDb(val);
                    }

                    cell.Value = mappedText ?? mapping.DefaultText ?? ToExcelMultiline(val?.ToString());
                }
                else
                {
                    cell.Value = ToExcelMultiline(val?.ToString());
                }
            }
        }

        private void SetDetailCellValue(ExcelRange cell, object val, string colName, MasterDetailOptions detailOptions)
        {
            if (val is DateTime dateTimeValue)
            {
                cell.Value = FormatHelpers.ConvertDateTimeToStringByLanguage(dateTimeValue, false, null);
            }
            else
            {
                var mapping = detailOptions.ConditionalMappingTexts?.FirstOrDefault(mp => mp.ColumnName == colName);
                if (mapping != null)
                {
                    string value = val?.ToString();
                    string mappedText = null;

                    if (!string.IsNullOrEmpty(value) && mapping.ValueMappings.TryGetValue(value, out var staticMapped))
                    {
                        mappedText = staticMapped;
                    }
                    else if (mapping.ResolveFromDb != null)
                    {
                        mappedText = mapping.ResolveFromDb(val);
                    }

                    cell.Value = mappedText ?? mapping.DefaultText ?? ToExcelMultiline(val?.ToString());
                }
                else
                {
                    cell.Value = ToExcelMultiline(val?.ToString());
                }
            }

            if (detailOptions.DetailNumberFormats != null && detailOptions.DetailNumberFormats.TryGetValue(colName, out var format))
            {
                cell.Style.Numberformat.Format = format;
            }
        }

        private void ApplyDetailCellStyle(ExcelRange cell, string colName, MasterDetailOptions detailOptions)
        {
            cell.Style.Border.Top.Style = ExcelBorderStyle.Thin;
            cell.Style.Border.Left.Style = ExcelBorderStyle.Thin;
            cell.Style.Border.Right.Style = ExcelBorderStyle.Thin;
            cell.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;

            if (detailOptions.DetailRowStyle != null)
            {
                ApplyStyle(cell, detailOptions.DetailRowStyle);
            }

            if (detailOptions.DetailColumnStyles != null && detailOptions.DetailColumnStyles.ContainsKey(colName))
            {
                ApplyStyle(cell, detailOptions.DetailColumnStyles[colName]);
            }
        }

        private int ApplyDetailColumnProperties(ExcelRange cell, string colName, MasterDetailOptions detailOptions)
        {
            Color? backgroundColor = null;

            if (detailOptions.DetailColumnBackgroundColors != null && detailOptions.DetailColumnBackgroundColors.TryGetValue(colName, out var color))
            {
                backgroundColor = color;
                cell.Style.Fill.PatternType = ExcelFillStyle.Solid;
                cell.Style.Fill.BackgroundColor.SetColor(color);
            }

            if (detailOptions.DetailColumnTextColors != null && detailOptions.DetailColumnTextColors.TryGetValue(colName, out var textColor))
            {
                cell.Style.Font.Color.SetColor(textColor);
            }

            if (detailOptions.DetailColumnBold != null && detailOptions.DetailColumnBold.TryGetValue(colName, out var bold))
            {
                cell.Style.Font.Bold = bold;
            }

            if (detailOptions.DetailColumnAlignments != null && detailOptions.DetailColumnAlignments.TryGetValue(colName, out var alignment))
            {
                cell.Style.HorizontalAlignment = alignment;
            }

            cell.Style.Border.Top.Style = ExcelBorderStyle.Thin;
            cell.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
            cell.Style.Border.Left.Style = ExcelBorderStyle.Thin;
            cell.Style.Border.Right.Style = ExcelBorderStyle.Thin;

            int skipRight = 0;
            if (detailOptions.DetailColumnMergeRightSpans != null && detailOptions.DetailColumnMergeRightSpans.TryGetValue(colName, out var span) && span > 1)
            {
                var worksheet = cell.Worksheet;
                int row = cell.Start.Row;
                int column = cell.Start.Column;

                var range = worksheet.Cells[row, column, row, column + span - 1];
                range.Merge = true;
                range.Value = cell.Value;
                range.Style.WrapText = true;
                range.Style.VerticalAlignment = ExcelVerticalAlignment.Center;
                range.Style.HorizontalAlignment = cell.Style.HorizontalAlignment;
                range.Style.Font.Bold = cell.Style.Font.Bold;

                if (!string.IsNullOrEmpty(cell.Style.Font.Color.Rgb))
                {
                    range.Style.Font.Color.SetColor(ColorTranslator.FromHtml("#" + cell.Style.Font.Color.Rgb));
                }

                if (backgroundColor.HasValue)
                {
                    range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                    range.Style.Fill.BackgroundColor.SetColor(backgroundColor.Value);
                }

                range.Style.Border.Top.Style = ExcelBorderStyle.Thin;
                range.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
                range.Style.Border.Left.Style = ExcelBorderStyle.Thin;
                range.Style.Border.Right.Style = ExcelBorderStyle.Thin;

                skipRight = span - 1;
            }

            return skipRight;
        }

        private void ApplyMasterRowStyle(ExcelRange cell, MasterDetailOptions detailOptions)
        {
            cell.Style.Border.Top.Style = ExcelBorderStyle.Thin;
            cell.Style.Border.Left.Style = ExcelBorderStyle.Thin;
            cell.Style.Border.Right.Style = ExcelBorderStyle.Thin;
            cell.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;

            if (detailOptions.MasterRowStyle != null)
            {
                ApplyStyle(cell, detailOptions.MasterRowStyle);
            }
            else
            {
                cell.Style.Fill.PatternType = ExcelFillStyle.Solid;
                cell.Style.Fill.BackgroundColor.SetColor(detailOptions.MasterRowBackgroundColor);
                cell.Style.Font.Color.SetColor(detailOptions.MasterRowTextColor);
                cell.Style.Font.Bold = detailOptions.MasterRowBold;
            }
        }

        private void ApplyCellStyle(ExcelRange cell, string colName, object val, ExcelExportOptions options, Color backgroundColor, int rowIndex)
        {
            if (options.WrapTextColumns != null && options.WrapTextColumns.Contains(colName))
            {
                cell.Style.WrapText = true;
                cell.Worksheet.Row(cell.Start.Row).CustomHeight = false;
            }

            cell.Style.Border.Top.Style = ExcelBorderStyle.Thin;
            cell.Style.Border.Left.Style = ExcelBorderStyle.Thin;
            cell.Style.Border.Right.Style = ExcelBorderStyle.Thin;
            cell.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;

            if (options.EnableZebraStripe)
            {
                cell.Style.Fill.PatternType = ExcelFillStyle.Solid;
                cell.Style.Fill.BackgroundColor.SetColor(backgroundColor);
            }

            var conditionalFormat = options.ConditionalFormats?.FirstOrDefault(format => format.ColumnName == colName);
            if (conditionalFormat?.Condition?.Invoke(val) == true)
            {
                cell.Style.Font.Color.SetColor(Color.Red);
                cell.Style.Font.Bold = true;
            }
        }

        private void AddGrandTotalRow(ExcelWorksheet worksheet, int rowIdx, List<ColumnDisplayInfo> displayColumns, ExcelExportOptions options, Dictionary<string, decimal> grandTotals, int firstSumCol, int columnCount)
        {
            for (int column = 0; column < columnCount; column++)
            {
                var cell = worksheet.Cells[rowIdx, column + 1];
                ApplyStyle(cell, options.GrandTotalStyle);
            }

            if (firstSumCol > 0)
            {
                var titleCell = worksheet.Cells[rowIdx, 1, rowIdx, firstSumCol];
                titleCell.Merge = true;
                titleCell.Value = "Grand Total";
                ApplyStyle(titleCell, options.GrandTotalStyle);
            }

            if (options.SumColumns == null || options.SumColumns.Count == 0)
            {
                return;
            }

            foreach (var columnInfo in displayColumns)
            {
                if (!options.SumColumns.Contains(columnInfo.ColumnName))
                {
                    continue;
                }

                var cell = worksheet.Cells[rowIdx, displayColumns.IndexOf(columnInfo) + 1];
                cell.Value = grandTotals[columnInfo.ColumnName];
                ApplyStyle(cell, options.GrandTotalStyle);
            }
        }

        private void AddGroupSummary(ExcelWorksheet worksheet, int rowIdx, List<DataRow> rows, List<ColumnDisplayInfo> displayColumns, ExcelExportOptions options, int firstSumCol)
        {
            int columnCount = displayColumns.Count;

            for (int column = 0; column < columnCount; column++)
            {
                var cell = worksheet.Cells[rowIdx, column + 1];
                ApplyStyle(cell, options.GroupSummaryStyle);
            }

            if (firstSumCol > 0)
            {
                var titleCell = worksheet.Cells[rowIdx, 1, rowIdx, firstSumCol];
                titleCell.Merge = true;
                titleCell.Value = "Group Total";
                ApplyStyle(titleCell, options.GroupSummaryStyle);
            }

            if (options.SumColumns == null || options.SumColumns.Count == 0)
            {
                return;
            }

            foreach (var columnInfo in displayColumns)
            {
                if (!options.SumColumns.Contains(columnInfo.ColumnName))
                {
                    continue;
                }

                decimal sum = rows.Sum(row => decimal.TryParse(row[columnInfo.ColumnName]?.ToString(), out var value) ? value : 0);
                var cell = worksheet.Cells[rowIdx, displayColumns.IndexOf(columnInfo) + 1];
                cell.Value = sum;
                ApplyStyle(cell, options.GroupSummaryStyle);
            }
        }

        private void ApplyStyle(ExcelRange cell, ExcelStyle style)
        {
            if (cell == null || style == null)
            {
                return;
            }

            cell.Style.Border = style.Border;
            cell.Style.Fill = style.Fill;
            cell.Style.Font = style.Font;
            cell.Style.HorizontalAlignment = style.HorizontalAlignment;
            cell.Style.Numberformat = style.Numberformat;
        }

        private void ApplyStyle(ExcelRange cell, ExcelStyleOptions style)
        {
            if (cell == null || style == null)
            {
                return;
            }

            cell.Style.Fill.PatternType = ExcelFillStyle.Solid;
            cell.Style.Fill.BackgroundColor.SetColor(style.BackgroundColor);
            cell.Style.Font.Color.SetColor(style.FontColor);
            cell.Style.Font.Size = style.FontSize;
            cell.Style.Font.Bold = style.Bold;
            cell.Style.HorizontalAlignment = style.HorizontalAlignment;
            cell.Style.Numberformat.Format = style.NumberFormat;
            cell.Style.WrapText = style.WrapText;
        }

        private void ApplyColumnStyles(ExcelWorksheet worksheet, DataTable table, int headerRowIndex, ExcelExportOptions options)
        {
            if (options?.ColumnStyles == null || table == null)
            {
                return;
            }

            foreach (var kvp in options.ColumnStyles)
            {
                int columnIndex = table.Columns.IndexOf(kvp.Key);
                if (columnIndex < 0)
                {
                    continue;
                }

                var range = worksheet.Cells[headerRowIndex + 1, columnIndex + 1, headerRowIndex + table.Rows.Count, columnIndex + 1];
                kvp.Value?.Invoke(range);
            }
        }

        private void ApplyMergeCells(ExcelWorksheet worksheet, ExcelExportOptions options)
        {
            if (options?.MergeCells == null)
            {
                return;
            }

            foreach (var mergeCell in options.MergeCells)
            {
                worksheet.Cells[mergeCell.FromRow, mergeCell.FromCol, mergeCell.ToRow, mergeCell.ToCol].Merge = true;
                worksheet.Cells[mergeCell.FromRow, mergeCell.FromCol].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                worksheet.Cells[mergeCell.FromRow, mergeCell.FromCol].Style.VerticalAlignment = ExcelVerticalAlignment.Center;
            }
        }

        private void ApplyGrouping(ExcelWorksheet worksheet, ExcelExportOptions options)
        {
            if (options?.GroupRowRanges != null)
            {
                foreach (var row in options.GroupRowRanges)
                {
                    for (int i = 1; i <= 3; i++)
                    {
                        worksheet.Row(row + i).OutlineLevel = 1;
                        worksheet.Row(row + i).Collapsed = true;
                    }
                }
            }

            if (options?.GroupColumnRanges != null)
            {
                foreach (var column in options.GroupColumnRanges)
                {
                    for (int i = 1; i <= 2; i++)
                    {
                        worksheet.Column(column + i).OutlineLevel = 1;
                        worksheet.Column(column + i).Collapsed = true;
                    }
                }
            }
        }

        private void AddCharts(ExcelWorksheet worksheet, DataTable table, int headerRowIndex, ExcelExportOptions options)
        {
            if (table == null || options == null)
            {
                return;
            }

            int chartOffsetY = 0;
            int dataRow = 1;

            ExcelWorksheet dataSheet = worksheet;
            if (options.UseHiddenDataSheet)
            {
                dataSheet = worksheet.Workbook.Worksheets.FirstOrDefault(sheet => sheet.Name == "__Data")
                            ?? worksheet.Workbook.Worksheets.Add("__Data");

                for (int i = 0; i < table.Rows.Count; i++)
                {
                    for (int j = 0; j < table.Columns.Count; j++)
                    {
                        dataSheet.Cells[i + 2, j + 1].Value = table.Rows[i][j];
                        dataSheet.Cells[1, j + 1].Value = table.Columns[j].ColumnName;
                    }
                }

                dataSheet.Hidden = eWorkSheetHidden.VeryHidden;
            }

            if (options.GroupedChart != null)
            {
                int groupColumnIndex = table.Columns.IndexOf(options.GroupedChart.GroupByColumn);
                int categoryColumnIndex = table.Columns.IndexOf(options.GroupedChart.CategoryColumn);
                int valueColumnIndex = table.Columns.IndexOf(options.GroupedChart.ValueColumn);

                if (groupColumnIndex >= 0 && categoryColumnIndex >= 0 && valueColumnIndex >= 0)
                {
                    var groups = table.AsEnumerable().GroupBy(row => row[groupColumnIndex] ?? 0);
                    foreach (var group in groups)
                    {
                        var groupList = group.ToList();
                        int groupRowStart = dataRow + 1;

                        if (options.UseHiddenDataSheet)
                        {
                            for (int i = 0; i < groupList.Count; i++)
                            {
                                for (int j = 0; j < table.Columns.Count; j++)
                                {
                                    dataSheet.Cells[groupRowStart + i, j + 1].Value = groupList[i][j];
                                }
                            }
                        }

                        var chart = worksheet.Drawings.AddChart($"chart_{group.Key}", options.GroupedChart.ChartType);
                        chart.Title.Text = $"{options.GroupedChart.ValueColumn} - {group.Key}";
                        chart.SetPosition(headerRowIndex + table.Rows.Count + chartOffsetY + 3, 0, 0, 0);
                        chart.SetSize(800, 400);

                        chart.Series.Add(
                            dataSheet.Cells[groupRowStart, valueColumnIndex + 1, groupRowStart + groupList.Count - 1, valueColumnIndex + 1],
                            dataSheet.Cells[groupRowStart, categoryColumnIndex + 1, groupRowStart + groupList.Count - 1, categoryColumnIndex + 1]);

                        chartOffsetY += groupList.Count + 15;
                        dataRow = groupRowStart + groupList.Count;
                    }
                }
            }

            if (options.Charts != null && options.Charts.Any())
            {
                foreach (var chartConfig in options.Charts)
                {
                    int categoryColumnIndex = table.Columns.IndexOf(chartConfig.CategoryColumn);
                    int valueColumnIndex = table.Columns.IndexOf(chartConfig.ValueColumn);

                    if (categoryColumnIndex < 0 || valueColumnIndex < 0)
                    {
                        continue;
                    }

                    var drawing = worksheet.Drawings.AddChart($"chart_{chartConfig.Title}", chartConfig.ChartType);
                    drawing.Title.Text = chartConfig.Title;
                    drawing.SetPosition(headerRowIndex + table.Rows.Count + chartOffsetY + 3, 0, 0, 0);
                    drawing.SetSize(800, 400);

                    drawing.Series.Add(
                        dataSheet.Cells[2, valueColumnIndex + 1, table.Rows.Count + 1, valueColumnIndex + 1],
                        dataSheet.Cells[2, categoryColumnIndex + 1, table.Rows.Count + 1, categoryColumnIndex + 1]);

                    chartOffsetY += table.Rows.Count + 5;
                }
            }
        }

        private int GetFirstSumColumnIndex(List<ColumnDisplayInfo> displayColumns, ExcelExportOptions options)
        {
            if (displayColumns == null || options?.SumColumns == null)
            {
                return displayColumns?.Count > 0 ? displayColumns.Count - 1 : 0;
            }

            foreach (var column in displayColumns.Select((info, index) => new { info.ColumnName, index }))
            {
                if (options.SumColumns.Contains(column.ColumnName))
                {
                    return column.index;
                }
            }

            return displayColumns.Count > 0 ? displayColumns.Count - 1 : 0;
        }

        private string GetDisplayNameFromColumn(string columnName)
        {
            return AutoGenerateDisplayName(columnName);
        }

        private string AutoGenerateDisplayName(string columnName)
        {
            return Regex.Replace(columnName, "([a-z])([A-Z])", "$1 $2");
        }

        private sealed class WorksheetRequest
        {
            public string SheetName { get; set; }
            public DataTable Table { get; set; }
            public IEnumerable<DataRow> Rows { get; set; }
            public ExcelExportOptions Options { get; set; }
            public List<HeaderLine> HeaderLines { get; set; }
        }

        private sealed class ExportContext
        {
            public string Subject { get; set; }
            public string ExportDate { get; set; }
            public string ExportBy { get; set; }
            public string UserName { get; set; }
            public string CompanyName { get; set; }
            public byte[] LogoBytes { get; set; }
            public string AppVersion { get; set; }
        }
    }
}
